### PR TITLE
Get Kani to run on Apple M1

### LINKED ISSUE #1167: Kani won't install on Apple M1
I've installed kani on Apple M1 running MacOS 11.6.5 with

```
git clone https://github.com/model-checking/kani.git kani
cd kani && git submodule update --init
PATH=$HOME/.cargo/bin:$PATH && cd kani && \
	    ./scripts/setup/macos-10.15/install_deps.sh && \
	    ./scripts/setup/install_rustup.sh && \
	    cargo build --workspace
export PATH=$HOME/.cargo/bin:$(pwd)/kani/scripts:$PATH
```

(Actually, I modified install_deps.h to brew install universal-ctags instead of ctags.)

Now I run kani on a regression test with

```
pushd kani/tests/kani/FunctionCall_NoRet-NoParam/
kani main.rs
```

and I get an exception and stack trace with

```
error: Kani requires the target platform to be `x86_64-unknown-linux-gnu` or `x86_64-apple-darwin`, but it is arm64-apple-macosx11.0.0
error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by ssoudan**
### Description of changes: 

Kani was building on M1 but refusing to perform verifications with the following error: error: Kani requires the target platform to be `x86_64-unknown-linux-gnu` or `x86_64-apple-darwin`, but it is arm64-apple-macosx11.0.0
error: aborting due to previous error. 

Modified check_target() in compiler_interface.rs to accept 'arm64-apple-*', machine_model_from_session() in goto_ctx.rs to use the parameters for this target (added a small cpp in tools/sizeofs/main.cpp to generate these), and fixed a few tests that had hardcoded assumes on type sizes and alignements.

### Resolved issues:

Resolves #1167

### Call-outs:

Not covering any CI aspects.

### Testing:

* How is this change tested?
- "cargo clean ; cargo build --workspace ; ./scripts/kani-regression.sh" tests are passing
- generated a bundle and installed it with cargo-kani setup --use-local-bundle

* Is this a refactor change?
- nope

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: kani-compiler/src/codegen_cprover_gotoc/context/goto_ctx.rs [hunk 1]
```diff
@@ -372,45 +372,90 @@ fn machine_model_from_session(sess: &Session) -> MachineModel {
...
+                char_is_unsigned,
+                char_width,
+                double_width,
+                float_width,
+                int_width,
+                is_big_endian,
+                long_double_width,
+                long_int_width,
+                long_long_int_width,
+                memory_operand_size: int_width / 8,
```
Comment (tedinski) [inline kani-compiler/src/codegen_cprover_gotoc/context/goto_ctx.rs:407]: Good change.

File: tests/kani/Intrinsics/AlignOfVal/align_of_fat_ptr.rs [hunk 2]
```diff
@@ -18,7 +18,10 @@ impl T for A {}
 fn check_align_simple() {
     let a = A { id: 0 };
     let t: &dyn T = &a;
+    #[cfg(target_arch = "x86_64")]
     assert_eq!(align_of_val(t), 8);
+    #[cfg(target_arch = "aarch64")]
+    assert_eq!(align_of_val(t), 16);
```
Comment (tedinski) [inline tests/kani/Intrinsics/AlignOfVal/align_of_fat_ptr.rs:24]: Hmm, note to self: wonder if this will be different on linux arm64.

**Review by tedinski — APPROVED** [review]
Awesome, thanks!

I think I want to change some things, but they're more appropriate for a refactoring followup after I add arm64 linux as well...
