### PR TITLE
Encode string literals as a byte array

### LINKED ISSUE #1665: Kani encodes string slices as null-terminated C slices
In Kani's regression test suite, in [offset_u8_ok.rs](https://github.com/model-checking/kani/blob/main/tests/kani/Intrinsics/Offset/offset_u8_ok.rs#L21), an out-of-bound pointer is dereferenced, but not detected by Kani. Here's a reduced code
```rust
#![feature(core_intrinsics)]
use std::intrinsics::offset;

#[kani::proof]
fn test_offset() {
    let s: &str = "123";
    let ptr: *const u8 = s.as_ptr();
    unsafe {
        let x = *offset(ptr, 3);
    }
}
```

The pointer is 1-passed the bound of the object, so it is "weak_valid", in the sense defined by [CompCert](https://compcert.org/doc/html/compcert.common.Values.html#Val.COMPARISONS.weak_valid_ptr), meaning that it is either in-bound or one-passed-the bound of the object. According to C standard, that is not undefined behaviour, and shouldn't be detected as such. However, it seems that, in addition to check that the pointer can be created, this test also checks that it can be dereferenced which is always UB.

@danielsn mentioned it might be on purpose because the stdlib does that sometimes, but I haven't been able to find an example

### PR DESCRIPTION
**Pull request by zhassan-aws**
### Description of changes: 

Kani currently encodes string slices (`str`) as null-terminated C slices, which is unsound. This PR changes the encoding to a byte array to guarantee that Kani reports pointer accesses outside the slice as invalid dereferences.

### Resolved issues:

Resolves #1665 

### Related RFC:

Optional #ISSUE-NUMBER.

### Testing:

* How is this change tested? A new test was added, and existing tests were slightly modified

* Is this a refactor change? No

### Checklist
- [X] Each commit message has a non-empty body, explaining why the change was made
- [X] Methods or procedures are documented
- [X] Regression or unit tests are included, or existing tests cover the modified code
- [X] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs [hunk 1]
```diff
@@ -98,18 +98,45 @@ impl<'tcx> GotocCtx<'tcx> {
...
+                    assert_eq!(start, 0);
+                    // Create a static variable that holds its value
+                    let mem_var =
+                        self.codegen_allocation_auto_imm_name(data, |tcx| tcx.next_global_name());
+
+                    // Extract identifier for static variable.
+                    // codegen_allocation_auto_imm_name returns the *address* of
+                    // the variable, so need to pattern match to extract it.
+                    let ident = match mem_var.value() {
+                        ExprValue::AddressOf(address) => match address.value() {
```
Comment (celinval) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:119]: nit: You could merge these matches into one.

File: kani-compiler/src/codegen_cprover_gotoc/utils/utils.rs [hunk 2]
```diff
@@ -61,6 +42,30 @@ impl<'tcx> GotocCtx<'tcx> {
...
+    /// codegen_slice_value), this will return the string constant. Otherwise,
+    /// return `None`.
+    pub fn extract_const_message(&self, arg: &Expr) -> Option<String> {
+        match arg.value() {
+            ExprValue::Struct { values } => match &values[0].value() {
+                ExprValue::Typecast(expr) => match expr.value() {
+                    ExprValue::AddressOf(address) => match address.value() {
+                        ExprValue::Symbol { identifier } => {
+                            // lookup the string literal in the goto context
+                            let name = self.str_literals.get(identifier).unwrap();
```
Comment (celinval) [inline kani-compiler/src/codegen_cprover_gotoc/utils/utils.rs:57]: not for this PR, but I was wondering if we could map directly Expr -> String Literal.

**Review by celinval — APPROVED** [review]
Thanks for doing this

File: tests/kani/Intrinsics/ArithOffset/offset_u8_ok.rs [hunk 3]
```diff
@@ -18,7 +18,7 @@ fn test_arith_offset() {
 
         // This is okay because it's one byte past the object,
```
Comment (celinval) [inline tests/kani/Intrinsics/ArithOffset/offset_u8_ok.rs:19]: We should probably update the comment in these tests and use a `_x` to show that this can't really be de-referenced.

File: kani-compiler/src/codegen_cprover_gotoc/utils/utils.rs (hunk 2 above)
Comment (zhassan-aws) [reply kani-compiler/src/codegen_cprover_gotoc/utils/utils.rs:57]: Yes, that would be better. I couldn't do that because `Expr` is not "hash"able. I'll add a comment though.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs (hunk 1 above)
Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:119]: I didn't realize there was a Box in there. It makes things a bit uglier, so what you have might just be cleaner. But here is how you could merge this:

```rust
let ident = match mem_var.value() {
                        ExprValue::AddressOf(Expr {
                            value: box ExprValue::Symbol { identifier },
                            ..
                        }) => identifier,
                        _ => unreachable!("Expecting a symbol for a string literal allocation"),
                    };
```

File: tests/kani/Intrinsics/ArithOffset/offset_u8_ok.rs (hunk 3 above)
Comment (zhassan-aws) [reply tests/kani/Intrinsics/ArithOffset/offset_u8_ok.rs:19]: Done
