### PR TITLE
Do not apply Ubuntu 18.04 workaround if user has installed newer versions of Python

### LINKED ISSUE #1721: cargo-kani setup fails; Ubuntu 18 with newer python
While following the README.md steps to install kani, I got the following error:

```
$ cargo-kani setup
[0/6] Running Kani first-time setup...
[1/6] Ensuring the existence of: /home/ANT.AMAZON.COM/karahmed/.kani/kani-0.10.0
[2/6] Downloading Kani release bundle: kani-0.10.0-x86_64-unknown-linux-gnu.tar.gz
[3/6] Installing rust toolchain version: nightly-2022-08-30-x86_64-unknown-linux-gnu
info: syncing channel updates for 'nightly-2022-08-30-x86_64-unknown-linux-gnu'

  nightly-2022-08-30-x86_64-unknown-linux-gnu unchanged - rustc 1.65.0-nightly (bc4b39c27 2022-08-29)

info: checking for self-updates
[4/6] Installing Kani python dependencies...
Applying a workaround for 18.04...

Usage:   
  /usr/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...
  /usr/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...
  /usr/bin/python3 -m pip install [options] [-e] <vcs project url> ...
  /usr/bin/python3 -m pip install [options] [-e] <local project path> ...
  /usr/bin/python3 -m pip install [options] <archive url/path> ...

no such option: --system
Error: Failed command: python3 -m pip install --system --prefix /home/ANT.AMAZON.COM/karahmed/.kani/kani-0.10.0/pyroot cbmc-viewer==3.6
```

My system is running:
```
$ pip --version
pip 21.3.1 from $HOME/.local/lib/python3.6/site-packages/pip (python 3.6)
karahmed@ubbcd806e443653:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

### PR DESCRIPTION
**Pull request by tedinski**
### Description of changes: 

Newer versions of Python do not have the option we use to workaround the broken `pip` in default Ubuntu 18.04, so the install fails for them.

However the broken version is only due to a debian/ubuntu-specific patch they applied. So if the user has done anything to get a different version of Python installed, we don't need this workaround.

So test for version 9 of pip. Any different version almost certainly means the user has installed their own python, instead of the system-supplied one for 18.04.

### Resolved issues:

Resolves #1721 

### Call-outs:

* I have not added a system integration test for this scenario. I think there's limits to the number of user system configurations we can test in CI. I believe the unit test for the version checker should be enough, and we're strictly narrower in scope for when we apply this hacky workaround, so I think this is good.

### Testing:

* How is this change tested? unit tests + ci for existing workaround

* Is this a refactor change? no

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: src/os_hacks.rs [hunk 1]
```diff
@@ -14,6 +14,41 @@ use os_info::Info;
 
 use crate::cmd::AutoRun;
 
+pub fn should_apply_ubuntu_18_04_python_hack(os: &os_info::Info) -> Result<bool> {
+    if os.os_type() == os_info::Type::Ubuntu {
```
Comment (zhassan-aws) [inline src/os_hacks.rs:18]: Shouldn't this be `!=` ?

**Review by zhassan-aws — APPROVED** [review]
