### PR TITLE
Handle enums with zero or one variants

### LINKED ISSUE #4170: Deriving BoundedArbitrary fails for enum with one variant
I tried this code:

```rust
#[derive(kani::BoundedArbitrary)]
enum Foo {
    A(#[bounded] String),
    //B(#[bounded] String),
}

#[kani::proof]
fn check_enum() {
    let _foo = kani::bounded_any::<Foo, 4>();
}
```

using the following command line invocation:

```
kani bounded_enum.rs
```

with Kani version: 37fb6345740

I expected to see this happen: Verification successful

Instead, this happened:
```bash
 $ kani bounded_enum.rs 
Kani Rust Verifier 0.63.0 (standalone)
error[E0283]: type annotations needed
  --> bounded_enum.rs:1:10
   |
1  | #[derive(kani::BoundedArbitrary)]
   |          ^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
   |
   = note: cannot satisfy `_: kani::Arbitrary`
   = help: the following types implement trait `kani::Arbitrary`:
             ()
             (A, B)
             (A, B, C)
             (A, B, C, D)
             (A, B, C, D, E)
             (A, B, C, D, E, F)
             (A, B, C, D, E, F, G)
             (A, B, C, D, E, F, G, H)
           and 50 others
note: required by a bound in `kani::any`
  --> /home/ubuntu/git/kani/library/kani/src/lib.rs:55:1
   |
55 | kani_core::kani_lib!(kani);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `any`
   = note: this error originates in the derive macro `kani::BoundedArbitrary` which comes from the expansion of the macro `kani_core::kani_lib` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0283`.
error: /home/ubuntu/git/kani/target/kani/bin/kani-compiler exited with status exit status: 101
```

If I uncomment the second variant, verification is successful.

### PR DESCRIPTION
**Pull request by zhassan-aws**
Handle enums with zero or one variants when deriving `BoundedArbitrary`.

Resolves #4170

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: library/kani_macros/src/derive_bounded.rs [hunk 1]
```diff
@@ -92,19 +92,40 @@ fn generate_type_constructor(type_name: TokenStream, fields: &syn::Fields) -> To
...
+    } else if data_enum.variants.len() == 1 {
+        let variant = data_enum.variants.first().unwrap();
         let variant_name = &variant.ident;
-        generate_type_constructor(quote!(#ident::#variant_name), &variant.fields)
-    });
-    let n_variants = data_enum.variants.len();
-    let cases = variant_constructors.enumerate().map(|(idx, var_constr)| {
-        if idx < n_variants - 1 { quote!(#idx => #var_constr) } else { quote!(_ => #var_constr) }
-    });
+        let variant_constructor =
```
Comment (remi-delmas-3000) [inline library/kani_macros/src/derive_bounded.rs:105]: would it be possible to treat the case `data_enum.variants.len() == 1` just like the case with n variants ?

Comment (zhassan-aws) [reply library/kani_macros/src/derive_bounded.rs:105]: Yes, it is possible, but since we don't need a match statement at all for the single-variant case, it makes sense to generate optimized code, i.e. instead of
```rust
match kani::any::<usize>() {
    _ => Variant,
}
```
we just generate:
```rust
Variant
```
The compiler will likely perform this reduction automatically though, but I'm not sure.

**Review by sgpthomas — APPROVED** [review]
LGTM!
