### PR TITLE
Fix handling of `dyn T`

### LINKED ISSUE #82: Dynamic and Ref(Dynamic) codegen to same fat pointer
The method `codegen_ty` produces the same fat pointer for both the Dynamic and Ref(Dyanmic) mir type kinds.  I'm not sure what Dynamic should codegen since a trait object can only be accessed via a pointer (a fat pointer).  But probably no one should be trying to codegen Dynamic itself, and we should panic if anyone tries to do so.

### LINKED ISSUE #990: Type check on "Plus" operation fails on smallvec crate
Steps to reproduce:
1. `cargo new foo`
2. Add `smallvec` to the `Cargo.toml` dependencies:
```toml
[dependencies]
smallvec = "1.8.0"
```
3. Run `cargo kani`

with Kani version: `7015212b374`

I expected to see this happen: Verification successful or "Error: No proof harnesses (functions with #[kani::proof]) were found to verify."

Instead, this happened:
```
   Compiling smallvec v1.8.0
WARN kani_compiler::codegen_cprover_gotoc::codegen::place Unexpected type mismatch in projection:
Expr { value: Member { lhs: Expr { value: Symbol { identifier: "_RNvMs2_NtCsbwYNDzcVKSW_4core3fmtNtB5_9Arguments6new_v1CsbUyYRrL8sBv_8smallvec::1::var_6" }, typ: StructTag("tag-_7469936087067620587"), location: None }, field: "data" }, typ: Pointer { typ: StructTag("tag-str") }, location: None }
Expr type
Pointer { typ: StructTag("tag-str") }
Type from MIR
FlexibleArray { typ: StructTag("tag-str") }
WARN kani_compiler::codegen_cprover_gotoc::codegen::place Unexpected type mismatch in projection:
Expr { value: Member { lhs: Expr { value: Symbol { identifier: "_RNvMs2_NtCsbwYNDzcVKSW_4core3fmtNtB5_9Arguments6new_v1CsbUyYRrL8sBv_8smallvec::1::var_8" }, typ: StructTag("tag-_16055536712214251876"), location: None }, field: "data" }, typ: Pointer { typ: StructTag("tag-_2902613861325605750") }, location: None }
Expr type
Pointer { typ: StructTag("tag-_2902613861325605750") }
Type from MIR
FlexibleArray { typ: StructTag("tag-_2902613861325605750") }
WARN kani_compiler::codegen_cprover_gotoc::codegen::place Unexpected type mismatch in projection:
Expr { value: Member { lhs: Expr { value: Symbol { identifier: "_RNvMs2_NtCsbwYNDzcVKSW_4core3fmtNtB5_9Arguments6new_v1CsbUyYRrL8sBv_8smallvec::1::var_11" }, typ: StructTag("tag-_7469936087067620587"), location: None }, field: "data" }, typ: Pointer { typ: StructTag("tag-str") }, location: None }
Expr type
Pointer { typ: StructTag("tag-str") }
Type from MIR
FlexibleArray { typ: StructTag("tag-str") }
WARN kani_compiler::codegen_cprover_gotoc::codegen::place Unexpected type mismatch in projection:
Expr { value: Member { lhs: Expr { value: Symbol { identifier: "_RNvMs2_NtCsbwYNDzcVKSW_4core3fmtNtB5_9Arguments6new_v1CsbUyYRrL8sBv_8smallvec::1::var_14" }, typ: StructTag("tag-_16055536712214251876"), location: None }, field: "data" }, typ: Pointer { typ: StructTag("tag-_2902613861325605750") }, location: None }
Expr type
Pointer { typ: StructTag("tag-_2902613861325605750") }
Type from MIR
FlexibleArray { typ: StructTag("tag-_2902613861325605750") }
thread 'rustc' panicked at 'BinaryOperation Expression does not typecheck Plus Expr { value: Dereference(Expr { value: Typecast(Expr { value: BinOp { op: Plus, lhs: Expr { value: Typecast(Expr { value: AddressOf(Expr { value: Dereference(Expr { value: Member { lhs: Expr { value: Symbol { identifier: "_RNvXsR_CsbUyYRrL8sBv_8smallvecNtB5_18CollectionAllocErrNtNtCsbwYNDzcVKSW_4core3fmt5Debug3fmt::1::var_3" }, typ: StructTag("tag-_16932096406897758278"), location: None }, field: "0" }, typ: Pointer { typ: StructTag("tag-_5532084034040080629") }, location: None }), typ: StructTag("tag-_5532084034040080629"), location: None }), typ: Pointer { typ: StructTag("tag-_5532084034040080629") }, location: None }), typ: Pointer { typ: Unsignedbv { width: 8 } }, location: None }, rhs: Expr { value: IntConstant(8), typ: CInteger(SizeT), location: None } }, typ: Pointer { typ: Unsignedbv { width: 8 } }, location: None }), typ: Pointer { typ: Unsignedbv { width: 64 } }, location: None }), typ: Unsignedbv { width: 64 }, location: None } Expr { value: IntConstant(340282366920938463463374607431768211455), typ: Unsignedbv { width: 128 }, location: None }', cprover_bindings/src/goto_program/expr.rs:919:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Kani unexpectedly panicked during compilation.
If you are seeing this message, please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md

[Kani] current codegen item: codegen_function: <CollectionAllocErr as core::fmt::Debug>::fmt
_RNvXsR_CsbUyYRrL8sBv_8smallvecNtB5_18CollectionAllocErrNtNtCsbwYNDzcVKSW_4core3fmt5Debug3fmt
[Kani] current codegen location: Loc { file: "/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.8.0/src/lib.rs", function: None, line: 277, col: Some(10) }
error: could not compile `smallvec`
Error: cargo exited with status exit status: 101
```

### PR DESCRIPTION
**Pull request by celinval**
### Description of changes: 

We were incorrectly handling `dyn T` as well as unsized structures with `dyn T`. This change fixes that.

### Resolved issues:

Resolves #82
Resolves #990
Mitigates #1072

### Call-outs:

1. This fixes many of the warnings from #277 but not all.
2. This fixes an issue with Rc<dyn T> and many other issues with Struct<dyn T>. I didn't find any issue related to them.
3. ~~There is a hack that people must be aware. The initial goal was to encode `dyn T` as a `typedef void` so the fat pointer would be in practice `void*`. However, this doesn't work well when the `dyn T`. The reference to this field is usually of the form `&*struct.unsized_field` which generates something like `&void` which is invalid. I am using `bool` for now to encode `dyn T`.~~
4. The `drop` logic still needs further adjustment (see #1072). I added a mitigation to capture the behavior that we don't support yet.

### Testing:

* How is this change tested?

* Is this a refactor change?

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs [hunk 1]
```diff
@@ -319,19 +320,67 @@ impl<'tcx> GotocCtx<'tcx> {
...
+    pub fn codegen_trait_data(&mut self, t: ty::Ty<'tcx>) -> Type {
+        let name = self.normalized_trait_name(t);
+        let inner_name = name.clone() + "Inner";
+        debug!(typ=?t, kind=?t.kind(), %name, %inner_name,
+                "codegen_trait_data_type");
+        self.ensure(inner_name.clone(), |_ctx, _| {
+            Symbol::typedef(
+                &inner_name,
+                &inner_name,
+                Type::bool().to_typedef(inner_name.clone()),
```
Comment (celinval) [inline src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:349]: Try to use Unit type here instead or use byte.

Comment (celinval) [inline src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:349]: Try to use Unit type here instead or use byte.

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs [hunk 2]
```diff
@@ -1304,17 +1394,21 @@ fn normalize_type(ty: Ty) -> Ty {
...
     }
     /// A pointer to the mir type should be a slice fat pointer.
+    /// We use a slice fat pointer if the metadata is the slice length (type usize).
     pub fn use_slice_fat_pointer(&self, mir_type: Ty<'tcx>) -> bool {
         let (metadata, _check_is_sized) = mir_type.ptr_metadata_ty(self.tcx, normalize_type);
         return metadata == self.tcx.types.usize;
     }
     /// A pointer to the mir type should be a vtable fat pointer.
+    /// We use a vtable fat pointer if this is a fat pointer to anything that is not a slice ptr.
+    /// I.e.: The metadata is not length (type usize).
```
Comment (danielsn) [inline src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:1407]: Is it possible to check that it is a vtable, rather than it not being the other two options?

File: src/kani-compiler/src/codegen_cprover_gotoc/context/vtable_ctx.rs [hunk 3]
```diff
@@ -117,9 +118,10 @@ impl<'tcx> GotocCtx<'tcx> {
             format!("restricted_call_label_{}", self.vtable_ctx.get_call_site_global_idx()).into();
 
         // We only have the Gotoc type, we need to normalize to match the MIR type.
-        assert!(trait_ty.is_struct_tag());
-        let mir_name =
-            self.normalized_trait_name(*self.type_map.get(&trait_ty.tag().unwrap()).unwrap());
+        // Retrieve the MIR for `&dyn T` and normalize the name.
+        assert!(trait_ref.is_struct_tag());
+        let mir_type = self.type_map.get(&trait_ref.tag().unwrap()).unwrap();
+        let mir_name = self.normalized_trait_name(pointee_type(*mir_type).unwrap());
```
Comment (danielsn) [inline src/kani-compiler/src/codegen_cprover_gotoc/context/vtable_ctx.rs:124]: Also, I know we called them this already, but `mir_type` and `mir_name` aren't the most descriptive variable names

File: tests/cargo-kani/small-vec/src/lib.rs [hunk 4]
```diff
@@ -0,0 +1,14 @@
+// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
+// SPDX-License-Identifier: Apache-2.0 OR MIT
+
+use kani::Invariant;
+use smallvec::{smallvec, SmallVec};
+
+#[kani::proof]
```
[the remark this answers is not in the document]
Comment (celinval) [reply tests/cargo-kani/small-vec/src/lib.rs:7]: Not much. There was a compilation failure before this fix.

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs [hunk 5]
```diff
@@ -1269,6 +1340,25 @@ impl<'tcx> GotocCtx<'tcx> {
...
+        let mut typ = struct_type;
+        while let ty::Adt(adt_def, adt_substs) = typ.kind() {
+            assert_eq!(
+                adt_def.variants().len(),
+                1,
+                "Expected a single-variant ADT. Found {:?}",
+                typ
+            );
+            let fields = &adt_def.variants().get(VariantIdx::from_u32(0)).unwrap().fields;
+            let last_field = fields.last().expect("Trait should be the last element.");
```
[the remark this answers is not in the document]
Comment (celinval) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:1353]: We'll print warnings for all u supported constructs in every crate we are compiling.

If you want I can try to aggregate the data into one big warning at the end. But it will be a follow up PR

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs (hunk 2 above)
Comment (celinval) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:1407]: I can try to add an assert. I just added a comment while figuring out what it was doing. For this PR, do you prefer if I remove the comments?

File: src/kani-compiler/src/codegen_cprover_gotoc/context/vtable_ctx.rs (hunk 3 above)
Comment (celinval) [reply src/kani-compiler/src/codegen_cprover_gotoc/context/vtable_ctx.rs:124]: I'm all in to improve our variable names! Let me change that.

[the remark this answers is not in the document]
Comment (celinval) [reply src/kani-compiler/src/codegen_cprover_gotoc/context/vtable_ctx.rs]: yes

File: tests/kani/DynTrait/rc_dyn.rs [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+#[kani::proof]
+fn check_rc_dyn() {
+    let table = table(kani::any());
+    let furniture = table.clone();
+    unsafe {
+        assert_eq!(COUNTER, 1);
+    }
+    assert_eq!(table.cost(), furniture.cost());
+
+    /* TODO: Finish this.
```
[the remark this answers is not in the document]
Comment (celinval) [reply tests/kani/DynTrait/rc_dyn.rs:59]: My bad. I forgot to finish it. I'll do that now. :)

File: src/kani-compiler/src/codegen_cprover_gotoc/utils/utils.rs [hunk 7]
```diff
@@ -56,8 +56,8 @@ impl<'tcx> GotocCtx<'tcx> {
         loc: Location,
         url: &str,
     ) -> Expr {
-        // We should possibly upgrade this to a warning in the future, but for now emit at least something
-        debug!("codegen_unimplemented: {} at {}", operation_name, loc.short_string());
+        // TODO: This should print a more user friendly warning format.
+        warn!("codegen_unimplemented: {} at {}", operation_name, loc.short_string());
```
[the remark this answers is not in the document]
Comment (celinval) [reply src/kani-compiler/src/codegen_cprover_gotoc/utils/utils.rs]: We'll print warnings for all u supported constructs in every crate we are compiling.

If you want I can try to aggregate the data into one big warning at the end. But it will be a follow up PR

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (celinval) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs]: Comment in the wrong place. :)

[the remark this answers is not in the document]
Comment (celinval) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs]: This function assumes that this is trait or struct with a trait element. I will add a check to the beginning of the function.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs [hunk 8]
```diff
@@ -850,10 +915,11 @@ impl<'tcx> GotocCtx<'tcx> {
             .iter()
             .filter_map(|t| {
                 if is_first {
-                    //TODO assert that this is a dynamic object
+                    // This should either be a &dyn T or a dyn T.
```
Comment (danielsn) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:918]: assert that?

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs (hunk 2 above)
Comment (danielsn) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs]: I think the comments are useful

**Review by danielsn — APPROVED** [review]
