### PR TITLE
NOP concrete playback to type check during verification mode.

### LINKED ISSUE #2475: Kani cannot verify bolero harness after concrete test has been added
I tried this code:

```rust

#[cfg(test)]
mod bolero_harness {
    #[test]
    #[cfg_attr(kani, kani::proof)]
    fn dummy_harness() {
        bolero::check!()
            .with_type()
            .cloned()
            .for_each(|(a, b): (u8, u8)| assert!(a < b || a > b));
    }
}
```

using the following command line sequence:

```
cargo kani --tests -Z concrete-playback --concrete-playback=inplace
cargo kani --tests
```

with Kani version:

I expected to see this happen: Both commands should succeed

Instead, this happened: The second command failed due to a compilation error
```
error[E0425]: cannot find function `concrete_playback_run` in crate `kani`
  --> src/lib.rs:
   |
   |         kani::concrete_playback_run(concrete_vals, fuzz_add);
   |               ^^^^^^^^^^^^^^^^^^^^^ not found in `kani`

```

The problem is that the harness uses a function that is only included when we execute concrete playback. We should still implement that function in verification mode.

### PR DESCRIPTION
**Pull request by YoshikiTakashima**
### Description of changes: 

This PR adds a NOP concrete playback function so that code inserted by the concrete playback feature that uses `concrete_playback` function still type checks during verification. Previously, this function was not available during verification, causing type fails during verification after playback code was injected.

### Resolved issues:

Resolves #2475 

### Call-outs:

@YoshikiTakashima is not sure where the tests should go given that we want to test behavior when the kani is not in playback mode.

### Testing:

* How is this change tested? `tests/cargo-kani/simple-lib`

* Is this a refactor change? No

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: library/kani/src/lib.rs [hunk 1]
```diff
@@ -21,6 +21,10 @@ pub mod vec;
 pub use arbitrary::Arbitrary;
 #[cfg(feature = "concrete_playback")]
 pub use concrete_playback::concrete_playback_run;
+#[cfg(not(feature = "concrete_playback"))]
+/// NOP `concrete_playback` for type checking during verification mode.
+pub fn concrete_playback_run<F: Fn()>(_: Vec<Vec<u8>>, _: F) {}
```
Comment (celinval) [inline library/kani/src/lib.rs:26]: Can you please add an `unreachable!("Concrete playback does not work during verification")` or something like that, just in case users ever reach this code.

**Review by celinval — APPROVED** [review]
Thanks @YoshikiTakashima. Do you mind adding a separate test instead?

File: library/kani/src/lib.rs (hunk 1 above)
Comment (YoshikiTakashima) [reply library/kani/src/lib.rs]: Done [c057854](https://github.com/model-checking/kani/pull/2476/commits/c057854d26cdf961d3ed778cdf9e1582e0318dd8)

**Comment by YoshikiTakashima** [comment]
new tests in 4575586d40bbb7b718ac41e5cd5e55744b247cf4.

**Comment by YoshikiTakashima** [comment]
Something about this PR seems to be degrading performance.

**Comment by celinval** [comment]
> Something about this PR seems to be degrading performance. Might need a deep dive into benchcomp.

No worries, the test that failed is very flaky. You should be safe.

**Comment by YoshikiTakashima** [comment]
Rerunning didn't seem to fix it. The performance degradation might be something a bit more permanent...
