### PR TITLE
Fix codegen of never return functions

### LINKED ISSUE #648: Codegen does not generate calls to functions that return the never type
Example:

```rust
#![feature(never_type)]
pub fn foo() -> ! {
    panic!();
}
```
The associated function hook (`output_of_instance_is_never`) needs to be removed.

### LINKED ISSUE #751: Panic for `assert_inhabited` has no effect because of `Nevers` hook
Related to #648.

Instead of executing the code for `assert_inhabited`, the `Nevers` hook is being applied. This causes the test introduced in #742 to fail with an unexpected property. The `Nevers` hook has to be removed at some point, this issue is for keeping track of that and going back to ensure the test is working as expected.

### PR DESCRIPTION
**Pull request by celinval**
### Description of changes: 

I have removed the Nevers hook and I have also introduced two stubs in our std library to provide more user friendly errors. Functions overriden: std::process::{abort, exit}

### Resolved issues:

Resolves #648 and resolves #751.

### Call-outs:

I did add a tiny fix to a wrong PropertyClass that I noticed while working on this fix.

### Testing:

* How is this change tested? New test

* Is this a refactor change? No

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: library/std/src/lib.rs [hunk 1]
```diff
@@ -12,6 +12,9 @@
 // re-export all std symbols
 pub use std::*;
 
+// Override process calls with stubs.
+pub mod process;
```
Comment (tedinski) [inline library/std/src/lib.rs:16]: I vaguely recall us having issues with overriding things here that weren't macros. Was that resolved somehow?

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs [hunk 2]
```diff
@@ -57,9 +57,10 @@ impl<'tcx> GotocCtx<'tcx> {
                 "reached intrinsic::abort",
                 span,
             ),
+            // Transmuting to an uninhabited type is UB.
             "transmute" => self.codegen_fatal_error(
-                PropertyClass::UnsupportedConstruct,
-                "transmuting to uninhabited type",
+                PropertyClass::DefaultAssertion,
+                "transmuting to uninhabited type has undefined behavior",
```
Comment (tedinski) [inline src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs:63]: Ah, I made the wrong call helping Jai. Good catch. :)

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs [hunk 3]
```diff
@@ -368,22 +382,16 @@ impl<'tcx> GotocCtx<'tcx> {
...
-                    return self.codegen_assert_false(
-                        PropertyClass::SanityCheck,
-                        &format!("reach some nonterminating function: {:?}", func),
-                        loc.clone(),
-                    );
-                }
-
-                let (p, target) = destination.unwrap();
+                let (place, target) =
+                    if let Some((p, t)) = destination { (Some(p), Some(t)) } else { (None, None) };
```
Comment (tedinski) [inline src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs:386]: Nit: This boggled me. Can we convert to match instead of if let?

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs [hunk 4]
```diff
@@ -481,7 +493,11 @@ impl<'tcx> GotocCtx<'tcx> {
 
         // Virtual function call and corresponding nonnull assertion.
         let call = fn_ptr.dereference().call(fargs.to_vec());
-        let call_stmt = self.codegen_expr_to_place(place, call).with_location(loc.clone());
+        let call_stmt = if let Some(place) = place {
+            self.codegen_expr_to_place(place, call).with_location(loc.clone())
+        } else {
+            call.as_stmt(loc.clone())
+        };
```
Comment (tedinski) [inline src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs:500]: Nit: here too

File: tests/expected/abort/main.rs [hunk 5]
```diff
@@ -14,7 +14,7 @@ fn main() {
         }
         if i == 2 {
             // This should never happen.
-            process::abort();
+            process::exit(1);
```
Comment (tedinski) [inline tests/expected/abort/main.rs:17]: The comment says test `abort` but now we're calling `exit`. Is there a reason for choosing either?

**Review by tedinski — APPROVED** [review]
I think just a style thing: I prefer we use `match` instead of an `if let` as an expression.

File: library/std/src/lib.rs (hunk 1 above)
Comment (zhassan-aws) [reply library/std/src/lib.rs:16]: The one I recall failing to override  was `std::mem::swap`, which turned out was because we have a hook for it: https://github.com/model-checking/kani/blob/e20874a616c0e2726726d4e23143ce77077ea7e2/src/kani-compiler/src/codegen_cprover_gotoc/overrides/hooks.rs#L390

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs (hunk 3 above)
Comment (celinval) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs:386]: I can. But why did it bother you?

File: tests/expected/abort/main.rs (hunk 5 above)
Comment (celinval) [reply tests/expected/abort/main.rs:17]: I just wanted to increase test coverage

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs (hunk 3 above)
Comment (tedinski) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs:386]: I think my brain treats `if let` as statement-like and `match` as expression-like. This is despite being happy with `if` as expression-like.

It's possible it's just me needing to get used to it. If you disagree, no problem.

File: tests/expected/abort/expected [hunk 6]
```diff
@@ -1,4 +1,16 @@
...
-a panicking function std::process::abort is invoked
+Status: UNREACHABLE\
+Description: ""This is unreachable""\
+in function main
+
+Status: FAILURE\
+Description: "Function abort() was invoked"\
+in function std::process::abort
+
+Status: SUCCESS\
```
Comment (zhassan-aws) [inline tests/expected/abort/expected:9]: I was expecting this to be UNREACHABLE, but it isn't because `std::exit` calls `panic` which we currently don't override. If we want it to be reported as UNREACHABLE (I think it should, but I'm not sure), then we can change the `panic(msg)` to `assert!(false, msg)`.

File: src/kani-compiler/src/codegen_cprover_gotoc/overrides/hooks.rs [hunk 7]
```diff
@@ -277,30 +252,6 @@ impl<'tcx> GotocHook<'tcx> for Panic {
     }
 }
 
-struct Nevers;
-
-impl<'tcx> GotocHook<'tcx> for Nevers {
```
Comment (zhassan-aws) [inline src/kani-compiler/src/codegen_cprover_gotoc/overrides/hooks.rs:282]: Nice to get rid of this!

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs (hunk 3 above)
Comment (zhassan-aws) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs:386]: It took me some time to get used to as well :)

File: library/std/src/process.rs [hunk 8]
```diff
@@ -0,0 +1,17 @@
+// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
+// SPDX-License-Identifier: Apache-2.0 OR MIT
+
+//! This module introduces stubs for process methods.
```
Comment (zhassan-aws) [inline library/std/src/process.rs:4]: Nice!

File: tests/expected/abort/expected (hunk 6 above)
Comment (celinval) [reply tests/expected/abort/expected:9]: We can't. It won't compile because of the never return. I think we should instrument panic inside the compiler to have a reach check.

Comment (zhassan-aws) [reply tests/expected/abort/expected:9]: I see.

**Review by zhassan-aws — APPROVED** [review]

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs (hunk 3 above)
Comment (celinval) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs:386]: If you don't mind, I prefer to move on with this PR since there's nothing else to change.

I don't have any strong opinion about this. I tend to favor `if let` when I'm looking for one specific match. It's less verbose and clear to me that it's an all or nothing situation. We can discuss this later and if one is preferred over the other, maybe we can have a little convention page.

**Review by adpaco-aws — APPROVED** [review]
Thanks for getting rid of the `Nevers` hook!

Can you please check if this fixes #751 too?

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs (hunk 3 above)
Comment (tedinski) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs:386]: Yeah, that's fine, I prefer velocity over this nit.

Comment (celinval) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs:386]: Thanks

**Comment by celinval** [comment]
> Thanks for getting rid of the `Nevers` hook!
> 
> Can you please check if this fixes #751 too?

Yes it does.
