### PR TITLE
Fix generator layout and sizes

### LINKED ISSUE #1359: Duplicate lang item in crate `std` errors while building the std library
This captures one of the issues raised by @zhassan-aws (https://github.com/model-checking/kani/issues/1213#issuecomment-1143033711)

Try the following steps:

1. `cargo new --lib lstd`
2. Put the following in `src/lib.rs`:
```rustc
#[kani::proof]
fn check_format() {
    assert!("2021".parse::<u32>().unwrap() == 2021);
}
```
3. Build using:
```
KANIFLAGS="--goto-c --ignore-global-asm --log-level=error --assertion-reach-checks -C symbol-mangling-version=v0" RUSTC="/home/ubuntu/git/kani/target/debug/kani-compiler" RUSTFLAGS="--kani-flags" cargo +nightly-2022-05-17 build --target x86_64-unknown-linux-gnu -Z build-std --lib --target-dir target
```

The following errors are emitted:
```
error: duplicate lang item in crate `std` (which `kani` depends on): `panic_impl`.
  |
  = note: the lang item is first defined in crate `std` (which `lstd` depends on)
  = note: first definition in `std` loaded from /home/ubuntu/examples/lstd/target/x86_64-unknown-linux-gnu/debug/deps/libstd-9f9e8af9b2102e2a.rmeta
  = note: second definition in `std` loaded from /home/ubuntu/.rustup/toolchains/nightly-2022-05-17-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-977ece543e1e3d2f.rlib

error: duplicate lang item in crate `std` (which `kani` depends on): `begin_panic`.
  |
  = note: the lang item is first defined in crate `std` (which `lstd` depends on)
  = note: first definition in `std` loaded from /home/ubuntu/examples/lstd/target/x86_64-unknown-linux-gnu/debug/deps/libstd-9f9e8af9b2102e2a.rmeta
  = note: second definition in `std` loaded from /home/ubuntu/.rustup/toolchains/nightly-2022-05-17-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-977ece543e1e3d2f.rlib

error: duplicate lang item in crate `std` (which `kani` depends on): `oom`.
  |
  = note: the lang item is first defined in crate `std` (which `lstd` depends on)
  = note: first definition in `std` loaded from /home/ubuntu/examples/lstd/target/x86_64-unknown-linux-gnu/debug/deps/libstd-9f9e8af9b2102e2a.rmeta
  = note: second definition in `std` loaded from /home/ubuntu/.rustup/toolchains/nightly-2022-05-17-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-977ece543e1e3d2f.rlib

error: duplicate lang item in crate `std` (which `kani` depends on): `start`.
  |
  = note: the lang item is first defined in crate `std` (which `lstd` depends on)
  = note: first definition in `std` loaded from /home/ubuntu/examples/lstd/target/x86_64-unknown-linux-gnu/debug/deps/libstd-9f9e8af9b2102e2a.rmeta
  = note: second definition in `std` loaded from /home/ubuntu/.rustup/toolchains/nightly-2022-05-17-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-977ece543e1e3d2f.rlib

error: duplicate lang item in crate `std` (which `kani` depends on): `termination`.
  |
  = note: the lang item is first defined in crate `std` (which `lstd` depends on)
  = note: first definition in `std` loaded from /home/ubuntu/examples/lstd/target/x86_64-unknown-linux-gnu/debug/deps/libstd-9f9e8af9b2102e2a.rmeta
  = note: second definition in `std` loaded from /home/ubuntu/.rustup/toolchains/nightly-2022-05-17-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-977ece543e1e3d2f.rlib

error: duplicate lang item in crate `core` (which `std` depends on): `sized`.
  |
  = note: the lang item is first defined in crate `core` (which `std` depends on)
  = note: first definition in `core` loaded from /home/ubuntu/examples/lstd/target/x86_64-unknown-linux-gnu/debug/deps/libcore-6d9d14315cbfc8dc.rmeta
  = note: second definition in `core` loaded from /home/ubuntu/.rustup/toolchains/nightly-2022-05-17-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-0e3656b1fda5fd7b.rlib

error[E0034]: multiple applicable items in scope
 --> src/lib.rs:3:20
  |
3 |     assert!("2021".parse::<u32>().unwrap() == 2021);
  |                    ^^^^^ multiple `parse` found
  |
  = note: candidate #1 is defined in an impl for the type `str`
  = note: candidate #2 is defined in an impl for the type `str`

For more information about this error, try `rustc --explain E0034`.
Error: "Failed to compile crate."
error: could not compile `lstd` due to 113 previous errors
```

_Edited from @zhassan-aws original post in https://github.com/model-checking/kani/issues/1213#issuecomment-1143033711_

### LINKED ISSUE #1395: Difference in size of generators between rustc (with panic=unwind!) and Kani
*Update:* the discrepancy is in fact due to Kani assuming `panic=abort`, but the Rust compiler assuming `panic=unwind` by default.

In https://github.com/model-checking/kani/pull/1378#discussion_r924977758, it was observed that Kani sometimes reports a different size of a generator than the LLVM backend of rustc. Interestingly, the WASM backend seems to disagree with LLVM as well (see https://github.com/rust-lang/rust/issues/62807).

The example code is the following:

```rust
#![feature(generators, generator_trait)]

use std::ops::Generator;

const FOO_SIZE: usize = 1024;
struct Foo([u8; FOO_SIZE]);

impl Drop for Foo {
    fn drop(&mut self) {}
}

fn noop() {}

fn move_before_yield_with_noop() -> impl Generator<Yield = (), Return = ()> {
    static || {
        let first = Foo([0; FOO_SIZE]);
        noop();
        let _second = first;
        yield;
        // _second dropped here
    }
}

fn main() {
    // This fails for Kani: it thinks the size is 1025, and so does the WASM backend.
    assert_eq!(1026, std::mem::size_of_val(&move_before_yield_with_noop()));
}
```

### LINKED ISSUE #1593: Assertion failure in `check_vtable_size`
Reproduction steps:

```
$ cargo new exr-test
     Created binary (application) `exr-test` package
$ cd exr-test/
$ cargo add exr
    Updating crates.io index
      Adding exr v1.5.0 to dependencies.
$ cargo kani
[..SNIP..]
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `40`,
 right: `33`', kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs:883:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Kani unexpectedly panicked during compilation.
If you are seeing this message, please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md

[Kani] current codegen item: codegen_function: <meta::header::LayerAttributes as std::fmt::Debug>::fmt
_RNvXs2_NtNtCs6ehrxsMMmGu_3exr4meta6headerNtB5_15LayerAttributesNtNtCs2ybv9YpAGK_4core3fmt5Debug3fmt
[Kani] current codegen location: Loc { file: "/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/exr-1.5.0/src/meta/header.rs", function: None, start_line: 1150, start_col: Some(5), end_line: 1150, end_col: Some(79) }
error: could not compile `exr`
Error: cargo exited with status exit status: 101
```

That "current codegen location" is here:

```
impl std::fmt::Debug for LayerAttributes {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
```

### PR DESCRIPTION
**Pull request by fzaiser**
### Description of changes: 

This PR fixes a bug in how Kani lays out generators. Previously, Kani got some offsets (and as a consequence, the size) wrong sometimes.

In the process, @celinval also discovered that the size of a generator may depend on the panic strategy, which explains the discrepancy of the sizes in #1395. This issue is resolved here as well.

### Resolved issues:

Resolves #1395 
Resolves #1593

### Testing:

* How is this change tested? Added a regression test for #1593, and got the failing tests from #1359 working.

* Is this a refactor change? No

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by danielsn — APPROVED** [review]

File: kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs [hunk 1]
```diff
@@ -361,19 +361,9 @@ impl<'tcx> GotocCtx<'tcx> {
         macro_rules! codegen_size_align {
             ($which: ident) => {{
                 let tp_ty = instance.substs.type_at(0);
-                if tp_ty.is_generator() {
-                    let e = self.codegen_unimplemented_expr(
```
Comment (tedinski) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs:365]: Was this previously missed because sitting inside a macro made it hard to find references? Just curious.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs [hunk 2]
```diff
@@ -1130,7 +1130,7 @@ impl<'tcx> GotocCtx<'tcx> {
                     name: field_name,
                     typ: ctx.codegen_ty(field_ty),
                 });
-                offset += field_size;
```
Comment (tedinski) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:1133]: This is the core of the fix right?

**Review by tedinski — APPROVED** [review]

File: kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs (hunk 2 above)
Comment (fzaiser) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:1133]: Yes, that was the bug.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs (hunk 1 above)
Comment (fzaiser) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs:365]: No, the macro had no effect on this as far as I can tell.

File: tests/kani/Generator/rustc-generator-tests/moved-locals-size.rs [hunk 3]
```diff
@@ -79,12 +79,10 @@ fn overlap_x_and_y() -> impl Generator<Yield = (), Return = ()> {
 
 #[kani::proof]
 fn main() {
-    // FIXME: size of generators does not work reliably (https://github.com/model-checking/kani/issues/1395)
     assert_eq!(1025, std::mem::size_of_val(&move_before_yield()));
-    // The following assertion fails for some reason (tracking issue: https://github.com/model-checking/kani/issues/1395).
-    // But it also fails for WASM (https://github.com/rust-lang/rust/issues/62807),
-    // so it is probably not a big problem:
-    assert_eq!(1026, std::mem::size_of_val(&move_before_yield_with_noop()));
+    // With panic=unwind, the following assertion passes:
```
Comment (celinval) [inline tests/kani/Generator/rustc-generator-tests/moved-locals-size.rs:83]: Please improve this doc. Maybe add as a document of the harness itself.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs [hunk 4]
```diff
@@ -1130,7 +1130,7 @@ impl<'tcx> GotocCtx<'tcx> {
...
+                offset = field_offset + field_size;
```
Comment (celinval) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:1133]: Can you please add a comment here? You really only care about the last field, right?

Comment (fzaiser) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:1133]: What kind of comment do you mean? We also use the offset earlier to figure out how much padding to insert before a field.

File: tests/kani/Generator/rustc-generator-tests/moved-locals-size.rs (hunk 3 above)
Comment (fzaiser) [reply tests/kani/Generator/rustc-generator-tests/moved-locals-size.rs]: Done

File: kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs (hunk 4 above)
Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:1133]: Gotcha. That's fine, thanks

**Review by celinval — APPROVED** [review]
Awesome! Thanks
