### PR TITLE
Fix issue 2589

### LINKED ISSUE #2589: Invalid stub cause different ICE while monomorphizing the code
I tried this code:

```rust
fn original<T>() {}

trait Dummy {
    const TRUE: bool = true;
}

fn stub<T: Dummy>() {
    // Do nothing.
    assert!(T::TRUE)
}

#[kani::proof]
#[kani::stub(original, stub)]
fn check_mismatch() {
    original::<String>();
}
```

using the following command line invocation:

```
kani --enable-unstable --enable-stubbing
```

with Kani version: 0.31.0 (dev)

I expected to see this happen: Kani should print a trait mismatch error

Instead, this happened: Kani compiler crashed with the following error:

```
error: internal compiler error: kani-compiler/src/kani_middle/reachability.rs:443:54: Unexpected polymorphic constant: Unevaluated(UnevaluatedConst { def: DefId(0:16 ~ trait_mismatch[1bfd]::Dummy::TRUE), substs: [std::string::String], promoted: None }, bool)
  --> trait_mismatch.rs:36:5
   |
36 |     assert!(T::TRUE)
   |     ^^^^^^^^^^^^^^^^
   |
   = note: this error: internal compiler error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_errors/src/lib.rs:994:33
```

<details><summary> Stack backtrace </summary>

```
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/library/std/src/panicking.rs:625:12
   1: std::panic::panic_any
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/library/std/src/panic.rs:63:5
   2: rustc_errors::HandlerInner::span_bug
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_errors/src/lib.rs:1588:9
   3: rustc_errors::Handler::span_bug
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_errors/src/lib.rs:994:9
   4: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/util/bug.rs:34:40
   5: rustc_middle::ty::context::tls::with_opt::{{closure}}
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/ty/context/tls.rs:154:36
   6: rustc_middle::ty::context::tls::with_context_opt
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/ty/context/tls.rs:100:18
   7: rustc_middle::ty::context::tls::with_opt
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/ty/context/tls.rs:154:5
   8: rustc_middle::util::bug::opt_span_bug_fmt
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/util/bug.rs:31:5
   9: rustc_middle::util::bug::span_bug_fmt
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/util/bug.rs:22:5
  10: <kani_compiler::kani_middle::reachability::MonoItemsFnCollector as rustc_middle::mir::visit::Visitor>::visit_constant
             at /kani/kani-compiler/src/kani_middle/reachability.rs:443:54
  11: rustc_middle::mir::visit::Visitor::super_operand
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/mir/visit.rs:779:25
  12: rustc_middle::mir::visit::Visitor::visit_operand
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/mir/visit.rs:146:17
  13: rustc_middle::mir::visit::Visitor::super_rvalue
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/mir/visit.rs:701:25
  14: <kani_compiler::kani_middle::reachability::MonoItemsFnCollector as rustc_middle::mir::visit::Visitor>::visit_rvalue
             at /kani/kani-compiler/src/kani_middle/reachability.rs:415:9
  15: rustc_middle::mir::visit::Visitor::super_assign
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/mir/visit.rs:461:17
  16: rustc_middle::mir::visit::Visitor::visit_assign
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/mir/visit.rs:114:17
  17: rustc_middle::mir::visit::Visitor::super_statement
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/mir/visit.rs:378:25
  18: rustc_middle::mir::visit::Visitor::visit_statement
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/mir/visit.rs:105:17
  19: rustc_middle::mir::visit::Visitor::super_basic_block_data
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/mir/visit.rs:307:21
  20: rustc_middle::mir::visit::Visitor::visit_basic_block_data
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/mir/visit.rs:90:17
  21: rustc_middle::mir::visit::Visitor::super_body
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/mir/visit.rs:292:17
  22: rustc_middle::mir::visit::Visitor::visit_body
             at /rustc/fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2/compiler/rustc_middle/src/mir/visit.rs:80:17
  23: kani_compiler::kani_middle::reachability::MonoItemsCollector::visit_fn
             at /kani/kani-compiler/src/kani_middle/reachability.rs:200:9
  24: kani_compiler::kani_middle::reachability::MonoItemsCollector::reachable_items
             at /kani/kani-compiler/src/kani_middle/reachability.rs:178:47
  25: kani_compiler::kani_middle::reachability::MonoItemsCollector::collect
             at /kani/kani-compiler/src/kani_middle/reachability.rs:168:9
  26: kani_compiler::kani_middle::reachability::collect_reachable_items
             at /kani/kani-compiler/src/kani_middle/reachability.rs:49:9
  27: kani_compiler::codegen_cprover_gotoc::compiler_interface::GotocCodegenBackend::codegen_items::{{closure}}
             at /kani/kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs:86:16
  28: kani_compiler::codegen_cprover_gotoc::compiler_interface::with_timer
             at /kani/kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs:738:15
  29: kani_compiler::codegen_cprover_gotoc::compiler_interface::GotocCodegenBackend::codegen_items
             at /kani/kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs:85:21
  30: <kani_compiler::codegen_cprover_gotoc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at /kani/kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs:242:25
  31: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
  32: rustc_interface::passes::start_codegen
  33: <rustc_middle::ty::context::GlobalCtxt>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>
  34: <rustc_interface::queries::Queries>::ongoing_codegen
  35: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Kani unexpectedly panicked during compilation.
Please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md

[Kani] no current codegen item.
[Kani] no current codegen location.
error: aborting due to previous error; 5 warnings emitted
```
</details>

### PR DESCRIPTION
**Pull request by JustusAdam**
### Description of changes: 

This addresses #2589 by providing a better error message that contains both the trait that failed to resolve and the type which does not implement it.

Before:

```
error: internal compiler error: kani-compiler/src/kani_middle/reachability.rs:471:29: Unexpected polymorphic constant: Unevaluated(UnevaluatedConst { def: DefId(0:6 ~ issue_2589[1b49]::Dummy::TRUE), args: [Adt(std::string::String, [])], promoted: None }, bool) Unevaluated(UnevaluatedConst { def: DefId(0:6 ~ issue_2589[1b49]::Dummy::TRUE), args: [T/#0], promoted: None }, bool)

thread 'rustc' panicked at /rustc/65ea825f4021eaf77f1b25139969712d65b435a4/compiler/rustc_errors/src/lib.rs:995:33:
Box<dyn Any>
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Kani unexpectedly panicked during compilation.
Please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md

[Kani] no current codegen item.
[Kani] no current codegen location.
error: aborting due to previous error; 1 warning emitted
```

After:

```
error: Type `std::string::String` does not implement trait `Dummy`. This is likely because `original` is used as a stub but its generic bounds are not being met.

error: aborting due to previous error; 1 warning emitted
```

### Resolved issues:

Resolves #2589 

### Related RFC:

Optional #ISSUE-NUMBER.

### Testing:

* How is this change tested?

* Is this a refactor change?

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: kani-compiler/src/kani_middle/reachability.rs [hunk 1]
```diff
@@ -494,6 +512,12 @@ impl<'a, 'tcx> MirVisitor<'tcx> for MonoItemsFnCollector<'a, 'tcx> {
                                 // implement the same traits as those in the
                                 // original function/method. A trait mismatch shows
                                 // up here, when we try to resolve a trait method
+
+                                // FIXME: This assumes the type resolving the
+                                // trait is the first argument, but that isn't
+                                // necessarily true. It could be any argument or
+                                // even the return type, for instance for a
+                                // trait like `FromIterator`.
```
Comment (feliperodri) [inline kani-compiler/src/kani_middle/reachability.rs:520]: Do we have an GitHub issue related to this? Any reason to not have one here?

File: kani-compiler/src/kani_middle/reachability.rs [hunk 2]
```diff
@@ -555,6 +579,36 @@ impl<'a, 'tcx> MirVisitor<'tcx> for MonoItemsFnCollector<'a, 'tcx> {
     }
 }
 
+/// Try to construct a nice error message when const evaluation fails.
+///
+/// This function handles the `Trt::CNST` case where there is one trait (`Trt`)
+/// which defined a constant `CNST` that we failed to resolve. As such we expect
+/// that the trait can be resolved from the constant and that only one generic
+/// parameter, the instantiation of `Trt` is present.
```
Comment (feliperodri) [inline kani-compiler/src/kani_middle/reachability.rs:587]:
```suggestion
/// parameter, the instantiation of `Trt`, is present.
```

**Review by feliperodri — CHANGES_REQUESTED** [review]

File: kani-compiler/src/kani_middle/reachability.rs (hunk 1 above)
Comment (JustusAdam) [reply kani-compiler/src/kani_middle/reachability.rs:520]: No. This is also not my code. I was just wondering how it could dispatch on the first argument and how that would be correct so I crafted an example that would break it and added the comment so if it comes up whoever fixes it has something to go on.

**Review by feliperodri — APPROVED** [review]
LGTM.
