### PR TITLE
Limit FFI calls by default to explicitly supported ones

### LINKED ISSUE #1781: function call: parameter "pthread_key_create::destructor" type mismatch when hitting `thread::current()`
When a kani is run with `--mir-linker --enable-unstable` and encounters `thread::current()` (or rather, the destructor of a thread object?) it yields the error message from the title. 

I tried this code:
```rust
fn main() {}

#[kani::proof]
fn crash() {
    std::thread::current();
}
```

using the following command line invocation:

```
cargo clean; cargo kani --mir-linker --enable-unstable
```

with Kani version: cargo-kani 0.12.0

I expected to see this happen: As `std::thread` interfaces with the OS API (pthread on linux) I'd have expected kani to complain about it reaching some function for which it does not have access to the source code. If I run kani without `--mir-linker`, this is indeed what happens. 

Instead, this happened: 

<details>

```bash
Checking harness crash...
CBMC 5.67.0 (cbmc-5.67.0)
CBMC version 5.67.0 (cbmc-5.67.0) 64-bit x86_64 linux
Reading GOTO program from file /home/ec2-user/kani-reproducer/target/x86_64-unknown-linux-gnu/debug/deps/cbmc-linked.for-crash.out
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 16 object bits, 48 offset bits (user-specified)
Starting Bounded Model Checking
: function call: parameter "pthread_key_create::destructor" type mismatch:
got struct_tag
  * identifier: tag-_3583338355805481440
expected pointer
  * #source_location: 
    * file: <builtin-library-pthread_key_create>
    * line: 11
    * function: pthread_key_create
    * working_directory: /home/ec2-user/kani-reproducer/src
  * width: 64
  * #failed_symbol: pthread_key_create::destructor$object
  0: code
      * #source_location: 
        * file: <builtin-library-pthread_key_create>
        * line: 11
        * function: pthread_key_create
        * working_directory: /home/ec2-user/kani-reproducer/src
      * return_type: empty
          * #source_location: 
            * file: <builtin-library-pthread_key_create>
            * line: 11
            * function: pthread_key_create
            * working_directory: /home/ec2-user/kani-reproducer/src
      * parameters: 
        0: parameter
            * type: pointer
                * #source_location: 
                  * file: <builtin-library-pthread_key_create>
                  * line: 11
                  * function: pthread_key_create
                  * working_directory: /home/ec2-user/kani-reproducer/src
                * width: 64
                0: empty
                    * #source_location: 
                      * file: <builtin-library-pthread_key_create>
                      * line: 11
                      * function: pthread_key_create
                      * working_directory: /home/ec2-user/kani-reproducer/src
            * #source_location: 
              * file: <builtin-library-pthread_key_create>
              * line: 11
              * function: pthread_key_create
              * working_directory: /home/ec2-user/kani-reproducer/src
Verification Time: 0.81680673s
```

</details>

### PR DESCRIPTION
**Pull request by celinval**
### Description of changes: 

C-FFI is fairly unstable right now and the lack of error handling causes a poor experience when things go wrong. 

In this PR, we limit its usage to only support CBMC built-in functions that are explicitly included in Kani and alloc functions from `kani_lib.c`. User's should still be enable to go back to previous behavior by enabling unstable C-FFI support

### Resolved issues:

Resolves #1781 

### Call-outs:

This PR is currently blocked by https://github.com/model-checking/kani/pull/2427. Once that gets merged, the regression should pass.

### Testing:

* How is this change tested? New tests

* Is this a refactor change? Kinda

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by zhassan-aws — COMMENTED** [review]
Looks good. Mostly minor comments.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+use cbmc::goto_program::{Expr, Location, Stmt, Symbol, Type};
+use cbmc::{InternString, InternedString};
+use kani_queries::UserInput;
+use lazy_static::lazy_static;
+use rustc_middle::ty::Instance;
+use rustc_target::abi::call::Conv;
+use tracing::{debug, trace};
+
+lazy_static! {
+    static ref RUST_ALLOC_FNS: HashSet<InternedString> = {
```
Comment (zhassan-aws) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs:24]: Might want to add a comment that this should be kept in sync with `kani_lib.c`. And perhaps add a comment in `kani_lib.c` itself.

File: tests/kani/ForeignItems/extern_fn_ptr.rs [hunk 2]
```diff
@@ -0,0 +1,21 @@
+// Copyright Kani Contributors
+// SPDX-License-Identifier: Apache-2.0 OR MIT
+// kani-flags: -Z c-ffi --c-lib tests/kani/ForeignItems/lib.c
+
+//! Check that Kani correctly handle function pointers to C functions.
```
[the remark this answers is not in the document]
Comment (celinval) [reply tests/kani/ForeignItems/extern_fn_ptr.rs:5]: Not sure I understand your question, can you please clarify?

File: tests/ui/missing-function/extern_c/extern_c.rs [hunk 3]
```diff
@@ -1,7 +1,7 @@
 // Copyright Kani Contributors
 // SPDX-License-Identifier: Apache-2.0 OR MIT
 
-// kani-flags: --harness harness
+// kani-flags: --harness harness -Z c-ffi
 
 // This test is to check Kani's error handling for missing functions.
 // TODO: Verify that this prints a compiler warning:
```
[the remark this answers is not in the document]
Comment (celinval) [reply tests/ui/missing-function/extern_c/extern_c.rs:7]: Let me check

File: tests/cargo-kani/libc/Cargo.toml [hunk 4]
```diff
@@ -0,0 +1,13 @@
+# Copyright Kani Contributors
```
[the remark this answers is not in the document]
Comment (celinval) [reply tests/cargo-kani/libc/Cargo.toml:1]: Ah, good catch! Let me do a `git add`. :)

File: kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs (hunk 1 above)
Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs:24]: Actually, the `kani_lib.c` already has proper comments in place.

File: cprover_bindings/src/goto_program/builtin.rs [hunk 5]
```diff
@@ -17,6 +17,8 @@ pub enum BuiltinFn {
     Copysignf,
     Cos,
     Cosf,
+    Error,
+    ErrorNoLocation,
```
Comment (feliperodri) [inline cprover_bindings/src/goto_program/builtin.rs:21]: There is no comment at the top of this enum documenting it. Is this the list of standard function supported by CPROVER? Can I add any builtin function from GCC that CBMC supports as well? Like anything from [here](https://github.com/diffblue/cbmc/tree/71d07e0d507b31220379f54eefb1bf3bb0f7a184/src/ansi-c/compiler_headers).

File: cprover_bindings/src/goto_program/builtin.rs [hunk 6]
```diff
@@ -195,6 +204,8 @@ impl BuiltinFn {
             Copysignf => Type::float(),
             Cos => Type::double(),
             Cosf => Type::float(),
+            Error => Type::c_int().to_pointer(),
+            ErrorNoLocation => Type::c_int().to_pointer(),
```
Comment (feliperodri) [inline cprover_bindings/src/goto_program/builtin.rs:208]: Are these the return type?

File: tests/cargo-kani/libc/Cargo.toml (hunk 4 above)
[the remark this answers is not in the document]
Comment (feliperodri) [reply tests/cargo-kani/libc/Cargo.toml:1]: I'm a bit confuse if this [rule](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) applies in this case.

File: tests/ui/missing-function/extern_c/extern_c.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (feliperodri) [reply tests/ui/missing-function/extern_c/extern_c.rs:7]: why `-Z`?

File: tests/expected/foreign-function/ffi_ptr.rs [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+}
+
+fn may_not_call(call: bool, input: u32, func: unsafe extern "C" fn(u32) -> u32) -> Option<u32> {
+    call.then(|| unsafe { func(input) })
+}
+
+#[kani::proof]
+fn check_fn_ptr_called() {
+    let input: u32 = kani::any();
+    assert_eq!(call_on(input, foreign), input);
```
Comment (feliperodri) [inline tests/expected/foreign-function/ffi_ptr.rs:21]: how can we always guarantee that the return o `call_on` is equal to `input`?

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs [hunk 8]
```diff
@@ -743,19 +743,15 @@ impl<'tcx> GotocCtx<'tcx> {
...
-            )
-            .with_is_extern(true)
-        });
+        let sym = if self.tcx.is_foreign_item(instance.def_id()) {
+            // Get the symbol that represents a foreign instance.
+            self.codegen_foreign_fn(instance)
+        } else {
+            // All non-foreign functions should've been declared beforehand.
+            let func = self.symbol_name(instance);
+            self.symbol_table.lookup(func).unwrap()
```
Comment (feliperodri) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:753]: Shouldn't we add a debug statement here?

File: kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs [hunk 9]
```diff
@@ -0,0 +1,155 @@
...
+                        .with_is_parameter(true);
+                    self.symbol_table.insert(sym);
+                    arg_type.as_parameter(Some(arg_name.into()), Some(base_name.into()))
+                })
+            })
+            .collect();
+        let ret_type = self.codegen_ty(fn_abi.ret.layout.ty);
+
+        if fn_abi.c_variadic {
+            Type::variadic_code(params, ret_type)
```
Comment (feliperodri) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs:123]: Do we have a test case for variadic code?

File: kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs [hunk 10]
```diff
@@ -0,0 +1,155 @@
...
+            "https://github.com/model-checking/kani/issues/2423"
+        } else {
+            "https://github.com/model-checking/kani/issues/new/choose"
+        };
+        self.codegen_assert_assume(
+            Expr::bool_false(),
+            PropertyClass::UnsupportedConstruct,
+            &GotocCtx::unsupported_msg(&msg, Some(url)),
+            loc,
+        )
```
Comment (feliperodri) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs:153]: I assume this will be reported as an assertion failure with the same source location of the unsupported function, correct?

File: kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs [hunk 11]
```diff
@@ -0,0 +1,155 @@
...
+    }
+
+    /// Generate code for a foreign function shim.
+    fn codegen_ffi_shim(&mut self, shim_name: InternedString, instance: Instance<'tcx>) -> Stmt {
+        debug!(?shim_name, ?instance, sym=?self.symbol_table.lookup(shim_name), "generate_foreign_shim");
+
+        let loc = self.codegen_span(&self.tcx.def_span(instance.def_id()));
+        let unsupported_check = self.codegen_ffi_unsupported(instance, loc);
+        Stmt::block(vec![unsupported_check], loc)
+    }
```
Comment (feliperodri) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs:97]: Do we have a test case for this?

File: kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs [hunk 12]
```diff
@@ -0,0 +1,155 @@
...
+use rustc_target::abi::call::Conv;
+use tracing::{debug, trace};
+
+lazy_static! {
+    static ref RUST_ALLOC_FNS: HashSet<InternedString> = {
+        HashSet::from([
+            "__rust_alloc".into(),
+            "__rust_alloc_zeroed".into(),
+            "__rust_dealloc".into(),
+            "__rust_realloc".into(),
```
Comment (feliperodri) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs:29]: Where does this list come from?

File: tests/ui/missing-function/extern_c/extern_c.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (celinval) [reply tests/ui/missing-function/extern_c/extern_c.rs:7]: Updated the comment.

File: cprover_bindings/src/goto_program/builtin.rs (hunk 5 above)
Comment (celinval) [reply cprover_bindings/src/goto_program/builtin.rs:21]: Yes. You can also see that this model doesn't scale really well. The other problem is that the Rust `libc` signature doesn't always matches CBMC's (although they have the same ABI).

File: cprover_bindings/src/goto_program/builtin.rs (hunk 6 above)
Comment (celinval) [reply cprover_bindings/src/goto_program/builtin.rs:208]: yep

File: kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs (hunk 12 above)
Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs:29]: I am adding a comment to describe this in the next version. Basically these are declared in the [Rust alloc module](https://stdrs.dev/nightly/x86_64-unknown-linux-gnu/alloc/alloc/index.html), but they are defined today in [kani_lib.c](https://github.com/model-checking/kani/blob/main/library/kani/kani_lib.c).

File: kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs (hunk 11 above)
Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs:97]: yes. The new tests `expected/foreign-function/ffi_ptr.rs` and `cargo-kani/libc/` both exercise this code.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs (hunk 9 above)
Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs:123]: Yes, we have a fix-me test today. However, it wasn't really checking what it was meant to. I'll create a separate PR that fixes that test since this PR is already big enough.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs (hunk 8 above)
Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:753]: Actually, let me add an expected message so if it ever crashes we have more information.

File: tests/expected/foreign-function/ffi_ptr.rs (hunk 7 above)
Comment (celinval) [reply tests/expected/foreign-function/ffi_ptr.rs:21]: This dummy proof is incomplete since we don't have the body of `foreign`. This would only work if foreign is an identity function.

Comment (celinval) [reply tests/expected/foreign-function/ffi_ptr.rs:21]: btw, I fixed the test here, but what I think we should do later is turn this test into an `expected` test and make sure we are emitting the right error.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs (hunk 9 above)
Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs:129]: btw, I fixed the test here, but what I think we should do later is turn this test into an expected test and make sure we are emitting the right error.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs [hunk 13]
```diff
@@ -0,0 +1,161 @@
...
+use kani_queries::UserInput;
+use lazy_static::lazy_static;
+use rustc_middle::ty::Instance;
+use rustc_target::abi::call::Conv;
+use tracing::{debug, trace};
+
+lazy_static! {
+    /// The list of Rust allocation functions that are declared in the `core::alloc` module
+    /// but defined by each backend.
+    /// For out `goto-program` backend, these functions are defined inside `kani_lib.c`.
```
Comment (zhassan-aws) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/foreign_function.rs:26]:
```suggestion
    /// For our `goto-program` backend, these functions are defined inside `kani_lib.c`.
```

**Review by zhassan-aws — APPROVED** [review]
