### PR TITLE
Emit `dead` goto-instructions on MIR StatementDead

### LINKED ISSUE #3061: Kani should fail due to invalid access of a dead local variable via raw pointer
I tried this code:
```rust
#[kani::proof]
pub fn check_invalid_ptr() {
    let raw_ptr = {
        let var = 10;
        &var as *const _
    };
    // This should fail since it is de-referencing a dead object.
    assert_eq !(unsafe {*raw_ptr}, 10);
}

```

using the following command line invocation:

```
kani invalid_ptr.rs
```

with Kani version: 0.47

I expected to see this happen: Verification should fail since the de-referenced pointer is pointing to a dead object.
Instead, this happened: Verification succeeds

### PR DESCRIPTION
**Pull request by karkhaz**
This commit adds a new `Dead` goto-instruction that gets codegened
whenever Kani sees a MIR `StatementDead` statement. This new
goto instruction corresponds to the CBMC [code_deadt](
https://diffblue.github.io/cbmc/classcode__deadt.html) statement
that marks the point where a local variable goes out of scope.

This new instruction is needed to detect invalid accesses of dead local
variables.

The commit also codegens a CBMC `Decl` instruction upon seeing a MIR
StatementLive. This ensures that variables that go out of scope at the
end of a loop are not falsely marked as having a dead dereference when
they are accessed on the next loop iteration.

Resolves #3061

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: kani-driver/src/call_single_file.rs [hunk 1]
```diff
@@ -122,6 +122,8 @@ impl KaniSession {
                 "symbol-mangling-version=v0",
                 "-Z",
                 "panic_abort_tests=yes",
+                "-Z",
+                "sanitizer=address",
```
Comment (celinval) [inline kani-driver/src/call_single_file.rs:126]: Can you please make sure the code from the standard library has these statements?

If not, we may have to add the same argument here: https://github.com/model-checking/kani/blob/ea710b36/tools/build-kani/src/sysroot.rs#L89

**Review by celinval — COMMENTED** [review]
It looks good. Can you also please add a cargo test to ensure dependencies also contains these statements?

For that, you will have to create 2 crates. You add the defective code in one crate, and the harness in the other crate. Thanks!

File: tests/expected/dead-invalid-access-via-raw/main.rs [hunk 2]
```diff
@@ -0,0 +1,12 @@
+// Copyright Kani Contributors
+// SPDX-License-Identifier: Apache-2.0 OR MIT
+
```
Comment (zhassan-aws) [inline tests/expected/dead-invalid-access-via-raw/main.rs:3]: Please add a comment that explains what this test is checking. It would be useful to add a reference to #3061 as well.

File: kani-driver/src/call_single_file.rs (hunk 1 above)
Comment (zhassan-aws) [reply kani-driver/src/call_single_file.rs:126]: Per our offline discussion, we will follow up on this separately.
