### PR TITLE
Fix Kani crash with const-generic `[e; N]` expression

### LINKED ISSUE #1728: Kani crashes when parsing const generics
(I'm using Kani version 0.11.0)

Kani seems to crash when encountering const generics (See https://github.com/rust-lang/rfcs/blob/master/text/2000-const-generics.md)

I tried this code:
```rust
struct Foo<const N: usize> {
    field: [u64; N],
}

impl<const N: usize> Foo<N> {
    fn new() -> Self {
        Self { field: [0; N] }
    }
}

fn main() {
    Foo::<32>::new();
    println!("Hello, world!");
}

#[cfg(kani)]
mod proofs {
    use super::*;

    #[kani::proof]
    fn kani_crash() {
        Foo::<32>::new();
    }
}
```

which runs fine on `cargo run` but crashes with a backtrace during code generation on `cargo kani`

This is the backtrace:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs:213:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bc4b39c271bbd36736cbf1c0a1ac23d5df38d365/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/bc4b39c271bbd36736cbf1c0a1ac23d5df38d365/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/bc4b39c271bbd36736cbf1c0a1ac23d5df38d365/library/core/src/panicking.rs:48:5
   3: kani_compiler::codegen_cprover_gotoc::codegen::rvalue::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_rvalue
   4: kani_compiler::codegen_cprover_gotoc::codegen::statement::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_statement
   5: kani_compiler::codegen_cprover_gotoc::codegen::block::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_block
   6: kani_compiler::codegen_cprover_gotoc::codegen::function::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_function
   7: std::thread::local::LocalKey<T>::with
   8: <kani_compiler::codegen_cprover_gotoc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
   9: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorGuaranteed>>
  10: <rustc_interface::queries::Queries>::ongoing_codegen
  11: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  12: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  13: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  14: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>

```

### LINKED ISSUE #1768: `lexical-core` crates prevents kani from building
The [lexical-core](https://crates.io/crates/lexical-core) crate causes kani to fail the build. I don't know where to start debugging this, but I can provide logs of the Github action.

[failed build](https://github.com/nyx-space/hifitime/actions/runs/3216395200/jobs/5258243859)
[successful build](https://github.com/nyx-space/hifitime/actions/runs/3215092857/jobs/5255944850)

I also tried preventing the compilation of the single function that uses this by adding `#[cfg(not(kani))]` before it, but that didn't prevent the building. If there's a better method, I'm all ears.

### PR DESCRIPTION
**Pull request by tedinski**
### Description of changes: 

Fixes an omitted call to `monomorphize` when translating `Rvalue::Repeat`

### Resolved issues:

* Resolves #1768 Confirmed the mentioned crate now builds under Kani.
* Resolves #1728 Thanks for the test case!
* Fixes this issue, but reveals another bug, in #1662

### Call-outs:

* The only two instances of `try_eval_usize` where here and in the code under `codegen_ty`. The latter already has a comment (that I clarified) that things should be monomorphized, and we haven't seen a crash there. So just the one fix needed to `Repeat` sounds probable here.

### Testing:

* How is this change tested? new test, failed before, passes now

* Is this a refactor change? no

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by zhassan-aws — APPROVED** [review]

File: tests/kani/Array/repeat_const_generic.rs [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+    }
+}
+
+#[cfg(kani)]
+mod proofs {
+    use super::*;
+
+    #[kani::proof]
+    fn kani_crash() {
+        Foo::<32>::new();
```
Comment (zhassan-aws) [inline tests/kani/Array/repeat_const_generic.rs:22]: Perhaps add an assertion that checks something about the returned value? e.g.:
```rust
let f = Foo::<32>::new();
assert_eq!(f.len(), 32);
```
where the `len` method returns `N`?

File: tests/kani/Array/repeat_const_generic.rs [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+        Self { field: [0; N] }
+    }
+}
+
+#[cfg(kani)]
+mod proofs {
+    use super::*;
+
+    #[kani::proof]
+    fn kani_crash() {
```
Comment (adpaco-aws) [inline tests/kani/Array/repeat_const_generic.rs:21]: Someone reading `kani_crash` may think the test is expect to crash Kani. Please rename the proof to avoid this.

**Review by adpaco-aws — APPROVED** [review]

File: tests/kani/Array/repeat_const_generic.rs (hunk 1 above)
Comment (tedinski) [reply tests/kani/Array/repeat_const_generic.rs:22]: The other file in this directory, `array_init.rs` already contains many tests for the contents of the array. IMO it'd be redundant

Comment (tedinski) [reply tests/kani/Array/repeat_const_generic.rs:22]: Although I guess this is const generic now, ok I'll add one.

**Review by zhassan-aws — APPROVED** [review]
