### PR TITLE
Fix drop of Wrapper<dyn T> and fix unsized cast too

### LINKED ISSUE #426: Fix drop type checking for nested `Arc`/`Mutex` objects
The two `SizeAndAlignOfDst` tests fail with:

```rust
"func":"Expr"{
   "value":"Symbol"{
      "identifier":"_RINvNtCsgWci0eQkB8o_4core3ptr13drop_in_placeNtNtNtCs1HAdiQHUxxm_3std10sys_common5mutex12MovableMutexECsb7rQPrKk64Y_4main"
   },
   "typ":"Code"{
      "parameters":[
         "Parameter"{
            "typ":"Pointer"{
               "typ":"StructTag(""tag-std::sys_common::mutex::MovableMutex"")"
            },
            "identifier":"None",
            "base_name":"None"
         }
      ],
      "return_type":"StructTag(""tag-Unit"")"
   },
   "location":"None"
}"args":[
   "Expr"{
      "value":"Symbol"{
         "identifier":"_RINvNtCsgWci0eQkB8o_4core3ptr13drop_in_placeINtNtNtCs1HAdiQHUxxm_3std4sync5mutex5MutexDNtCsb7rQPrKk64Y_4main10SubscriberEL_EEB1p_::1::var_1"
      },
      "typ":"StructTag(""tag-dyn Subscriber"")",
      "location":"None"
   }
]"', compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/expr.rs:532:9"

stack backtrace:
   0: rust_begin_unwind
             at ./library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at ./library/std/src/panicking.rs:460:5
   2: rustc_codegen_llvm::gotoc::cbmc::goto_program::expr::Expr::call
             at ./compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/expr.rs:532:9
   3: rustc_codegen_llvm::gotoc::statement::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_drop
             at ./compiler/rustc_codegen_llvm/src/gotoc/statement.rs:148:29
   4: rustc_codegen_llvm::gotoc::statement::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_terminator
             at ./compiler/rustc_codegen_llvm/src/gotoc/statement.rs:58:66
   5: rustc_codegen_llvm::gotoc::block::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_block
             at ./compiler/rustc_codegen_llvm/src/gotoc/block.rs:18:29
   6: rustc_codegen_llvm::gotoc::function::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_function::{{closure}}
             at ./compiler/rustc_codegen_llvm/src/gotoc/function.rs:95:71
   7: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at ./library/core/src/iter/traits/iterator.rs:730:29
   8: core::iter::adapters::map::map_fold::{{closure}}
             at ./library/core/src/iter/adapters/map.rs:84:21
   9: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at ./library/core/src/iter/adapters/enumerate.rs:106:27
  10: core::iter::traits::iterator::Iterator::fold
             at ./library/core/src/iter/traits/iterator.rs:2170:21
  11: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at ./library/core/src/iter/adapters/enumerate.rs:112:9
  12: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at ./library/core/src/iter/adapters/map.rs:124:9
  13: core::iter::traits::iterator::Iterator::for_each
             at ./library/core/src/iter/traits/iterator.rs:733:9
  14: rustc_codegen_llvm::gotoc::function::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_function
             at ./compiler/rustc_codegen_llvm/src/gotoc/function.rs:95:13
  15: <rustc_codegen_llvm::gotoc::backend::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{{closure}}
             at ./compiler/rustc_codegen_llvm/src/gotoc/backend.rs:102:35
  16: rustc_codegen_llvm::gotoc::debug::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::call_with_panic_debug_info::{{closure}}
             at ./compiler/rustc_codegen_llvm/src/gotoc/debug.rs:72:13
  17: std::thread::local::LocalKey<T>::try_with
             at ./library/std/src/thread/local.rs:399:16
  18: std::thread::local::LocalKey<T>::with
             at ./library/std/src/thread/local.rs:375:9
  19: rustc_codegen_llvm::gotoc::debug::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::call_with_panic_debug_info
             at ./compiler/rustc_codegen_llvm/src/gotoc/debug.rs:70:9
  20: <rustc_codegen_llvm::gotoc::backend::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at ./compiler/rustc_codegen_llvm/src/gotoc/backend.rs:101:25
  21: rustc_interface::passes::start_codegen::{{closure}}
             at ./compiler/rustc_interface/src/passes.rs:1056:9
  22: rustc_data_structures::profiling::VerboseTimingGuard::run
             at ./compiler/rustc_data_structures/src/profiling.rs:611:9
  23: rustc_session::utils::<impl rustc_session::session::Session>::time
             at ./compiler/rustc_session/src/utils.rs:16:9
  24: rustc_interface::passes::start_codegen
             at ./compiler/rustc_interface/src/passes.rs:1055:19
  25: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}::{{closure}}
             at ./compiler/rustc_interface/src/queries.rs:254:20
  26: rustc_interface::passes::QueryContext::enter::{{closure}}
             at ./compiler/rustc_interface/src/passes.rs:780:42
  27: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at ./compiler/rustc_middle/src/ty/context.rs:1784:50
  28: rustc_middle::ty::context::tls::set_tlv
             at ./compiler/rustc_middle/src/ty/context.rs:1768:9
  29: rustc_middle::ty::context::tls::enter_context
             at ./compiler/rustc_middle/src/ty/context.rs:1784:9
  30: rustc_interface::passes::QueryContext::enter
             at ./compiler/rustc_interface/src/passes.rs:780:9
  31: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}
             at ./compiler/rustc_interface/src/queries.rs:245:13
  32: rustc_interface::queries::Query<T>::compute
             at ./compiler/rustc_interface/src/queries.rs:38:28
  33: rustc_interface::queries::Queries::ongoing_codegen
             at ./compiler/rustc_interface/src/queries.rs:243:9
  34: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at ./compiler/rustc_driver/src/lib.rs:407:13
  35: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at ./compiler/rustc_interface/src/queries.rs:394:19
  36: rustc_driver::run_compiler::{{closure}}
             at ./compiler/rustc_driver/src/lib.rs:312:22
  37: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at ./compiler/rustc_interface/src/interface.rs:209:13
  38: rustc_span::with_source_map
             at ./compiler/rustc_span/src/lib.rs:911:5
  39: rustc_interface::interface::create_compiler_and_run
             at ./compiler/rustc_interface/src/interface.rs:203:5
  40: rustc_interface::interface::run_compiler::{{closure}}
             at ./compiler/rustc_interface/src/interface.rs:225:12
  41: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at ./compiler/rustc_interface/src/util.rs:157:13
  42: scoped_tls::ScopedKey<T>::set
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  43: rustc_span::create_session_globals_then
             at ./compiler/rustc_span/src/lib.rs:105:5
  44: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at ./compiler/rustc_interface/src/util.rs:155:9
  45: rustc_interface::util::scoped_thread::{{closure}}
             at ./compiler/rustc_interface/src/util.rs:130:24
```

### PR DESCRIPTION
**Pull request by celinval**
### Description of changes: 

Fix direct call to drop a fat pointer to a structure with an unsized element. Join similar code that we had to build a reference to a place.

### Resolved issues:

Resolves #426 

### Call-outs:

While inspecting the code, I realized that we were probably not handling slice correctly. The test I added also uncovered an issue with unsized cast, which I also fixed here.

### Testing:

* How is this change tested? New test + fixme test

* Is this a refactor change? No

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: kani-compiler/src/codegen_cprover_gotoc/codegen/place.rs [hunk 1]
```diff
@@ -563,6 +564,45 @@ impl<'tcx> GotocCtx<'tcx> {
...
+            // Build a new fat pointer to the place dereferenced with the metadata from the
+            // original fat pointer.
+            let proj_expr = projection.goto_expr;
+            let data = if proj_expr.typ().is_pointer() {
+                proj_expr
+            } else if proj_expr.typ().is_array_like() {
+                proj_expr.array_to_ptr()
+            } else {
+                proj_expr.address_of()
+            };
```
Comment (danielsn) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/place.rs:592]: Does this happen often enough it could use a utility fn?

File: kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs [hunk 2]
```diff
@@ -1128,8 +1056,13 @@ impl<'tcx> GotocCtx<'tcx> {
...
                 let dst_goto_len = self.codegen_const(*src_elt_count, None);
-                let dst_data_expr =
-                    src_goto_expr.cast_to(self.codegen_ty(*src_elt_type).to_pointer());
+                let src_pointee_ty = pointee_type(coerce_info.src_ty).unwrap();
+                let dst_data_expr = if src_pointee_ty.is_array() {
+                    src_goto_expr.cast_to(self.codegen_ty(*src_elt_type).to_pointer())
+                } else {
+                    // A struct that contains the type being coerced to a slice.
+                    src_goto_expr.cast_to(dst_data_type)
+                };
```
Comment (danielsn) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs:1065]: A comment explaining this using C like pseudocode might make it easier to follow

File: kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs [hunk 3]
```diff
@@ -310,47 +309,30 @@ impl<'tcx> GotocCtx<'tcx> {
...
         let drop_instance = Instance::resolve_drop_in_place(self.tcx, place_ty);
+        debug!(?place_ty, ?drop_instance, "codegen_drop");
+        // Once upon a time we did a `hook_applies` check here, but we no longer seem to hook drops
         let drop_implementation = match drop_instance.def {
             InstanceDef::DropGlue(_, None) => {
                 // We can skip empty DropGlue functions
                 Stmt::skip(loc)
             }
             InstanceDef::DropGlue(_def_id, Some(_)) => {
+                let place_ref = self.codegen_place_ref(place);
```
Comment (danielsn) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/statement.rs:321]: nice

**Review by danielsn — APPROVED** [review]

File: kani-compiler/src/codegen_cprover_gotoc/codegen/place.rs (hunk 1 above)
Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/place.rs:592]: I haven't bumped into it in other places yet but I can still move this to a utility function.
