### PR TITLE
Audit for `offset` intrinsic

### LINKED ISSUE #1082: Pointer sub() operation is giving spurious overflow check error
I tried this code:
```rust
#[kani::proof]
fn check_thin_ptr() {
    let array = [0, 1, 2, 3, 4, 5, 6];
    let second_ptr: *const i32 = &array[3];
    unsafe {
        let before = second_ptr.sub(1);
        assert_eq!(*before, 2);
    }
}
```

using the following command line invocation:

```
kani <test_file>
```

with Kani version:

I expected to see this happen: Verification succeed.

Instead, this happened: It fails with the following message:

```
SUMMARY:
 ** 1 of 9 failed
Failed Checks: attempt to compute offset which would overflow
 File: "rustlib/src/rust/library/core/src/ptr/const_ptr.rs", line 295, in std::ptr::const_ptr::<impl *const T>::offset

VERIFICATION:- FAILED
```

### PR DESCRIPTION
**Pull request by adpaco-aws**
### Description of changes: 

Changes the `offset` intrinsic to use addition with overflow to detect overflow, but computes the actual destination pointer with regular addition. This fixes spurious failures that appeared when offsets were negative or being substracted.

In addition, standard pointer checks cover the case where the pointer is dereferenced outside the object bounds. I've observed that this works as expected: One byte past the object is fine, more than that is not. 5 test cases included.

### Resolved issues:

Resolves #1082 
Part of #727 

### Testing:

* How is this change tested? Adds 5 test cases.

* Is this a refactor change? No.

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: tests/kani/Intrinsics/Offset/offset_u8_fail.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+#![feature(core_intrinsics)]
+use std::intrinsics::offset;
+
+#[kani::proof]
+fn test_offset() {
+    let s: &str = "123";
+    let ptr: *const u8 = s.as_ptr();
+
+    unsafe {
+        let x = *offset(ptr, 4) as char;
```
Comment (celinval) [inline tests/kani/Intrinsics/Offset/offset_u8_fail.rs:16]: nit: For cases like this, I recommend using the expected test suite. `kani-verify-fail` is very fragile.

Not a blocker though.

File: tests/kani/PointerOffset/fixme_overflow_ptr.rs [hunk 2]
```diff
@@ -1,12 +0,0 @@
-// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
-// SPDX-License-Identifier: Apache-2.0 OR MIT
```
Comment (celinval) [inline tests/kani/PointerOffset/fixme_overflow_ptr.rs:2]: I would prefer if we don't delete this one in favor of things that call the intrinsic directly. This is actually closer to what the user code would look like. Can you please just rename it?

**Review by celinval — COMMENTED** [review]
Just small comments. Don't worry about moving the tests to expected, but it is something I recommend for the future.

**Comment by adpaco-aws** [comment]
Thanks, I moved the negative tests to `expected` and restored the "fixme" test (sorry about that).

**Comment by adpaco-aws** [comment]
Thanks, I moved the negative tests to `expected` and restored the "fixme" test (sorry about that).

File: kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs [hunk 3]
```diff
@@ -874,6 +874,31 @@ impl<'tcx> GotocCtx<'tcx> {
...
+        &mut self,
+        intrinsic: &str,
+        mut fargs: Vec<Expr>,
+        p: &Place<'tcx>,
+        loc: Location,
+    ) -> Stmt {
+        let src_ptr = fargs.remove(0);
+        let offset = fargs.remove(0);
+        // Check that the computation would not overflow an `isize`
+        let dst_ptr_of = src_ptr.clone().cast_to(Type::ssize_t()).add_overflow(offset.clone());
```
Comment (danielsn) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs:889]: This does integer arithmatic, not pointer arithmatic, and I think will give the wrong results

**Review by danielsn — CHANGES_REQUESTED** [review]

File: kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs (hunk 3 above)
Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs:889]: I.e.: You should account for the pointee size.

Comment (adpaco-aws) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs]: Right, should be getting the right results now.

**Review by celinval — COMMENTED** [review]
Can you add a test that exercise the new check? Something like:

```rust
/// Check that an offset that overflow an isize::MAX triggers a verification failure.
#[kani::proof]
unsafe fn check_wrap_offset() {
        let v : &[u128] = &[0; 200];
        let v_100 : *const u128 = &v[100];
        let max_offset = usize::MAX / std::mem::size_of::<u128>();
        let v_wrap : *const u128 = v_100.offset((max_offset + 1).try_into().unwrap());
        assert_eq!(v_100, v_wrap);
        assert_eq!(*v_100, *v_wrap);
}
```

**Review by danielsn — APPROVED** [review]
Approved modulo @celinval comments

File: kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs [hunk 4]
```diff
@@ -868,6 +868,45 @@ impl<'tcx> GotocCtx<'tcx> {
...
+
+        // Check that computing `bytes` would not overflow
+        let ty = self.monomorphize(instance.substs.type_at(0));
+        let layout = self.layout_of(ty);
+        let size = Expr::int_constant(layout.size.bytes(), Type::ssize_t());
+        let bytes = offset.clone().mul_overflow(size);
+        let bytes_overflow_check = self.codegen_assert(
+            bytes.overflowed.not(),
+            PropertyClass::ArithmeticOverflow,
+            format!("{}: attempt to compute `bytes` which would overflow", intrinsic).as_str(),
```
[the remark this answers is not in the document]
Comment (adpaco-aws) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs]: Thanks, changed both messages to avoid `format!` :)

File: kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs [hunk 5]
```diff
@@ -868,6 +868,45 @@ impl<'tcx> GotocCtx<'tcx> {
         Stmt::atomic_block(vec![skip_stmt], loc)
     }
 
+    // Computes the offset from a pointer
```
[the remark this answers is not in the document]
Comment (adpaco-aws) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs]: Done.

**Comment by adpaco-aws** [comment]
Addressed all @celinval's comments, including the proposed test case.
