### PR TITLE
Upgrade to CBMC 5.68.0 (with fixes)

### LINKED ISSUE #1779: Updating to latest CBMC version requires update to architecture strings
With https://github.com/diffblue/cbmc/pull/7215 Kani will need to update various `int_constant` (and `int_constant_from_bool`) entries in `cprover_bindings/src/env.rs` to produce constants of type "integer" instead of the 32-bit bitvector type int.

### PR DESCRIPTION
**Pull request by adpaco-aws**
### Description of changes: 

Upgrades CBMC to v5.68.0 and changes Kani so that it conforms with the latest changes in CBMC:
 * Changes the type of Kani-generated CProver primitives to the `integer` type where appropriate (also adds required support to generate `integer` ireps). This change was forced by CBMC (see https://github.com/model-checking/kani/issues/1779)
 * Redefines C functions with `void` return types so they use type `struct Unit` instead. This is necessary because of stricter type-checking in CBMC (likely caused by https://github.com/diffblue/cbmc/pull/6547)
 * Always pushes `--slice-formula`, even in the cases where we didn't (opened #1810 for debugging).
 * Moves the diamond dependency test into the `cargo-kani` suite. This was the last test failing, but it run its own compilation process so it was dubious. Moving into `cargo-kani` showed no issues.

### Resolved issues:

Resolves #1779 

### Testing:

* How is this change tested? Existing egression.

* Is this a refactor change? No.

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: cprover_bindings/src/env.rs [hunk 1]
```diff
@@ -58,7 +65,7 @@ pub fn machine_model_symbols(mm: &MachineModel) -> Vec<Symbol> {
         ),
         int_constant("__CPROVER_architecture_wchar_t_width", mm.wchar_t_width),
         int_constant("__CPROVER_architecture_word_size", mm.word_size),
-        int_constant("__CPROVER_rounding_mode", mm.rounding_mode),
+        int_constant_c_int("__CPROVER_rounding_mode", mm.rounding_mode),
```
Comment (danielsn) [inline cprover_bindings/src/env.rs:68]: Seriously? There is one remaining outlier? Is there an issue open to CBMC about that?

File: cprover_bindings/src/goto_program/typ.rs [hunk 2]
```diff
@@ -343,6 +347,7 @@ impl Type {
             IncompleteStruct { .. } => unreachable!("IncompleteStruct doesn't have a sizeof"),
             IncompleteUnion { .. } => unreachable!("IncompleteUnion doesn't have a sizeof"),
             InfiniteArray { .. } => unreachable!("InfiniteArray doesn't have a sizeof"),
+            Integer => st.machine_model().int_width,
```
Comment (tautschnig) [inline cprover_bindings/src/goto_program/typ.rs:350]: This doesn’t have a sizeof, should be handled like the line before.

File: cprover_bindings/src/goto_program/typ.rs [hunk 3]
```diff
@@ -286,6 +289,7 @@ impl Type {
             CInteger(CIntType::Bool) => Some(mm.bool_width),
             CInteger(CIntType::Char) => Some(mm.char_width),
             CInteger(CIntType::Int) => Some(mm.int_width),
+            Integer => Some(mm.int_width),
```
Comment (tautschnig) [inline cprover_bindings/src/goto_program/typ.rs:292]: This one is unbounded, it doesn’t have a bitwidth.

File: cprover_bindings/src/goto_program/typ.rs [hunk 4]
```diff
@@ -46,6 +46,8 @@ pub enum Type {
     IncompleteStruct { tag: InternedString },
     /// `union x {}`
     IncompleteUnion { tag: InternedString },
+    /// `integer`
```
Comment (danielsn) [inline cprover_bindings/src/goto_program/typ.rs:49]: What is the difference between this and CInteger?

File: cprover_bindings/src/goto_program/typ.rs (hunk 2 above)
Comment (danielsn) [inline cprover_bindings/src/goto_program/typ.rs:350]: Are we sure that's true? Is there documentation for this?

File: kani-driver/src/call_cbmc.rs [hunk 5]
```diff
@@ -124,12 +124,17 @@ impl KaniSession {
...
+        // Previously, this would happen if the condition below was satisfied:
+        // ```rust
+        // if !self.args.visualize
+        //   && self.args.concrete_playback.is_none()
+        //   && !self.args.no_slice_formula
+        // ```
+        // But for some reason, not pushing it causes a CBMC invariant violation
+        // since version 5.68.0.
+        // <https://github.com/model-checking/kani/issues/1810>
+        args.push("--slice-formula".into());
```
Comment (danielsn) [inline kani-driver/src/call_cbmc.rs:137]: Does this mess with concrete playback?

File: library/kani/kani_lib.c [hunk 6]
```diff
@@ -8,6 +8,12 @@
 #include <stdlib.h>
 #include <string.h>
 
+// Note: the Kani compiler changes `void` return types to the empty tuple `()`
+// AKA `VoidUnit`. Because of that, we need to declare its type `struct Unit`
+// and the extern instance `VoidUnit` here.
```
Comment (danielsn) [inline library/kani/kani_lib.c:13]: I'm not sure this is an accurate description.  Rust `()` is not the same thing as void, and `__rust_dealloc` is extern Rust not extern C https://stdrs.dev/nightly/x86_64-unknown-linux-gnu/src/alloc/alloc.rs.html#37

File: kani-driver/src/call_cbmc.rs (hunk 5 above)
Comment (adpaco-aws) [reply kani-driver/src/call_cbmc.rs:137]: Needs more investigation.

My understanding was that using `--slice-formula` with concrete playback may remove calls to `kani::any()` from the trace, which doesn't allow us to provide a counter-example (in that case, we just report a test couldn't be generated). But all tests we have for concrete playback and `--visualize` pass if we use `--slice-formula`.

File: library/kani/kani_lib.c (hunk 6 above)
Comment (adpaco-aws) [reply library/kani/kani_lib.c:13]: OK, I've changed it to the same comment we use in the Kani compiler's `typ.rs` module:
```
/// Mapping unit to `void` works for functions with no return type but not for
/// variables with type unit. We treat both uniformly by declaring an empty
/// struct type: `struct Unit {}` and a global variable `struct Unit VoidUnit`
/// returned by all void functions (both declared by the Kani compiler).
```

File: cprover_bindings/src/goto_program/typ.rs (hunk 4 above)
Comment (adpaco-aws) [reply cprover_bindings/src/goto_program/typ.rs]: This one's a machine independent integer. Added that in the comment.

File: cprover_bindings/src/env.rs (hunk 1 above)
Comment (adpaco-aws) [reply cprover_bindings/src/env.rs:70]: Couldn't find one, so I opened https://github.com/diffblue/cbmc/issues/7282 (and pasted the issue there)

File: cprover_bindings/src/goto_program/typ.rs (hunk 2 above)
Comment (adpaco-aws) [reply cprover_bindings/src/goto_program/typ.rs]: Done.

File: cprover_bindings/src/goto_program/typ.rs (hunk 3 above)
Comment (adpaco-aws) [reply cprover_bindings/src/goto_program/typ.rs]: Done. Thanks!

File: cprover_bindings/src/goto_program/typ.rs (hunk 2 above)
Comment (adpaco-aws) [reply cprover_bindings/src/goto_program/typ.rs]: Looks like it's not (see @tautschnig comments).

Comment (adpaco-aws) [reply cprover_bindings/src/goto_program/typ.rs]: Done.

File: cprover_bindings/src/goto_program/typ.rs (hunk 3 above)
Comment (adpaco-aws) [reply cprover_bindings/src/goto_program/typ.rs]: Actually, do you think we should return `None` or just `Some(x)` where x is a large number?

**Comment by tautschnig** [comment]
High-level note: you might consider upgrading to 5.69.1 right away, which will be out later on today (https://github.com/diffblue/cbmc/pull/7283).

File: cprover_bindings/src/env.rs (hunk 1 above)
Comment (tautschnig) [reply cprover_bindings/src/env.rs:70]: I'll comment on the CBMC issue, but indeed rounding mode is different.

**Comment by adpaco-aws** [comment]
> High-level note: you might consider upgrading to 5.69.1 right away, which will be out later on today ([diffblue/cbmc#7283](https://github.com/diffblue/cbmc/pull/7283)).

Tried now, but `brew` couldn't find it in CI. I'm rolling back to v5.68.0 for now.

**Comment by tautschnig** [comment]
> > High-level note: you might consider upgrading to 5.69.1 right away, which will be out later on today ([diffblue/cbmc#7283](https://github.com/diffblue/cbmc/pull/7283)).
> 
> Tried now, but `brew` couldn't find it in CI. I'm rolling back to v5.68.0 for now.

Please retry, should just be a matter of timing.

File: cprover_bindings/src/goto_program/typ.rs (hunk 3 above)
Comment (danielsn) [reply cprover_bindings/src/goto_program/typ.rs]: Maybe we can have an "infinite" token? But `Some(x)` is semantically wrong for all `x`

File: tests/kani/ForeignItems/lib.c [hunk 7]
```diff
@@ -48,7 +55,11 @@ struct Foo2 {
 
 uint32_t S = 12;
 
-void update_static() { S++; }
+struct Unit update_static()
```
Comment (danielsn) [inline tests/kani/ForeignItems/lib.c:58]: This is something that ought to work once C-FFI is in place.  We should have comments and a tracking ticket explaining that this is a workaround we want to remove

**Review by danielsn — APPROVED** [review]
