### PR TITLE
Reject proof harnesses with arguments

### LINKED ISSUE #661: RMC should use fully qualified name for harness selection and it should not rely on `no_mangle` attribute
Users should be able to use RMC to target functions with the same name in different modules. For example, if user wants to verify the following code:

```rust
mod first {
    fn check() {
        // some check
    }
}

mod second {
    fn check() {
        // check for second module
    }
}

pub fn check() {
  // full check
}
```

They should be able to provide which function they want to check. I.e:
```
rmc multiple.rs --function [check | first::check | second::check]
```

Note that users cannot use `#[no_mangle]` for the check functions, since this would cause a name conflict. The compilation would fail with the following error:
```
error: symbol `check` is already defined
  --> multiple.rs:26:1
   |
26 | fn check() {
   | ^^^^^^^^^^^^^^

error: aborting due to previous error

```

### LINKED ISSUE #689: Introduce rmctool attribute validation
We presently do not do any validation of `rmctool` attributes in the rmc compiler.

Presently, we only have `rmctool::proof`, so the only real missing validations are:

* [x] Check to ensure there aren't multiple proof attributes on the function.
* [x] Check there's no parameters to proof (`#[rmc::proof(stuff, here)]`)
* [ ] Check the function being annotated to ensure it has no parameters. (Initially: in the future, we might try to handle parameters as `nondet`. But this is something to design to handle the assumptions problem...)

When we add more attributes, those need validation too.

Possibly we should do this at the `proc_macro` level, instead of in the rmc backend of the compiler?

### LINKED ISSUE #1919: Inconsistent behavior when functions with parameters are used as harnesses
Consider the following program:
```rust
#[kani::proof]
fn foo(c: char) {
    assert!(char::from_u32(c as u32).is_some());
}

#[kani::proof]
fn bar() {
    let c = kani::any();
    foo(c);
}
```
When run with:
```
kani entry.rs --harness bar
```
verification succeeds as expected:
```
SUMMARY:
 ** 0 of 67 failed

VERIFICATION:- SUCCESSFUL
```
However, when run with
```
kani entry.rs --harness foo
```
verification fails:
```
SUMMARY:
 ** 1 of 11 failed
Failed Checks: assertion failed: char::from_u32(c as u32).is_some()
 File: "/home/ubuntu/examples/entry.rs", line 3, in foo

VERIFICATION:- FAILED
```
Kani version: 4db1b0964a3

This is caused by not applying the validity constraints on `char` in the `foo` version.

### PR DESCRIPTION
**Pull request by celinval**
### Description of changes: 

- Change `#[kani::proof]` expansion so it doesn't include `#[no_mangle]` but includes `[allow(dead_code)]`. (#661 and #689).

- Add a check for harnesses with arguments and merge the checks into one function (#1919). 

### Resolved issues:

Fixes #661
Fixes #689
Fixes #1919

### Testing:

* How is this change tested? New test

* Is this a refactor change?

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: kani-compiler/src/codegen_cprover_gotoc/codegen/function.rs [hunk 1]
```diff
@@ -245,33 +249,37 @@ impl<'tcx> GotocCtx<'tcx> {
...
+                if !self.fn_abi_of_instance(instance, ty::List::empty()).args.is_empty() {
+                    self.tcx
+                        .sess
+                        .span_err(span, "Functions used as harnesses can not have any arguments.");
+                }
             }
+        }
+    }
+
+    pub fn is_proof_harness(&self, def_id: DefId) -> bool {
```
Comment (tedinski) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/function.rs:263]: Since this function is called from e.g. reachability, it might not be appropriate to the put the check here. It may get called multiple times?

**Review by tedinski — APPROVED** [review]

**Comment by tedinski** [comment]
One other thing: Can we change the PR title? Want to ensure that whoever write the release notes will notice that this is a possible "breaking" change.

Maybe:

> Properly reject proof harnesses with arguments, and don't change harness symbol names

File: kani-compiler/src/codegen_cprover_gotoc/codegen/function.rs [hunk 2]
```diff
@@ -232,11 +233,14 @@ impl<'tcx> GotocCtx<'tcx> {
         self.reset_current_fn();
     }
 
-    pub fn is_proof_harness(&self, def_id: DefId) -> bool {
-        let all_attributes = self.tcx.get_attrs_unchecked(def_id);
-        let (proof_attributes, _) = partition_kanitool_attributes(all_attributes);
+    /// Check that if an item is tagged with a proof_attribute, it is a valid harness.
+    fn check_proof_attribute(&self, def_id: DefId, proof_attributes: Vec<&Attribute>) {
         if !proof_attributes.is_empty() {
```
Comment (zhassan-aws) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/function.rs:238]: This condition is also checked by the callers. Should we remove it and turn it into an assert?

File: kani-compiler/src/codegen_cprover_gotoc/codegen/function.rs [hunk 3]
```diff
@@ -232,11 +233,14 @@ impl<'tcx> GotocCtx<'tcx> {
...
             let span = proof_attributes.first().unwrap().span;
+            if proof_attributes.len() > 1 {
+                self.tcx.sess.span_warn(proof_attributes[0].span, "Duplicated attribute");
```
Comment (zhassan-aws) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/function.rs:241]:
```suggestion
                self.tcx.sess.span_warn(proof_attributes[0].span, "Duplicate attribute");
```

File: kani-compiler/src/codegen_cprover_gotoc/codegen/function.rs (hunk 2 above)
Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/function.rs:238]: Sure

File: kani-compiler/src/codegen_cprover_gotoc/codegen/function.rs (hunk 1 above)
Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/function.rs:263]: It already was being checked twice. But I'm ok removing from here.

**Review by zhassan-aws — APPROVED** [review]
