### PR TITLE
Remove the overflow checks for wrapping_offset

### LINKED ISSUE #3582: Spurious failure in pointer offset
I tried this code:

```rust
#[kani::proof]
fn check_foo() {
    let x: u8 = 0;
    let ptr: *const u8 = &x as *const u8;
    let count = isize::MAX - 800;
    let _ = ptr.wrapping_offset(count);
}
```

using the following command line invocation:

```
kani lib.rs
```

with Kani version: fe17fdc31f5

I expected to see this happen: Verification successful.

Instead, this happened: Verification failed:
```bash
RESULTS:
Check 1: std::ptr::const_ptr::<impl *const u8>::wrapping_offset.arithmetic_overflow.1
         - Status: SUCCESS
         - Description: "arith_offset: attempt to compute number in bytes which would overflow"
         - Location: ../../../.rustup/toolchains/nightly-2024-10-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/const_ptr.rs:481:18 in function std::ptr::const_ptr::<impl *const u8>::wrapping_offset

Check 2: std::ptr::const_ptr::<impl *const u8>::wrapping_offset.arithmetic_overflow.2
         - Status: FAILURE
         - Description: "attempt to compute offset which would overflow"
         - Location: ../../../.rustup/toolchains/nightly-2024-10-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/const_ptr.rs:481:18 in function std::ptr::const_ptr::<impl *const u8>::wrapping_offset

Check 3: check_foo.assertion.1
         - Status: SUCCESS
         - Description: "attempt to subtract with overflow"
         - Location: lib.rs:5:17 in function check_foo


SUMMARY:
 ** 1 of 3 failed
Failed Checks: attempt to compute offset which would overflow
 File: "/home/ubuntu/.rustup/toolchains/nightly-2024-10-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/const_ptr.rs", line 481, in std::ptr::const_ptr::<impl *const u8>::wrapping_offset

VERIFICATION:- FAILED
```

### PR DESCRIPTION
**Pull request by zhassan-aws**
This PR removes the overflow checks done for the `arith_offset` intrinsic, which is used in implementation of `ptr::wrapping_offset`. According to the documentation, this operation is always safe:

https://doc.rust-lang.org/std/primitive.pointer.html#method.wrapping_offset
https://doc.rust-lang.org/std/intrinsics/fn.arith_offset.html

See https://github.com/model-checking/kani/issues/3582#issuecomment-2403453345 for the context.

Resolves #3582 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: tests/expected/offset-overflow/main.rs [hunk 1]
```diff
@@ -8,13 +8,12 @@ use std::intrinsics::offset;
...
 #[kani::proof]
 fn test_offset_overflow() {
-    let a: [i32; 3] = [1, 2, 3];
-    let ptr: *const i32 = a.as_ptr();
+    let s: &str = "123";
+    let ptr: *const u8 = s.as_ptr();
 
-    // a value that when multiplied by the size of i32 (i.e. 4 bytes)
-    // would overflow `isize`
-    let count: isize = isize::MAX / 4 + 1;
```
Comment (celinval) [inline tests/expected/offset-overflow/main.rs:16]: What's wrong with this?

**Review by celinval — APPROVED** [review]
Thanks

File: tests/expected/offset-overflow/main.rs (hunk 1 above)
Comment (zhassan-aws) [reply tests/expected/offset-overflow/main.rs:16]: Nothing. I changed this test in #3584 to have an overflow in the multiplication operation, but then realized that it was meant to check overflow in the addition operation, so I reverted the change.
