### PR TITLE
Fix ICE due to mishandling of Aggregate rvalue for raw pointers to `str`

### LINKED ISSUE #3312: Kani internal panic when calling somehwat complex library path with no symbolic inputs
I tried this code:
```rust
    #[kani::proof]
    #[kani::unwind(101)]
    fn safe_indexing() {
        let args_len: usize = kani::any();
        kani::assume(args_len < 100);
        let mut args: Vec<i32> = vec![];
        for _ in 0..args_len {
            args.push(kani::any());
        }
        let name = "foo".parse().unwrap();

        // All we care is that this doesn't panic
        let _ = CedarValueJson::extract_arg(&args, &name);
    }
```
Where `.parse()` is created a value of type `Name` from [cedar-policy-core](https://docs.rs/cedar-policy-core/latest/cedar_policy_core/ast/struct.Name.html#)

using the following command line invocation:

```
cargo kani
```

with Kani version:

I expected to see this happen: either proof succeeds or fails

Instead, this happened: 
```
error: internal compiler error: Kani unexpectedly panicked at panicked at cprover_bindings/src/goto_program/stmt.rs:172:9:
                                assertion `left == right` failed: Error: assign statement with unequal types lhs StructTag("tag-refstr") rhs Pointer { typ: FlexibleArray { typ: Unsignedbv { width: 8 } } }
                                  left: StructTag("tag-refstr")
                                 right: Pointer { typ: FlexibleArray { typ: Unsignedbv { width: 8 } } }.

thread 'rustc' panicked at cprover_bindings/src/goto_program/stmt.rs:172:9:
assertion `left == right` failed: Error: assign statement with unequal types lhs StructTag("tag-refstr") rhs Pointer { typ: FlexibleArray { typ: Unsignedbv { width: 8 } } }
  left: StructTag("tag-refstr")
 right: Pointer { typ: FlexibleArray { typ: Unsignedbv { width: 8 } } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Kani unexpectedly panicked during compilation.
Please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md

[Kani] current codegen item: codegen_function: std::ptr::from_raw_parts::<str>
_RINvNtNtCscBmSNMcqgUz_4core3ptr8metadata14from_raw_partseECs9jBWyIwnR1b_14regex_automata
[Kani] current codegen location: Loc { file: "/github/home/.rustup/toolchains/nightly-2024-05-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/metadata.rs", function: None, start_line: 113, start_col: Some(1), end_line: 116, end_col: Some(14) }
error: could not compile `cedar-policy-core` (lib); 8 warnings emitted
error: Failed to compile `cedar_policy_core` due to an internal compiler error.: error: internal compiler error: Kani unexpectedly panicked at panicked at cprover_bindings/src/goto_program/stmt.rs:172:9:
                                assertion `left == right` failed: Error: assign statement with unequal types lhs StructTag("tag-refstr") rhs Pointer { typ: FlexibleArray { typ: Unsignedbv { width: 8 } } }
                                  left: StructTag("tag-refstr")
                                 right: Pointer { typ: FlexibleArray { typ: Unsignedbv { width: 8 } } }.
```

### PR DESCRIPTION
**Pull request by celinval**
We were missing a match arm for the case where a raw pointer to a string slice was created from a thin pointer and the string size.

Resolves #3312 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: tests/perf/smol_str/src/lib.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// Copyright Kani Contributors
+// SPDX-License-Identifier: Apache-2.0 OR MIT
+//! Test that Kani can correctly verify the cedar implementation of `SmolStr`
+//! An ICE was initially reported for this case in:
+//! <https://github.com/model-checking/kani/issues/3312>
+
+#[kani::proof]
+#[kani::unwind(4)]
```
Comment (adpaco-aws) [inline tests/perf/smol_str/src/lib.rs:8]: Is this annotation required for unwinding to terminate?

File: kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs [hunk 2]
```diff
@@ -694,6 +694,14 @@ impl<'tcx> GotocCtx<'tcx> {
                         let meta = self.codegen_operand_stable(&operands[1]);
                         slice_fat_ptr(typ, data_cast, meta, &self.symbol_table)
                     }
+                    TyKind::RigidTy(RigidTy::Str) => {
+                        let pointee_goto_typ = Type::unsigned_int(8);
+                        // cast data to pointer with specified type
+                        let data_cast =
+                            data.cast_to(Type::Pointer { typ: Box::new(pointee_goto_typ.clone()) });
```
Comment (adpaco-aws) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs:701]: Do we really need `clone()` here?

Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs:701]: My bad, I used to have a log statement after this one.

File: tests/perf/smol_str/src/lib.rs (hunk 1 above)
Comment (celinval) [reply tests/perf/smol_str/src/lib.rs:8]: I don't remember if I just automatically added it. Let me double check

File: kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs (hunk 2 above)
Comment (celinval) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs:701]:
```suggestion
                            data.cast_to(Type::Pointer { typ: Box::new(pointee_goto_typ) });
```

File: tests/perf/smol_str/src/lib.rs (hunk 1 above)
Comment (adpaco-aws) [reply tests/perf/smol_str/src/lib.rs:8]: I'm asking in case this is an example where Kani cannot automatically unwind. But I don't know if/where we're compiling this information...

Comment (adpaco-aws) [reply tests/perf/smol_str/src/lib.rs:8]: Thanks!

**Review by adpaco-aws — APPROVED** [review]
