### PR TITLE
Prevent kani crash during setup for first time

### LINKED ISSUE #1545: Interrupted first-time setup procedure cannot resume
I tried these commands:

Install kani with `cargo install kani-verifier` and run `kani --help`

```bash
$ kani --help                 
[0/6] Running Kani first-time setup...
[1/6] Ensuring the existence of: /home/wayne/.kani/kani-0.8.0
[2/6] Downloading Kani release bundle: kani-0.8.0-x86_64-unknown-linux-gnu.tar.gz
^C
```
then kill it with `Ctrl C`. And re-run `kani --help` got:
```bash
$ kani --help
Error: Failed to invoke kani-driver

Caused by:
    No such file or directory (os error 2)
```

The content in `~/.kani`:
```bash
$ ll ~/.kani/
total 1004K
drwxr-xr-x 1 wayne wayne     0 Aug 18 22:59 kani-0.8.0
-rw-r--r-- 1 wayne wayne 1004K Aug 18 23:00 kani-0.8.0-x86_64-unknown-linux-gnu.tar.gz
```

After removing the content in `~/.kani` it goes normal
```bash
$ rm -r ~/.kani/*

$ kani --help                 
[0/6] Running Kani first-time setup...
[1/6] Ensuring the existence of: /home/wayne/.kani/kani-0.8.0
[2/6] Downloading Kani release bundle: kani-0.8.0-x86_64-unknown-linux-gnu.tar.gz
```

with Kani version: `v0.8.0` 

I expected to see this happen: `kani` can recognize the setup procedure is not finished and keep on setting things up.

Logs with backtrace:
```bash
$ RUST_BACKTRACE=1 kani --help
Error: Failed to invoke kani-driver

Caused by:
    No such file or directory (os error 2)

Stack backtrace:
   0: kani_verifier::proxy
   1: std::sys_common::backtrace::__rust_begin_short_backtrace
   2: std::rt::lang_start::{{closure}}
   3: std::rt::lang_start_internal
   4: main
   5: <unknown>
   6: __libc_start_main
   7: _start
```

I guess this is because the tarball's download hasn't finished. Maybe verifying the checksum or downloading it to a temporary filename before finishing can solve this?

### PR DESCRIPTION
**Pull request by jaisnan**
> Please ensure your PR description includes the following:
> 1. A description of how your changes improve Kani.
> 2. Some context on the problem you are solving.
> 3. A list of issues that are resolved by this PR.
> 4. If you had to perform any manual test, please describe them.
>
> **Make sure you remove this list from the final PR description.**

By using the `tar` file as a lock mechanism, we can detect incomplete setups i.e when both `kani's` working directory and the tar file present before setup, we can simply use the local bundle to start setup again.

This still carries the minor risk that the setup getting interrupted (for the first time) while the tar file is being downloaded. In that case, we can inform the user about the broken tar extraction and ask them to restart the setup process.

Unfortunately, can't be tested automatically.

Resolves #1545 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: src/setup.rs [hunk 1]
```diff
@@ -92,7 +108,10 @@ fn setup_kani_bundle(kani_dir: &Path, use_local_bundle: Option<OsString>) -> Res
             .arg("-zxf")
             .arg(&path)
             .current_dir(&kani_dir)
-            .run()?;
+            .run()
+            .context(
+                "Failed to extract tar file, try removing Kani setup and restarting the setup step",
```
Comment (tautschnig) [inline src/setup.rs:113]: What exactly should the user do to remove "Kani setup?"

File: src/setup.rs [hunk 2]
```diff
@@ -53,6 +53,22 @@ pub fn appears_setup() -> bool {
     kani_dir().expect("couldn't find kani directory").exists()
 }
 
+// Ensure that the tar file does not exist, essentially using it's presence
```
Comment (tautschnig) [inline src/setup.rs:56]: s/it's/its/

File: src/setup.rs (hunk 1 above)
Comment (jaisnan) [reply src/setup.rs:113]: Can I add a direct suggestion to remove it by invoking `rm ~/.kani`?

**Review by tautschnig — APPROVED** [review]
