### PR TITLE
Fix issue with value_of / align_of traits

### LINKED ISSUE #1074: Kani implementations of `mem::size_of_val` and `mem::align_of_val` are incorrect for traits
I added a test case here: [tests/kani/Intrinsics/SizeOfVal/fixme_size_of_fat_ptr.rs](https://github.com/model-checking/kani/commit/2ec1da9473bc298a795e6daa50530f125d07fe9c#diff-1b86643bc21300182c32776e56fd65b6ae1e106b3400593efac0fe2563f46acf)

It fails due to incorrect implementation of `size_of_val`. See test for more details.

### PR DESCRIPTION
**Pull request by celinval**
### Description of changes: 

We were trying to figure out the values of those properties during runtime, which is not possible. Fix the code to look for the information in the vtable instead.

### Resolved issues:

Fixes #1074 

### Call-outs:

This is v2. The initial PR was trying to mitigate it but it turned out that the fix was straight forward.

### Testing:

* How is this change tested? New tests

* Is this a refactor change? No

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs [hunk 1]
```diff
@@ -294,7 +294,17 @@ impl<'tcx> GotocCtx<'tcx> {
                 let tp_ty = instance.substs.type_at(0);
                 let arg = fargs.remove(0);
                 let size_align = self.size_and_align_of_dst(tp_ty, arg);
-                self.codegen_expr_to_place(p, size_align.$which)
+                if size_align.is_some() {
```
Comment (danielsn) [inline src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs:297]: `if let Some` instead of using `unwrap`?

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs [hunk 2]
```diff
@@ -946,25 +956,24 @@ impl<'tcx> GotocCtx<'tcx> {
...
-                // The size of &dyn Trait is two words.
-                let size = Expr::int_constant((layout.size.bytes_usize()) * 2, Type::size_t());
-                // The alignment of &dyn Trait is the word size.
-                let align = Expr::int_constant(layout.align.abi.bytes(), usizet);
-                SizeAlign { size, align }
+                // TODO: We don't support size of dynamic yet.
+                // https://github.com/model-checking/kani/issues/1074
+                // The size of dyn T is only known at runtime. Thus, we need to retrieve that
+                // information from the object vtable.
+                None
```
Comment (danielsn) [inline src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs:976]: Does `arg.member("vtable").member("size")` not work here?

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs [hunk 3]
```diff
@@ -1004,7 +1013,7 @@ impl<'tcx> GotocCtx<'tcx> {
                 // Call this function recursively to compute the size and align for the last field.
                 let field_ty = layout.field(self, n).ty;
                 let SizeAlign { size: unsized_size, align: mut unsized_align } =
-                    self.size_and_align_of_dst(field_ty, arg);
+                    self.size_and_align_of_dst(field_ty, arg.clone())?;
```
Comment (danielsn) [inline src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs:1016]: Why is this clone now needed?

File: tests/kani/Intrinsics/AlignOfVal/fixme_align_of_fat_ptr.rs [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+    id: u128,
+}
+
+impl T for A {}
+
+#[cfg_attr(kani, kani::proof)]
+fn check_align_simple() {
+    let a = A { id: 0 };
+    let t: &dyn T = &a;
+    assert_eq!(align_of_val(t), 8);
```
Comment (danielsn) [inline tests/kani/Intrinsics/AlignOfVal/fixme_align_of_fat_ptr.rs:22]: Does this assume a particular architecture?

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs (hunk 1 above)
Comment (celinval) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs:297]: Yes, because this can be None.

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs (hunk 2 above)
Comment (celinval) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs:976]: Probably. I just didn't have time to go figure it out. Let me try and maybe we can just fix this issue. :)

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs (hunk 3 above)
Comment (celinval) [reply src/kani-compiler/src/codegen_cprover_gotoc/codegen/intrinsic.rs:1016]: This was probably some debug I removed and forgot to revert this. I'll remove it.

File: tests/kani/Intrinsics/AlignOfVal/fixme_align_of_fat_ptr.rs (hunk 4 above)
Comment (celinval) [reply tests/kani/Intrinsics/AlignOfVal/fixme_align_of_fat_ptr.rs]: This should hold for the architecture we currently support.

**Review by adpaco-aws — APPROVED** [review]
