### PR TITLE
Use cargo locate-project

### LINKED ISSUE #717: Cargo-rmc cannot locate workspace Cargo.toml
I tried the following command line invocation:

```bash
cd src/test/cargo-rmc/simple-main/src
# Build succeed.
cargo build
# ERROR: Cannot find configuration toml at expected location: Cargo.toml
cargo rmc
```

with RMC version: 2021-12-27

I expected to see this happen: The command should work the same way as it works from the top folder. Cargo rmc should be able to locate the project Cargo.toml the same way cargo build does.

We should use `cargo locate-project` to find the correct Cargo.toml instead of trying to find it in the current directory only.

### PR DESCRIPTION
**Pull request by tedinski**
### Description of changes: 

While bumbling around trying to find the name of "this crate" I basically implemented this, so I've cleaned this up to submit separately from anything else.

### Resolved issues:

Resolves #717 

### Call-outs:

Contains a few extra cleanups and comments unrelated to headline feature.

### Testing:

* How is this change tested? existing suite. Notably not really feasible to add to our cargo-kani test suite since the way all those invocations work specifies the working directory. But it does work now to e.g. call `cargo-kani` from `src`

* Is this a refactor change? basically yes

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: src/cargo-kani/src/args_toml.rs [hunk 1]
```diff
@@ -19,6 +20,16 @@ pub fn config_toml_to_args() -> Result<Vec<OsString>> {
     }
 }
 
+/// `cargo locate-project` produces a response like:
+/// `{"root":"/full/path/to/src/cargo-kani/Cargo.toml"}`
+fn cargo_locate_project() -> Result<PathBuf> {
+    let cmd = Command::new("cargo").arg("locate-project").output()?;
```
Comment (zhassan-aws) [inline src/cargo-kani/src/args_toml.rs:26]: One option is to run `cargo locate-project` with `--message-format plain` to avoid parsing json.
```
$ pwd
/home/ubuntu/git/kani/tests/cargo-kani/config/src
$ cargo locate-project
{"root":"/home/ubuntu/git/kani/tests/cargo-kani/config/Cargo.toml"}
$ cargo locate-project --message-format plain
/home/ubuntu/git/kani/tests/cargo-kani/config/Cargo.toml
```

Comment (tedinski) [reply src/cargo-kani/src/args_toml.rs]: Done, though while debugging why everything suddenly failed (there is a newline in the bytes, oh), I realized I should update a bit of the error handling here too.

Comment (zhassan-aws) [reply src/cargo-kani/src/args_toml.rs]: Ouch!

**Review by zhassan-aws — APPROVED** [review]
