### PR TITLE
Fix infinite loop on stub resolution and improve error handling

### LINKED ISSUE #2013: Improve stub resolution error
Failure to resolve a stub source or target name is fairly generic. For the following stub:
```
#[kani::stub(orig2, self::other_crate2::mock)]
```

an error would look like:

```
error: unable to resolve function/method: crate::other_crate2::mock
```

We should be able to provide more information for the user. For example, was the problem found while trying to resolve `other_crate2` or `mock`? Ideally we should also point out where the error is with span_error. Something like the resolution errors from the compiler:

```
error: cannot find `other_crate2` in the crate root
   --> src/lib.rs:10:20
   |
10 | #[kani::stub(orig2, self::other_crate2::mock)]
   |                           ^^^^^^^^^^^^ cannot find `other_crate2` in the crate root

```

### LINKED ISSUE #2201: Name resolution falls into a cycle on local modules
I tried this code: (it's a cargo project which is attached in [resolve-cycles.tar.gz](https://github.com/model-checking/kani/files/10689942/resolve-cycles.tar.gz) for your convenience)

*src/lib.rs*
```rust
pub mod module_a;
pub mod top_module;
```

*src/module_a.rs*
```rust
mod other_mod;
pub use other_mod::*;
```

*src/top_module.rs*
```rust
use crate::module_a::*;

pub fn hello() {
    println!("hello");
}

#[cfg(kani)]
mod verification {
    use super::*;
#[kani::proof]
#[kani::stub(
    module_a::StructA::method_a,
    top_module::verification::method_a
)]

fn infinite_harness() {
    let data = StructA::method_a();
    assert!(data.field_a);
}

    fn method_a() -> StructA {
        StructA { field_a: true }
    }
}
```

*src/module_a/other_mod.rs*
```rust
use crate::module_a::*;
use crate::top_module::*;

pub (crate) struct StructA {
    pub field_a: bool,
}

impl StructA {
    #[cfg(any(test, kani))]
    pub(crate) fn method_a() -> Self {
        hello();
        Self { field_a: false }
    }
}
```

using the following command line invocation:

```
cargo kani --enable-unstable --enable-stubbing --harness verification::infinite_harness
```

with Kani version: 0.20.0 (development version - commit [a7adb0b](https://github.com/model-checking/kani/commit/a7adb0b583abb56c6f3e1255a8c2e2a043513bc3))

I expected to see this happen: Verification success, due to stubbing replacing `method_a` appropriately.

Instead, this happened: 
```
error: could not compile `resolve-cycles`; 2 warnings emitted

Caused by: Got an error from `cargo` (see below).
  process didn't exit successfully: `/home/ubuntu/kani/target/kani/bin/kani-compiler --crate-name resolve_cycles --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --reachability=harnesses -C metadata=447f54d52aae14b3 -C extra-filename=-447f54d52aae14b3 --out-dir /home/ubuntu/resolve-cycles/target/kani/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -C incremental=/home/ubuntu/resolve-cycles/target/kani/x86_64-unknown-linux-gnu/debug/incremental -L dependency=/home/ubuntu/resolve-cycles/target/kani/x86_64-unknown-linux-gnu/debug/deps -L dependency=/home/ubuntu/resolve-cycles/target/kani/debug/deps -C overflow-checks=on -C panic=abort -C symbol-mangling-version=v0 -Z unstable-options -Z panic_abort_tests=yes -Z trim-diagnostic-paths=no -Z human_readable_cgu_names -Z always-encode-mir --cfg=kani -Z 'crate-attr=feature(register_tool)' -Z 'crate-attr=register_tool(kanitool)' --sysroot /home/ubuntu/kani/target/kani -L /home/ubuntu/kani/target/kani/lib --extern kani --extern 'noprelude:std=/home/ubuntu/kani/target/kani/lib/libstd.rlib' --kani-flags` (signal: 11, SIGSEGV: invalid memory reference)
error: Failed to execute cargo (exit status: 101). Found 0 compilation errors.
```

Running with `--debug` shows that the name resolution algorithm falls into a cycle, generating an endless debug trace.
```
───0ms DEBUG kani_compiler::kani_middle::resolve Resolving `module_a::StructA::method_a` in local module `top_module::verification`
├─┐
├───┐kani_compiler::kani_middle::resolve::glob_resolution 
│   ├───0ms DEBUG kani_compiler::kani_middle::resolve Resolving `module_a::StructA::method_a` in local module `top_module`
│   ├─┐
│   ├───┐kani_compiler::kani_middle::resolve::glob_resolution 
│   │   ├───0ms DEBUG kani_compiler::kani_middle::resolve Resolving `module_a::StructA::method_a` in local module `module_a`
│   │   ├─┐
│   │   ├───┐kani_compiler::kani_middle::resolve::glob_resolution 
│   │   │   ├───0ms DEBUG kani_compiler::kani_middle::resolve Resolving `module_a::StructA::method_a` in local module `module_a::other_mod`
│   │   │   ├─┐
│   │   │   ├───┐kani_compiler::kani_middle::resolve::glob_resolution 
│   │   │   │   ├───0ms DEBUG kani_compiler::kani_middle::resolve Resolving `module_a::StructA::method_a` in local module `module_a`
│   │   │   │   ├─┐
│   │   │   │   ├───┐kani_compiler::kani_middle::resolve::glob_resolution 
│   │   │   │   │   ├───0ms DEBUG kani_compiler::kani_middle::resolve Resolving `module_a::StructA::method_a` in local module `module_a::other_mod`
[...]
```

I suspect that the culprit is #2003, although I haven't really done a proper bisection.

### PR DESCRIPTION
**Pull request by celinval**
### Description of changes: 

Refactor the name resolution code to take into consideration loops added by loops in globs. Since I had to do some refactoring, I also ensured we now the reason why the resolution failed and print it as part of the error.

### Resolved issues:

Resolves #2013 and resolves #2201

### Testing:

* How is this change tested? New tests

* Is this a refactor change? Kinda

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: kani-compiler/src/kani_middle/attributes.rs [hunk 1]
```diff
@@ -83,7 +85,10 @@ pub fn is_test_harness_closure(tcx: TyCtxt, def_id: DefId) -> bool {
 }
 
 /// Extract all Kani attributes for a given `def_id` if any exists.
+/// We only extract attributes for harnesses that are local to the current crate.
 pub fn extract_harness_attributes(tcx: TyCtxt, def_id: DefId) -> Option<HarnessAttributes> {
+    // Abort if not local.
+    def_id.as_local()?;
```
Comment (adpaco-aws) [inline kani-compiler/src/kani_middle/attributes.rs:91]: Is this to avoid attribute extraction from external code?

File: kani-compiler/src/kani_middle/resolve.rs [hunk 2]
```diff
@@ -6,426 +6,363 @@
...
-    ExternPrelude,
-    /// Indicates a path that may be local (and must be local if
-    /// `may_be_external_path` is false) and should be resolved relative to the
-    /// module identified by `id`.
-    LocalModule { id: LocalDefId, may_be_external_path: bool },
+/// Provide information about where the resolution failed.
+/// Todo: Add error message.
+pub struct ResolveError {
+    pub msg: String,
+}
```
Comment (adpaco-aws) [inline kani-compiler/src/kani_middle/resolve.rs:89]: Can we make this an `enum` with variants for each kind of error you can get? That way, all formatting (which is now done each time you construct an error) can be put in the `fmt` function.

File: kani-compiler/src/kani_middle/resolve.rs [hunk 3]
```diff
@@ -6,426 +6,363 @@
...
-/// Resolves an external path.
-fn resolve_external(tcx: TyCtxt, mut segments: Segments) -> Option<DefId> {
-    tracing::debug!("Resolving `{}` in the external prelude", segments_to_string(&segments));
-    let first = segments.pop_front().or_else(|| {
-        tracing::debug!("Unable to resolve the empty path");
-        None
-    })?;
-    for crate_num in tcx.crates(()) {
+/// Resolves an external crate name.
+fn resolve_external(tcx: TyCtxt, name: &str) -> Option<DefId> {
```
Comment (adpaco-aws) [inline kani-compiler/src/kani_middle/resolve.rs:212]: I was expecting this to return `Result<DefId, ...>`. Is there any reason to keep `Option<DefId>`?

File: kani-compiler/src/kani_middle/resolve.rs [hunk 4]
```diff
@@ -6,426 +6,363 @@
...
-        return glob_resolves.first().copied();
+    mut glob_resolutions: Vec<Res>,
+    name: &str,
+) -> Result<DefId, ResolveError> {
+    let mut visited = HashSet::<Res>::default();
+    let mut matches = vec![];
+    while let Some(res) = glob_resolutions.pop() {
+        if !visited.contains(&res) {
+            visited.insert(res);
+            let result = resolve_in_glob_use(tcx, &res, name);
```
Comment (adpaco-aws) [inline kani-compiler/src/kani_middle/resolve.rs:308]: Nice! 😄

File: kani-compiler/src/kani_middle/resolve.rs [hunk 5]
```diff
@@ -6,426 +6,363 @@
...
+            // cases (see <https://github.com/model-checking/kani/issues/2013>).
+            let location = description(tcx, current_module.to_def_id());
+            Err(ResolveError {
+                msg: format!(
+                    "`{name}` is ambiguous because of multiple glob imports in {location}. Found:\n{}",
+                    ambiguous
+                        .iter()
+                        .map(|def_id| tcx.def_path_str(*def_id))
+                        .intersperse("\n".to_string())
+                        .collect::<String>()
```
Comment (adpaco-aws) [inline kani-compiler/src/kani_middle/resolve.rs:332]: Again, an `enum` can probably help with this.

File: tests/kani/Stubbing/glob_path.rs [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+        mod_a::mod_b::mod_a::mod_b::noop();
+        panic!();
+    }
+}
+
+pub mod mod_b {
+    pub use crate::mod_a::*;
+    pub use crate::*;
+
+    /// This harness replace `method_a` which always fail by `method_b` that should always succeed.
```
Comment (adpaco-aws) [inline tests/kani/Stubbing/glob_path.rs:22]: Took me some time to understand. I'd suggest:
```suggestion
    /// This harness replaces `method_a` (always fails), by `method_b` (always succeeds).
```

File: tests/kani/Stubbing/glob_path.rs [hunk 7]
```diff
@@ -0,0 +1,31 @@
...
+    #[kani::proof]
+    #[kani::stub(mod_a::mod_b::mod_a::method_a, mod_b::noop)]
+    pub fn check_stub() {
+        method_a();
+    }
+
+    /// This method always succeed.
```
Comment (adpaco-aws) [inline tests/kani/Stubbing/glob_path.rs:29]:
```suggestion
    /// This method always succeeds.
```

File: tests/kani/Stubbing/glob_path.rs [hunk 8]
```diff
@@ -0,0 +1,31 @@
...
+// SPDX-License-Identifier: Apache-2.0 OR MIT
+//
+// kani-flags: --harness check_stub --enable-unstable --enable-stubbing
+//! Test that stub can solve glob cycles even when the path expands the cycle.
+
+pub mod mod_a {
+    pub use crate::mod_b::*;
+    pub use crate::*;
+
+    /// This method always fail.
```
Comment (adpaco-aws) [inline tests/kani/Stubbing/glob_path.rs:11]:
```suggestion
    /// This method always fails.
```

Comment (adpaco-aws) [reply tests/kani/Stubbing/glob_path.rs:11]: There are similar occurrences throughout the other tests, please take a look.

File: kani-compiler/src/kani_middle/attributes.rs (hunk 1 above)
Comment (celinval) [reply kani-compiler/src/kani_middle/attributes.rs:91]: Yes. So we don't collect a harness from a dependency.

File: kani-compiler/src/kani_middle/resolve.rs (hunk 2 above)
Comment (celinval) [reply kani-compiler/src/kani_middle/resolve.rs:89]: yeah, we could... I was just trying to do a quick hack

File: kani-compiler/src/kani_middle/resolve.rs (hunk 3 above)
Comment (celinval) [reply kani-compiler/src/kani_middle/resolve.rs:212]: Yes. I've been trying to use `Option<>` when the only possible outcomes are item was found or item was not found. I've been using result when the outcome can be also be an error.

Comment (adpaco-aws) [reply kani-compiler/src/kani_middle/resolve.rs:212]: Only brought this up because the usage in `resolve_prefix` would benefit from a `Result<T>` type. I don't feel too strong about this one, to be honest.

Comment (celinval) [reply kani-compiler/src/kani_middle/resolve.rs:212]: Gotcha... but I don't think it would work so well in `resolve_relative`. So if you don't mind I will just keep it as an `Option<>`.

Comment (adpaco-aws) [reply kani-compiler/src/kani_middle/resolve.rs:212]: Sounds good, thanks for the explanation!

**Review by adpaco-aws — APPROVED** [review]
