### PR TITLE
Expand supported crate-type check

### LINKED ISSUE #1896: Error opening file '(..)/hifitime/target/x86_64-unknown-linux-gnu/debug/deps/cbmc-linked.out'
When using Kani version 0.14.1, it fails to do a harness check:

```
╭─chris@localhost in ~/Workspace/nyx-space/hifitime on 172-fix-formal-verification ✔ (origin/172-fix-formal-verification)
╰$ cargo-kani                                                            
Error opening file '/home/chris/Workspace/nyx-space/hifitime/target/x86_64-unknown-linux-gnu/debug/deps/cbmc-linked.out'
Error: goto-cc exited with status exit status: 1

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: kani_driver::session::KaniSession::run_suppress
   2: kani_driver::call_goto_cc::<impl kani_driver::session::KaniSession>::link_goto_binary
   3: kani_driver::main
   4: std::sys_common::backtrace::__rust_begin_short_backtrace
   5: std::rt::lang_start::{{closure}}
   6: std::rt::lang_start_internal
   7: main
   8: __libc_start_call_main
   9: __libc_start_main@GLIBC_2.2.5
  10: _start

```

The issue happens with Github actions when using the provided Action, cf. https://github.com/nyx-space/hifitime/actions/runs/3466289900/jobs/5789955435 .

I'm really not too sure where to start debugging this, so let me know what I can do to help. This happens on [this commit of hifitime](https://github.com/nyx-space/hifitime/commit/e44444ebd9004e39bcd152ae773e3251cb84245b).

### LINKED ISSUE #1908: A bug in handling rlib type
I tried this code:

```rust
#[kani::proof]
fn entry() {
    assert!(1 == 2);
}
```

with Cargo.toml
```
[package]
name = "noname"
version = "0.1.0"
edition = "2021"

[lib]
name = "noname"
path = "src/lib.rs"
crate-type = ["rlib"]      // if this line is removed, the output will be the expected one.

[dependencies]
```

using the following command line invocation:

```
cargo kani
```

with Kani version: 0.15.0 (e4851c1)

I expected to see this happen
```
SUMMARY:
 ** 1 of 1 failed
Failed Checks: assertion failed: 1 == 2
 File: "/home/xxx/test/kani-test/rlib/src/lib.rs", line 3, in entry

VERIFICATION:- FAILED
Verification Time: 0.015207451s
```

Instead, this happened. `cbmc-linked.out` does not seem to be generated in the expected place.

```
Error opening file '/home/xxx/test/kani-test/rlib/target/kani/x86_64-unknown-linux-gnu/debug/deps/cbmc-linked.out'
Error: goto-cc exited with status exit status: 1

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
             at /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.66/src/error.rs:83:36
   1: kani_driver::session::KaniSession::run_suppress
             at /home/xxx/kani/kani-driver/src/session.rs:158:13
   2: kani_driver::call_goto_cc::<impl kani_driver::session::KaniSession>::link_goto_binary
             at /home/xxx/kani/kani-driver/src/call_goto_cc.rs:40:9
   3: kani_driver::cargokani_main
             at /home/xxx/kani/kani-driver/src/main.rs:71:5
   4: kani_driver::main
             at /home/xxx/kani/kani-driver/src/main.rs:34:44
   5: core::ops::function::FnOnce::call_once
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/core/src/ops/function.rs:251:5
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/std/src/sys_common/backtrace.rs:121:18
   7: std::rt::lang_start::{{closure}}
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/std/src/rt.rs:166:18
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/core/src/ops/function.rs:286:13
   9: std::panicking::try::do_call
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/std/src/panicking.rs:483:40
  10: std::panicking::try
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/std/src/panicking.rs:447:19
  11: std::panic::catch_unwind
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/std/src/panic.rs:137:14
  12: std::rt::lang_start_internal::{{closure}}
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/std/src/rt.rs:148:48
  13: std::panicking::try::do_call
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/std/src/panicking.rs:483:40
  14: std::panicking::try
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/std/src/panicking.rs:447:19
  15: std::panic::catch_unwind
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/std/src/panic.rs:137:14
  16: std::rt::lang_start_internal
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/std/src/rt.rs:148:20
  17: std::rt::lang_start
             at /rustc/1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82/library/std/src/rt.rs:165:17
  18: main
  19: __libc_start_main
             at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  20: _start
```

### PR DESCRIPTION
**Pull request by celinval**
### Description of changes: 

This change add support to `rlib` libraries and add proper error handling for crate types that aren't supported. We also no longer crash if there was no supported target found.

### Resolved issues:

Fixes #1908
Fixes #1896

### Related RFC:

N/A

### Call-outs:

- I'm being conservative on the types we currently support since types that involve native libraries trigger the linker and may result in cryptic linking errors.
- I couldn't find any easy way to make cargo only compile specific crate types, so cases where the target has at least one unsupported type, we ignore the target.

### Testing:

* How is this change tested? I added a bunch of tests

* Is this a refactor change? No

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: kani-driver/src/call_cargo.rs [hunk 1]
```diff
@@ -87,8 +87,8 @@ impl KaniSession {
         // Only joing them at the end. All kani flags must come first.
         kani_args.extend_from_slice(&rustc_args);
 
+        let mut any_target = false;
```
Comment (zpzigi754) [inline kani-driver/src/call_cargo.rs:90]: How about renaming this variable into a more readable one like `target_found` or `supported_target_found`?

Comment (celinval) [reply kani-driver/src/call_cargo.rs:90]: Yeah, that makes sense.

File: kani-driver/src/call_cargo.rs [hunk 2]
```diff
@@ -181,22 +185,81 @@ impl VerificationTarget {
...
-            } else if target.kind.contains(&String::from("lib")) {
-                Some(VerificationTarget::Lib)
-            } else if target.kind.contains(&String::from("test")) && args.tests {
-                Some(VerificationTarget::Test(target.name.clone()))
+            } else if target.kind.contains(&String::from("lib"))
+                || target.kind.contains(&String::from("rlib"))
+            {
+                // Lib targets.
+                if target.kind.iter().any(|kind| {
+                    matches!(kind.as_str(), "cdylib" | "dylib" | "staticlib" | "proc-macro")
```
Comment (zhassan-aws) [inline kani-driver/src/call_cargo.rs:217]: Can we define these strings as constants?

File: kani-driver/src/call_cargo.rs [hunk 3]
```diff
@@ -181,22 +185,81 @@ impl VerificationTarget {
...
+
+    if !ignored_libs.is_empty() {
+        // Print a warning for a lib that had at least one supported crate-types and one
+        // unsupported one.
+        println!(
+            "warning: Skipped verification of the following targets: '{}'",
+            ignored_libs.join("', '")
+        );
+        println!(
+            "    -> The targets above contained at least of one unsupported library type. \
```
Comment (zhassan-aws) [inline kani-driver/src/call_cargo.rs:247]:
```suggestion
            "    -> The targets above contained at least one unsupported library type. \
```

File: kani-driver/src/call_cargo.rs [hunk 4]
```diff
@@ -181,22 +185,81 @@ impl VerificationTarget {
...
         })
-        .collect()
+        .collect();
+
+    if !ignored_libs.is_empty() {
+        // Print a warning for a lib that had at least one supported crate-types and one
+        // unsupported one.
+        println!(
+            "warning: Skipped verification of the following targets: '{}'",
+            ignored_libs.join("', '")
```
Comment (zhassan-aws) [inline kani-driver/src/call_cargo.rs:244]: If it's not too much work, it would be useful to include in the warning the unsupported library type that this library had.

**Review by zhassan-aws — APPROVED** [review]

File: kani-driver/src/call_cargo.rs (hunk 2 above)
Comment (celinval) [reply kani-driver/src/call_cargo.rs:217]: sure

File: kani-driver/src/call_cargo.rs (hunk 4 above)
Comment (celinval) [reply kani-driver/src/call_cargo.rs:244]: Sure. Any suggestion on how this should look like? Here are a few options:
```
warning: Skipped verification of the following targets due to unsupported crate-type:
      - 'crate-name':  'cdylib'
      - 'other-crate': 'cdylib', 'staticlib'
```
I could also print on warning per crate:
```
warning: Skipped verification of `crate-name` due to unsupported crate-type: `cdylib`.
warning: Skipped verification of `other-crate` due to unsupported crate-type: `cdylib`, `staticlib`.
```

Should I also add the crate type to the verbose messages?

Comment (zhassan-aws) [reply kani-driver/src/call_cargo.rs:244]: I prefer the warning per crate version (the second one).

I think it should be OK to skip the crate type in the verbose messages because it would be a bit redundant.

Comment (celinval) [reply kani-driver/src/call_cargo.rs:244]: The verbose messages are printing crates that only have unsupported types.

Comment (celinval) [reply kani-driver/src/call_cargo.rs:244]: Actually, one per target makes total sense, since this summary would print once per package and each package can have a max of 1 lib. :)

The verbose might be nicer to keep as summary, because this gets very verbose if the package has a bunch of examples.
