### PR TITLE
Fix all remaining clippy lints

### LINKED ISSUE #1373: Clippy Compliance within Kani
As noted by @giltho & @celinval, there is a lot of clippy warnings in
Kani. This issue is for tracking compliance and tasks related to
measuring compliance.

- [x] Figure out which parts of Kani have Clippy warnings, and how many.
  - All 32 **top-level** hard errors come from `kani-compiler`.
    - This result does not conflict with people getting 100+ issues
    since these are top-level errors. Some errors may contain
    sub-errors, and we exclude all warnings.
  - When warnings are included, the breakdown is as follows.
Screen Shot 2022-07-13 at 8 27 17 PM
```js
{'library/kani': 3,
 'src': 55,
 'cprover_bindings': 17,
 'kani-driver': 6,
 'kani-compiler': 23,
 'tools/bookrunner': 5,
 'tools/compiletest': 44}
```

- [x] Add Clippy warnings to `script/kani-regressions.sh`. For now,
      explicitly ignore libraries that warnings, and incrementally
      remove them as they are fixed.

### PR DESCRIPTION
**Pull request by fzaiser**
### Description of changes: 

This fixes all the remaining clippy lints.

### Resolved issues:

Resolves #1373 

### Call-outs:

This PR adds local `#[allow(clippy::___)]` annotations in a lot of places if I think a lint is generally good to have, but does not apply in that particular instance.

This PR also globally ignores `clippy::new_without_default` because in my opinion, just because a type has a `Self::new` function, it does not always warrant a `Default` implementation.

Agreeing on this will probably involve some discussion. For reference, descriptions of each clippy lints can be found here: https://rust-lang.github.io/rust-clippy/master/

### Testing:

* How is this change tested? Clippy is run in CI.

* Is this a refactor change? Yes

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs [hunk 1]
```diff
@@ -37,8 +37,8 @@ pub struct GotocCodegenBackend {
 }
 
 impl GotocCodegenBackend {
-    pub fn new(queries: &Rc<QueryDb>) -> Box<dyn CodegenBackend> {
-        Box::new(GotocCodegenBackend { queries: Rc::clone(queries) })
+    pub fn new(queries: &Rc<QueryDb>) -> Self {
```
Comment (danielsn) [inline kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs:40]: Nice

**Review by danielsn — APPROVED** [review]

**Comment by fzaiser** [comment]
I'll keep this open for a bit, so other people can comment too, e.g. if they think some lints should not be locally or globally disabled or dealt with in a different way.

**Review by tedinski — APPROVED** [review]
