### PR TITLE
Property class comment expect fail

### LINKED ISSUE #793: Feature - Adding Property Classes Fields to Assertion Metadata
Requested feature: Add Property Classes to Assertion Metadata

Use case: 1) Allow Kani to dictate behavior and handling of different types of assertions depending on their property_class instead of handling all the assertions the same way. 
                  2) Users can query with unique assertion id's like - [main.property_class.1]

This requires changing how we codegen asserts. The symtab currently looks like - 

```json

"id": "side_effect",
"sub": [
{
"id": "symbol",
"namedSub": {
    "identifier": {
        "id": "__CPROVER_assert"
    },
    "#source_location": {
        "id": "",
        "namedSub": {
            "file": {
                "id": "/home/ubuntu/kani/library/kani/src/lib.rs"
            },
            "line": {
                "id": "86"
            },
            "column": {
                "id": "5"
            },
            "function": {
                "id": "kani::any_raw"
            },
        }
    },
    "type": {
        "id": "code",
        "namedSub": {
            "parameters": {
                "id": "",
                "sub": [
                    {
                        "id": "parameter",
                        "namedSub": {
                            "type": {
                                "id": "bool"
                            }
                        }
                    },
                    {
                        "id": "parameter",
                        "namedSub": {
                            "type": {
                                "id": "pointer",
                                "sub": [
                                    {
                                        "id": "signedbv",
                                        "namedSub": {
                                            "width": {
                                                "id": "8"
                                            }
                                        }
                                    }
                                ],
                                "namedSub": {
                                    "width": {
                                        "id": "64"
                                    }
                                }
                            }
                        }
                    }
                ]
            },
            "return_type": {
                "id": "empty"
            }
        }
    }
}
                
```

This is generated by a function that has a `function_call` statement - 

```rust
pub fn assert(cond: Expr, msg: &str, loc: Location) -> Self {
    assert!(cond.typ().is_bool());
    BuiltinFn::CProverAssert
        .call(vec![cond, Expr::string_constant(msg)], loc.clone())
        .as_stmt(loc)
}

```

This needs to be replaced by `assert` statement instead.

### PR DESCRIPTION
**Pull request by jaisnan**
### Description of changes: 

Adds Property_classes and Comment Fields to the Source Location Metadata for Expect_fail asserts only (for now). With this change, the output for the rust line - 

` kani::expect_fail(i > 20, "Blocked by assumption above.");` changes from

Before the change -
`[main.assertion.1] line 7 EXPECTED FAIL: FAILURE` 

After the change -
`[main.expect_fail.1] line 7 EXPECTED FAIL: FAILURE`

It's now possible to customize the assertion ID strings as well as control descriptions for various types of assertions (which currently default to `assertion`.

### Resolved issues:

Resolves #793

### Call-outs:

NOTE: This PR does not yet replace all the existing asserts with the new assert statements. That change shall be added in a separate PR

### Testing:

* How is this change tested?

* Is this a refactor change? Yes

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: cprover_bindings/src/goto_program/location.rs [hunk 1]
```diff
@@ -46,18 +55,49 @@ impl Location {
...
+            _ => None,
+        }
+    }
+
+    pub fn get_property_class(&self) -> Option<InternedString> {
+        match self {
+            Location::Property { property_class, .. } => *property_class,
+            _ => None,
+        }
+    }
```
Comment (tedinski) [inline cprover_bindings/src/goto_program/location.rs:84]: None of these functions appear to be used.

File: cprover_bindings/src/goto_program/location.rs [hunk 2]
```diff
@@ -46,18 +55,49 @@ impl Location {
...
+
     /// Convert a location to a short string suitable for (e.g.) logging.
     /// Goal is to return just "file:line" as clearly as possible.
     pub fn short_string(&self) -> String {
         match self {
             Location::None => "<none>".to_string(),
-            Location::BuiltinFunction { function_name, line: Some(line) } => {
+            Location::BuiltinFunction { function_name, line: Some(line), .. } => {
```
Comment (tedinski) [inline cprover_bindings/src/goto_program/location.rs:91]: There are multiple locations in the PR where you're adding dots to patterns, and these appear to be remnants of a previous version of the PR. Please fix them all.

File: cprover_bindings/src/irep/to_irep.rs [hunk 3]
```diff
@@ -347,7 +360,15 @@ impl ToIrep for Parameter {
 
 impl ToIrep for Stmt {
     fn to_irep(&self, mm: &MachineModel) -> Irep {
-        self.body().to_irep(mm).with_location(self.location(), mm)
+        // Match Assert in Stmt to add fields to Source Location Irep
```
Comment (tedinski) [inline cprover_bindings/src/irep/to_irep.rs:363]: Needs better comment to explain what's going on here.

**Review by tedinski — CHANGES_REQUESTED** [review]
I'm having a hard time being sure about this just from reviewing on Github, but it seems like your PR has two conflicting strategies for adding property class information.

1. Adds `Property` as a `Location`, and ensures that an `Assert` has such a `Location`. Consequently, things should just work.
2. Special-casing `Assert` in `to_irep` for `Stmt`, to inject the property class info with `with_assert_properties`.

It does not seem to me that both are necessary? Seems like you implemented things both ways but only one is actually being used.

File: cprover_bindings/src/irep/to_irep.rs (hunk 3 above)
Comment (jaisnan) [reply cprover_bindings/src/irep/to_irep.rs:363]: sure

File: cprover_bindings/src/goto_program/stmt.rs [hunk 4]
```diff
@@ -184,6 +221,34 @@ impl Stmt {
...
+            )
+        } else {
+            loc
+        };
+
+        stmt!(Assert { cond, property_class, msg }, property_location)
+    }
+
     /// `__CPROVER_assert(cond, msg);`
     pub fn assert(cond: Expr, msg: &str, loc: Location) -> Self {
```
[the remark this answers is not in the document]
Comment (jaisnan) [reply cprover_bindings/src/goto_program/stmt.rs:253]: It should be removed, and replaced with the new assert.

File: cprover_bindings/src/goto_program/stmt.rs [hunk 5]
```diff
@@ -184,6 +221,34 @@ impl Stmt {
...
+            Location::property_location(
+                file,
+                function,
+                line,
+                col,
+                Some(message.into()),
+                Some(property_class.as_str().to_string().intern()),
+            )
+        } else {
+            loc
```
[the remark this answers is not in the document]
Comment (jaisnan) [reply cprover_bindings/src/goto_program/stmt.rs:246]: sure, makes sense

File: cprover_bindings/src/goto_program/location.rs [hunk 6]
```diff
@@ -14,6 +14,15 @@ pub enum Location {
...
     /// `function` is `None` for global, `Some(function_name)` for function local.
     Loc { file: InternedString, function: Option<InternedString>, line: u64, col: Option<u64> },
+    /// Location for Statements that use Property Class and Description - Assert, Assume, Cover etc.
+    Property {
+        file: InternedString,
+        function: Option<InternedString>,
+        line: u64,
+        col: Option<u64>,
+        comment: Option<InternedString>,
+        property_class: Option<InternedString>,
```
[the remark this answers is not in the document]
Comment (jaisnan) [reply cprover_bindings/src/goto_program/location.rs:24]: Yes, that is what makes it a Property and since they're key to the variant, I'll make them mandatory.

**Comment by tedinski** [comment]
Fair enough.

@celinval ? I think I like the adding the `Property` variant to the `Location` enum. It's a little weird, but having to treat locations non-uniformly (`to_irep`) I think is worse. Your thoughts?

(BTW, @jaisnan : have you audited all other places that pattern matches on locations? If we add a new variant like this, we need to make sure we don't break some code elsewhere that might have made an assumption like you did that the `Location` would be a `Loc`.)

File: cprover_bindings/src/goto_program/location.rs (hunk 2 above)
Comment (jaisnan) [reply cprover_bindings/src/goto_program/location.rs:91]: Yup, thanks for spotting these.

**Comment by jaisnan** [comment]
> Fair enough.
> 
> @celinval ? I think I like the adding the `Property` variant to the `Location` enum. It's a little weird, but having to treat locations non-uniformly (`to_irep`) I think is worse. Your thoughts?
> 
> (BTW, @jaisnan : have you audited all other places that pattern matches on locations? If we add a new variant like this, we need to make sure we don't break some code elsewhere that might have made an assumption like you did that the `Location` would be a `Loc`.)

I agree, it's less intuitive than adding fields onto the irep's at the last step feels more hacky. Since we intent to add properties to cover and assume as well, we would be better off just adding a new variant for such statement locations imo.

I think I did do a basic pass to audit but I don't quite remember at what point of development. I can do another check.

File: cprover_bindings/src/goto_program/stmt.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (celinval) [reply cprover_bindings/src/goto_program/stmt.rs:246]: +1. This should at least work with the new Location type you created.

File: cprover_bindings/src/goto_program/location.rs [hunk 7]
```diff
@@ -81,6 +121,27 @@ impl Location {
         Location::Loc { file, function, line, col }
     }
 
+    pub fn property_location<T, U: Into<InternedString>, V: Into<InternedString>>(
+        file: U,
+        function: Option<V>,
+        line: T,
+        col: Option<T>,
+        comment: Option<U>,
+        property_name: Option<U>,
```
Comment (celinval) [inline cprover_bindings/src/goto_program/location.rs:130]: IMO, we should either keep this function simple or flexible. This implementation is neither. You should either add a 4th parameter here (like `X: Into<InternedString>`) or just keep them all as one type. I.e.:  `pub fn property_location<T, U: Into<InternedString>>`

File: cprover_bindings/src/goto_program/stmt.rs [hunk 8]
```diff
@@ -21,6 +21,37 @@ use tracing::debug;
 ///     `while (c) {stmt1, stmt2}`
 ///      would translate to `Stmt::while_loop(c, vec![stmt1, stmt2], loc)`
 /// Statements can also be created using the converters in the `Expr` module.
+///
+#[derive(Copy, Debug, Clone)]
+pub enum PropertyClass {
```
Comment (celinval) [inline cprover_bindings/src/goto_program/stmt.rs:26]: I like the idea of having an enum, but this code should live inside kani-compiler codegen module.

**Review by celinval — COMMENTED** [review]
Maybe next time publish 2 PRs to compare the approaches. It's a bit hard to figure out what is needed for each.

Overall, I also prefer the new Location variant.

File: cprover_bindings/src/goto_program/stmt.rs (hunk 8 above)
Comment (tedinski) [reply cprover_bindings/src/goto_program/stmt.rs:26]: A bit hard to do that when the `Location` type its used in is in `cprover_bindings`. IMO leave it, it's certainly not the only "Kani thing" in this crate.

Comment (celinval) [reply cprover_bindings/src/goto_program/stmt.rs:26]: This shouldn't be hard though. The Location should still work over strings since the CProver API accepts any string.

Codegen module should have a method that builds the property correctly from the `enum` value.

Comment (tedinski) [reply cprover_bindings/src/goto_program/stmt.rs:26]: Ah, right, fair.

File: cprover_bindings/src/goto_program/location.rs (hunk 7 above)
Comment (jaisnan) [reply cprover_bindings/src/goto_program/location.rs:130]: Will do!

File: cprover_bindings/src/goto_program/stmt.rs (hunk 8 above)
Comment (jaisnan) [reply cprover_bindings/src/goto_program/stmt.rs:26]: Will move it to codegen

Comment (jaisnan) [reply cprover_bindings/src/goto_program/stmt.rs:26]: Tried moving to codegen but it presented problems for the assert_stmt implementation. As the Assert is ultimately a Stmt and the StmtBody needs to be implemented, we need to retain the enum in the stmt.rs file.

Would refactoring this later be acceptable @celinval ?

File: cprover_bindings/src/goto_program/location.rs [hunk 9]
```diff
@@ -14,6 +14,15 @@ pub enum Location {
     /// Location in user code.
     /// `function` is `None` for global, `Some(function_name)` for function local.
     Loc { file: InternedString, function: Option<InternedString>, line: u64, col: Option<u64> },
+    /// Location for Statements that use Property Class and Description - Assert, Assume, Cover etc.
```
Comment (danielsn) [inline cprover_bindings/src/goto_program/location.rs:17]: What happens if a "property" location is put on a non property statement?

File: cprover_bindings/src/goto_program/location.rs [hunk 10]
```diff
@@ -81,6 +93,68 @@ impl Location {
         Location::Loc { file, function, line, col }
     }
 
+    pub fn property_location<T, U: Into<InternedString>>(
```
Comment (danielsn) [inline cprover_bindings/src/goto_program/location.rs:96]: Move the constraint on `U` into the `where` clause

Comment (jaisnan) [reply cprover_bindings/src/goto_program/location.rs:96]: Sure

File: src/kani-compiler/src/codegen_cprover_gotoc/overrides/hooks.rs [hunk 11]
```diff
@@ -98,13 +98,20 @@ impl<'tcx> GotocHook<'tcx> for ExpectFail {
         assert_eq!(fargs.len(), 2);
         let target = target.unwrap();
         let cond = fargs.remove(0).cast_to(Type::bool());
-        // add "EXPECTED FAIL" to the message because compiletest relies on it
+        //TODO: actually use the error message passed by the user.
```
Comment (tedinski) [inline src/kani-compiler/src/codegen_cprover_gotoc/overrides/hooks.rs:101]: slightly confused by this TODO

File: cprover_bindings/src/irep/to_irep.rs [hunk 12]
```diff
@@ -323,12 +323,25 @@ impl ToIrep for Location {
                 (IrepId::Function, Irep::just_string_id(function_name.to_string())),
             ])
             .with_named_sub_option(IrepId::Line, line.map(Irep::just_int_id)),
-            Location::Loc { file, function, line, col } => Irep::just_named_sub(vector_map![
+            Location::Loc { file, function, line, col, .. } => Irep::just_named_sub(vector_map![
```
[the remark this answers is not in the document]
Comment (jaisnan) [reply cprover_bindings/src/irep/to_irep.rs:326]: Yeah, my bad. I removed these and reverted my commit and forgot to remove them again.

File: cprover_bindings/src/goto_program/location.rs [hunk 13]
```diff
@@ -81,6 +93,69 @@ impl Location {
...
+        let file = file.unwrap().into();
+        let line = line.try_into().unwrap();
+        let col = col.map(|x| x.try_into().unwrap());
+        let function = function.intern();
+        let property_class = property_name.into();
+        let comment = comment.into();
+        Location::Property { file, function, line, col, comment, property_class }
+    }
+
+    // Create a Property type Location from an already existing Location type
```
[the remark this answers is not in the document]
Comment (jaisnan) [reply cprover_bindings/src/goto_program/location.rs:118]: Will keep that in mind although I didn't intend this to be a doc comment. When do we want to place doc comment vs regular comment, is there any guidelines that we follow for that?

File: cprover_bindings/src/goto_program/location.rs [hunk 14]
```diff
@@ -81,6 +93,69 @@ impl Location {
...
+    pub fn create_location<T: Into<InternedString>>(
+        comment: T,
+        property_name: T,
```
[the remark this answers is not in the document]
Comment (jaisnan) [reply cprover_bindings/src/goto_program/location.rs:121]: Yes. I can reshape all of this to use the enum and remove the above constructor

File: cprover_bindings/src/goto_program/stmt.rs [hunk 15]
```diff
@@ -184,6 +221,24 @@ impl Stmt {
...
+    ) -> Self {
+        assert!(cond.typ().is_bool());
+
+        let property_name = property_class.as_str().to_string().intern();
+        let msg = message.into();
+
+        // Create a Property Location Variant from any given Location type
+        let property_location = Location::create_location(msg, property_name, loc);
+
+        stmt!(Assert { cond, property_class, msg }, property_location)
```
[the remark this answers is not in the document]
Comment (jaisnan) [reply cprover_bindings/src/goto_program/stmt.rs:239]: I think it makes sense logically although it does seem like replication of data. Not sure what the correct approach is either.

File: src/kani-compiler/src/codegen_cprover_gotoc/overrides/hooks.rs (hunk 11 above)
Comment (jaisnan) [reply src/kani-compiler/src/codegen_cprover_gotoc/overrides/hooks.rs:101]: Yeah, this todo is now redundant

**Comment by jaisnan** [comment]
Revision : 

1. Separated out the PropertyClass Enum to codegen crate.
2. Converted all references to the enum to use `InternedString` instead.

File: cprover_bindings/src/goto_program/location.rs (hunk 14 above)
[the remark this answers is not in the document]
Comment (jaisnan) [reply cprover_bindings/src/goto_program/location.rs:122]: Since we've removed the Enum, I'm marking this as resolved.

File: cprover_bindings/src/goto_program/stmt.rs (hunk 15 above)
[the remark this answers is not in the document]
Comment (jaisnan) [reply cprover_bindings/src/goto_program/stmt.rs]: Kept the same structure, imo this is an easy way to mandate the new fields in everyplace where we're going to use the new Assert.

File: cprover_bindings/src/goto_program/location.rs [hunk 16]
```diff
@@ -58,6 +67,9 @@ impl Location {
                 format!("<{}>", function_name)
             }
             Location::Loc { file, line, .. } => format!("{}:{}", file, line),
+            Location::Property { property_class, comment, .. } => {
+                format!("{:?}:{:?}", property_class, comment)
```
Comment (tedinski) [inline cprover_bindings/src/goto_program/location.rs:71]: this should be file and line too

File: cprover_bindings/src/goto_program/location.rs [hunk 17]
```diff
@@ -81,6 +93,57 @@ impl Location {
...
+        let line = line.try_into().unwrap();
+        let col = col.map(|x| x.try_into().unwrap());
+        let function = function.intern();
+        let property_class = property_name.into();
+        let comment = comment.into();
+        Location::Property { file, function, line, col, comment, property_class }
+    }
+
+    /// Create a Property type Location from an already existing Location type
+    pub fn create_location<T: Into<InternedString>>(
```
Comment (tedinski) [inline cprover_bindings/src/goto_program/location.rs:120]: This function need a better name. `with_property`? Change the final `location` to an initial `&self`?

File: src/kani-compiler/src/codegen_cprover_gotoc/codegen/assert.rs [hunk 18]
```diff
@@ -0,0 +1,58 @@
...
+        match self {
+            PropertyClass::ExpectFail => "expect_fail",
+            PropertyClass::UnsupportedStructs => "unsupported_struct",
+            PropertyClass::DefaultAssertion => "assertion",
+        }
+    }
+}
+
+impl<'tcx> GotocCtx<'tcx> {
+    pub fn codegen_assert(
```
Comment (tedinski) [inline src/kani-compiler/src/codegen_cprover_gotoc/codegen/assert.rs:42]: This looks good.

File: src/kani-compiler/src/codegen_cprover_gotoc/overrides/hooks.rs [hunk 19]
```diff
@@ -98,13 +99,19 @@ impl<'tcx> GotocHook<'tcx> for ExpectFail {
         assert_eq!(fargs.len(), 2);
         let target = target.unwrap();
         let cond = fargs.remove(0).cast_to(Type::bool());
-        // add "EXPECTED FAIL" to the message because compiletest relies on it
+
+        // msg is the comment field that's set on source location which is presented as the Description field
```
Comment (tedinski) [inline src/kani-compiler/src/codegen_cprover_gotoc/overrides/hooks.rs:103]: I'd just remove the comments in this function. I don't think they're adding anything?

But you removed a comment that maybe still is: we're adding "EXPECTED FAIL" because of compiletest. We shouldn't lose that comment until we fix compiletest (or our own output formatter?) to handle the `expect_fail` property class correctly.

**Review by tedinski — COMMENTED** [review]
almost there, looking pretty good

File: cprover_bindings/src/goto_program/location.rs (hunk 17 above)
Comment (jaisnan) [reply cprover_bindings/src/goto_program/location.rs:120]: Yup, will do

File: src/kani-compiler/src/codegen_cprover_gotoc/overrides/hooks.rs (hunk 19 above)
Comment (jaisnan) [reply src/kani-compiler/src/codegen_cprover_gotoc/overrides/hooks.rs:103]: cool, i'll add it back

File: cprover_bindings/src/goto_program/location.rs [hunk 20]
```diff
@@ -58,6 +67,9 @@ impl Location {
                 format!("<{}>", function_name)
             }
             Location::Loc { file, line, .. } => format!("{}:{}", file, line),
+            Location::Property { property_class, comment, file, line, .. } => {
+                format!("{:?}:{:?},{:?}:{:?}", property_class, comment, file, line)
```
Comment (tedinski) [inline cprover_bindings/src/goto_program/location.rs:71]: I'm fairly certain, given this function's comment, this should only be printing the file/line.

**Review by tedinski — APPROVED** [review]
One thing to fix then lgtm
