### PR TITLE
Fix description updates for missing function properties

### LINKED ISSUE #1424: Missing function assertions aren't generating useful failure messages
```
Failed check: assertion
```

Should state what function and that it is missing.

### PR DESCRIPTION
**Pull request by adpaco-aws**
### Description of changes: 

Changes the conditions to determine whether a property corresponds to a missing function definition. Updates the related UI tests.

### Resolved issues:

Resolves #1424 #1271 

### Testing:

* How is this change tested? Existing regression. The tests have been updated with stronger requirements.

* Is this a refactor change? No.

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: kani-driver/src/cbmc_output_parser.rs [hunk 1]
```diff
@@ -816,9 +815,9 @@ fn has_check_failure(properties: &Vec<Property>, description: &str) -> bool {
 fn modify_undefined_function_checks(mut properties: Vec<Property>) -> (Vec<Property>, bool) {
     let mut has_unknown_location_checks = false;
     for mut prop in &mut properties {
-        if prop.description.contains(ASSERTION_FALSE)
-            && extract_property_class(prop).unwrap() == DEFAULT_ASSERTION
+        if prop.description == DEFAULT_ASSERTION
             && prop.source_location.file.is_none()
+            && prop.source_location.function.is_some()
         {
             prop.description = "Function with missing definition is unreachable".to_string();
```
Comment (celinval) [inline kani-driver/src/cbmc_output_parser.rs:822]: It looks like the propery_id as well as the location include the name of the missing function. Can we use that to print a nicer error message? The only issue is that the name is mangled. :(

**Review by celinval — COMMENTED** [review]
Just one comment. Thanks

File: kani-driver/src/cbmc_output_parser.rs (hunk 1 above)
Comment (tedinski) [reply kani-driver/src/cbmc_output_parser.rs]: It's rust code now. Demangle? e.g. https://crates.io/crates/rustc-demangle

Comment (adpaco-aws) [reply kani-driver/src/cbmc_output_parser.rs]: Thanks for the suggestion! AFAIK we can use `rustc-demangle` to demangle the name. For some reason, demangling works only partially for missing function definitions, but still provides a nice result:

Screen Shot 2022-08-12 at 13 09 09

I could also rebuild the property name with the demangled function name in #1514. Can you review this PR again?

File: kani-driver/Cargo.toml [hunk 2]
```diff
@@ -24,6 +24,7 @@ clap = "2.34"
 glob = "0.3"
 toml = "0.5"
 regex = "1.6"
+rustc-demangle = { version = "0.1.21" }
```
Comment (fzaiser) [inline kani-driver/Cargo.toml:27]: Why not just
```suggestion
rustc-demangle = "0.1.21"
```

File: tests/ui/missing-function/rust-by-example-description/expected [hunk 3]
```diff
@@ -1,2 +1,4 @@
 Status: FAILURE\
-Description: "assertion"
+Description: "Function
```
Comment (fzaiser) [inline tests/ui/missing-function/rust-by-example-description/expected:2]: Why not add the name of the function as well, to ensure that the demangling works corectly?

Comment (adpaco-aws) [reply tests/ui/missing-function/rust-by-example-description/expected]: Maybe I'm mistaken, but I was under the impression that mangled names may change across different versions of the compiler. But you're right, let's add it and we'll remove if that's the case in future toolchain updates.

Comment (adpaco-aws) [reply tests/ui/missing-function/rust-by-example-description/expected]: CI failed because the last (mangled) part is not consistent across different platforms. Went back to two lines but the first one includes the demangled part of the function name.

File: kani-driver/src/cbmc_output_parser.rs [hunk 4]
```diff
@@ -811,16 +812,24 @@ fn has_check_failure(properties: &Vec<Property>, description: &str) -> bool {
...
+            // Missing functions come with mangled names. `demangle` produces
+            // the demangled version if it's a mangled name, but for some reason
+            // the name is not being fully demangled. For example:
+            //
+            // function: _ZN60_$LT$alloc..string..String$u20$as$u20$core..clone..Clone$GT$5clone17h830b64d2ac32f613E
+            // demangle(function): <alloc::string::String as core::clone::Clone>::clone::h830b64d2ac32f613
+            //
+            // Note the last part, which doesn't appear to be demangled.
+            // Still, it's more readable than the mangled name.
+            let modified_description = format!("Function {} with missing definition is unreachable", demangle(function));
```
Comment (fzaiser) [inline kani-driver/src/cbmc_output_parser.rs:831]: Can you try `{:#}` instead of `{}`? I think the alternative formatting of `Demangle` should omit the hash at the end, which avoids the platform differences. I believe with that change, you can add the whole line to the `expected` files.

Comment (fzaiser) [reply kani-driver/src/cbmc_output_parser.rs:831]: `rustfilt` does something similar: https://github.com/luser/rustfilt/blob/3c81f107b73fdcf7bbb98b426c1214f15946ec90/src/main.rs#L47

File: tests/ui/missing-function/rust-by-example-description/expected (hunk 3 above)
Comment (fzaiser) [reply tests/ui/missing-function/rust-by-example-description/expected]: Thanks! I think you can get rid of the hash at the end tho, see below.

File: kani-driver/src/cbmc_output_parser.rs (hunk 4 above)
Comment (adpaco-aws) [reply kani-driver/src/cbmc_output_parser.rs]: Thanks @fzaiser, that did the trick!

File: kani-driver/src/cbmc_output_parser.rs [hunk 5]
```diff
@@ -811,16 +812,24 @@ fn has_check_failure(properties: &Vec<Property>, description: &str) -> bool {
...
+            // Missing functions come with mangled names. `demangle` produces
+            // the demangled version if it's a mangled name, but for some reason
+            // the name is not being fully demangled. For example:
+            //
+            // function: _ZN60_$LT$alloc..string..String$u20$as$u20$core..clone..Clone$GT$5clone17h830b64d2ac32f613E
+            // demangle(function): <alloc::string::String as core::clone::Clone>::clone::h830b64d2ac32f613
+            //
+            // Note the last part, which doesn't appear to be demangled.
+            // Still, it's more readable than the mangled name.
+            let modified_description = format!("Function {:#} with missing definition is unreachable", demangle(function));
```
Comment (celinval) [inline kani-driver/src/cbmc_output_parser.rs:831]: nit: can you add quotes around the name of the function?

**Review by celinval — APPROVED** [review]
That looks much nicer! Just one little comment.

**Review by tedinski — APPROVED** [review]
Woo!
