### PR TITLE
Join and format warnings about concurrent constructs

### LINKED ISSUE #1460: Kani should not print warnings about concurrency primitives (as long as it's single-threaded)
As mentioned in https://github.com/model-checking/kani/pull/1452#discussion_r938945779, users will often be greeted by messages of the form `Kani does not support concurrency for now. `{}` in {} treated as a sequential operation.`. For instance, if you're compiling tokio, you get the following output:

<details>

```
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_fence_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3305 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_fence_release` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3306 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_fence_acqrel` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3307 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_fence_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3308 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2960 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2961 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2962 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_relaxed_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3028 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_relaxed_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3030 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_relaxed_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3032 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acquire_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3033 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acquire_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3034 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acquire_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3036 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_release_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3037 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_release_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3039 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_release_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3041 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acqrel_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3042 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acqrel_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3043 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acqrel_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3045 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_seqcst_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3046 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_seqcst_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3047 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_seqcst_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3048 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <<std::sync::Mutex<T> as std::fmt::Debug>::fmt::LockedPlaceholder as std::fmt::Debug>::fmt, attempted lookup for symbol name: _ZN129_$LT$$LT$std..sync..mutex..Mutex$LT$T$GT$$u20$as$u20$core..fmt..Debug$GT$..fmt..LockedPlaceholder$u20$as$u20$core..fmt..Debug$GT$3fmt17hfa13453a5ad73070E
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&usize as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRjNtB5_5Debug3fmtCsb2tXkiy4HHk_6memchr
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <futures_io::Error as std::fmt::Debug>::fmt, attempted lookup for symbol name: _ZN58_$LT$std..io..error..Error$u20$as$u20$core..fmt..Debug$GT$3fmt17h57fbb5ea577dca77E
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::thread::AccessError as std::fmt::Debug>::fmt, attempted lookup for symbol name: _ZN68_$LT$std..thread..local..AccessError$u20$as$u20$core..fmt..Debug$GT$3fmt17h3d116f9f58b0e37fE
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <tokio::loom::std::atomic_usize::AtomicUsize as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXs3_NtNtNtCs43oGvCTZBYr_5tokio4loom3std12atomic_usizeNtB5_11AtomicUsizeNtNtCs4YygHDVoDdI_4core3fmt5Debug3fmt
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <tokio::sync::task::atomic_waker::AtomicWaker as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXs2_NtNtNtCs43oGvCTZBYr_5tokio4sync4task12atomic_wakerNtB5_11AtomicWakerNtNtCs4YygHDVoDdI_4core3fmt5Debug3fmt
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&str as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtReNtB5_5Debug3fmtCs4DXZRR6gaHf_3log
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_fence_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3305 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_fence_release` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3306 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_fence_acqrel` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3307 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_fence_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3308 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2960 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2961 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2962 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_relaxed_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3028 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_relaxed_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3030 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_relaxed_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3032 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acquire_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3033 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acquire_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3034 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acquire_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3036 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_release_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3037 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_release_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3039 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_release_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3041 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acqrel_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3042 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acqrel_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3043 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acqrel_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3045 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_seqcst_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3046 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_seqcst_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3047 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_seqcst_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3048 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::error::<impl std::convert::From<std::string::String> for std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>::from::StringError as std::fmt::Debug>::fmt, attempted lookup for symbol name: _ZN242_$LT$std..error..$LT$impl$u20$core..convert..From$LT$alloc..string..String$GT$$u20$for$u20$alloc..boxed..Box$LT$dyn$u20$std..error..Error$u2b$core..marker..Sync$u2b$core..marker..Send$GT$$GT$..from..StringError$u20$as$u20$core..fmt..Debug$GT$3fmt17h596233209d8b7714E
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::error::<impl std::convert::From<std::string::String> for std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>::from::StringError as std::fmt::Display>::fmt, attempted lookup for symbol name: _ZN244_$LT$std..error..$LT$impl$u20$core..convert..From$LT$alloc..string..String$GT$$u20$for$u20$alloc..boxed..Box$LT$dyn$u20$std..error..Error$u2b$core..marker..Sync$u2b$core..marker..Send$GT$$GT$..from..StringError$u20$as$u20$core..fmt..Display$GT$3fmt17h3109561963b528c8E
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::error::<impl std::convert::From<std::string::String> for std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>::from::StringError as std::error::Error>::source, attempted lookup for symbol name: _RNvYNtNvXs1_NtCsfcET2xiHyR1_3std5errorINtNtCsbutnkbugfxH_5alloc5boxed3BoxDNtBa_5ErrorNtNtCs4YygHDVoDdI_4core6marker4SyncNtB1n_4SendEL_EINtNtB1p_7convert4FromNtNtBF_6string6StringE4from11StringErrorB1a_6sourceCs9FYAfFSAVYQ_3mio
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::error::<impl std::convert::From<std::string::String> for std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>::from::StringError as std::error::Error>::type_id, attempted lookup for symbol name: _RNvYNtNvXs1_NtCsfcET2xiHyR1_3std5errorINtNtCsbutnkbugfxH_5alloc5boxed3BoxDNtBa_5ErrorNtNtCs4YygHDVoDdI_4core6marker4SyncNtB1n_4SendEL_EINtNtB1p_7convert4FromNtNtBF_6string6StringE4from11StringErrorB1a_7type_idCs9FYAfFSAVYQ_3mio
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::error::<impl std::convert::From<std::string::String> for std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>::from::StringError as std::error::Error>::backtrace, attempted lookup for symbol name: _RNvYNtNvXs1_NtCsfcET2xiHyR1_3std5errorINtNtCsbutnkbugfxH_5alloc5boxed3BoxDNtBa_5ErrorNtNtCs4YygHDVoDdI_4core6marker4SyncNtB1n_4SendEL_EINtNtB1p_7convert4FromNtNtBF_6string6StringE4from11StringErrorB1a_9backtraceCs9FYAfFSAVYQ_3mio
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::error::<impl std::convert::From<std::string::String> for std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>::from::StringError as std::error::Error>::description, attempted lookup for symbol name: _ZN243_$LT$std..error..$LT$impl$u20$core..convert..From$LT$alloc..string..String$GT$$u20$for$u20$alloc..boxed..Box$LT$dyn$u20$std..error..Error$u2b$core..marker..Sync$u2b$core..marker..Send$GT$$GT$..from..StringError$u20$as$u20$std..error..Error$GT$11description17hf765c17a6ae77acfE
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::error::<impl std::convert::From<std::string::String> for std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>::from::StringError as std::error::Error>::cause, attempted lookup for symbol name: _RNvYNtNvXs1_NtCsfcET2xiHyR1_3std5errorINtNtCsbutnkbugfxH_5alloc5boxed3BoxDNtBa_5ErrorNtNtCs4YygHDVoDdI_4core6marker4SyncNtB1n_4SendEL_EINtNtB1p_7convert4FromNtNtBF_6string6StringE4from11StringErrorB1a_5causeCs9FYAfFSAVYQ_3mio
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::error::<impl std::convert::From<std::string::String> for std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>::from::StringError as std::error::Error>::provide, attempted lookup for symbol name: _RNvYNtNvXs1_NtCsfcET2xiHyR1_3std5errorINtNtCsbutnkbugfxH_5alloc5boxed3BoxDNtBa_5ErrorNtNtCs4YygHDVoDdI_4core6marker4SyncNtB1n_4SendEL_EINtNtB1p_7convert4FromNtNtBF_6string6StringE4from11StringErrorB1a_7provideCs9FYAfFSAVYQ_3mio
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&std::vec::Vec<u8> as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRINtNtCsbutnkbugfxH_5alloc3vec3VechENtB5_5Debug3fmtCs43oGvCTZBYr_5tokio
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&std::time::Duration as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRNtNtB7_4time8DurationNtB5_5Debug3fmtCsaQ5MVki7BDy_7socket2
warning: Found the following unsupported constructs:
             - Rvalue::ThreadLocalRef (6)
             - drop_in_place for drop_unimplemented__RINvNtCs4YygHDVoDdI_4core3ptr13drop_in_placeNtNtNtNtCs43oGvCTZBYr_5tokio4sync4task12atomic_waker11AtomicWakerEBO_ (1)
         
         Verification will fail if one or more of these constructs is reachable.
         See https://model-checking.github.io/kani/rust-feature-support.html for more details.

WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&usize as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRjNtB5_5Debug3fmtCs43Jws2ifaqL_15futures_channel
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&bool as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRbNtB5_5Debug3fmtCs43Jws2ifaqL_15futures_channel
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&std::vec::Vec<u8> as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRINtNtCsbutnkbugfxH_5alloc3vec3VechENtB5_5Debug3fmtCs43oGvCTZBYr_5tokio
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&futures_io::Error as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRNtNtNtCsfcET2xiHyR1_3std2io5error5ErrorNtB5_5Debug3fmtCs43oGvCTZBYr_5tokio
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&() as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRuNtB5_5Debug3fmtCs4ve6hHYRnOw_16parking_lot_core
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&bytes::BytesMut as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRNtNtCshtrNijB0EoG_5bytes9bytes_mut8BytesMutNtB5_5Debug3fmtCs43oGvCTZBYr_5tokio
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&std::option::Option<usize> as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRINtNtB7_6option6OptionjENtB5_5Debug3fmtCsb2tXkiy4HHk_6memchr
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::sync::Arc<tokio::sync::Semaphore> as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsE_NtCsbutnkbugfxH_5alloc4syncINtB5_3ArcNtNtNtCs43oGvCTZBYr_5tokio4sync9semaphore9SemaphoreENtNtCs4YygHDVoDdI_4core3fmt5Debug3fmtBM_
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&u64 as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRyNtB5_5Debug3fmtCsb2tXkiy4HHk_6memchr
warning: Found the following unsupported constructs:
             - Rvalue::ThreadLocalRef (7)
             - drop_in_place for drop_unimplemented__RINvNtCs4YygHDVoDdI_4core3ptr13drop_in_placeNtNtNtCsfcET2xiHyR1_3std2io5error5ErrorECs9FYAfFSAVYQ_3mio (1)
             - try (1)
         
         Verification will fail if one or more of these constructs is reachable.
         See https://model-checking.github.io/kani/rust-feature-support.html for more details.

warning: `tokio-test` (lib) generated 1 warning
warning: `tokio-util` (lib) generated 4 warnings
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&u32 as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRmNtB5_5Debug3fmtCs4DXZRR6gaHf_3log
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&() as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRuNtB5_5Debug3fmtCs4ve6hHYRnOw_16parking_lot_core
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&&str as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRReNtB5_5Debug3fmtCs4DXZRR6gaHf_3log
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&u8 as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRhNtB5_5Debug3fmtCsb2tXkiy4HHk_6memchr
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&i32 as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRlNtB5_5Debug3fmtCse9dO0SfHQET_4libc
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&std::option::Option<usize> as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRINtNtB7_6option6OptionjENtB5_5Debug3fmtCsb2tXkiy4HHk_6memchr
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&bool as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRbNtB5_5Debug3fmtCs4ve6hHYRnOw_16parking_lot_core
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&std::option::Option<u32> as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRINtNtB7_6option6OptionmENtB5_5Debug3fmtCs4DXZRR6gaHf_3log
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::thread::AccessError as std::fmt::Debug>::fmt, attempted lookup for symbol name: _ZN68_$LT$std..thread..local..AccessError$u20$as$u20$core..fmt..Debug$GT$3fmt17h3d116f9f58b0e37fE
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::cell::BorrowError as std::fmt::Debug>::fmt, attempted lookup for symbol name: _ZN60_$LT$core..cell..BorrowError$u20$as$u20$core..fmt..Debug$GT$3fmt17h4c4d5842ef5efbd5E
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::cell::BorrowMutError as std::fmt::Debug>::fmt, attempted lookup for symbol name: _ZN63_$LT$core..cell..BorrowMutError$u20$as$u20$core..fmt..Debug$GT$3fmt17h8a41a0130d49cfbdE
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::string::FromUtf8Error as std::fmt::Debug>::fmt, attempted lookup for symbol name: _ZN65_$LT$alloc..string..FromUtf8Error$u20$as$u20$core..fmt..Debug$GT$3fmt17h3948c6a593737b3aE
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::ffi::NulError as std::fmt::Debug>::fmt, attempted lookup for symbol name: _ZN64_$LT$alloc..ffi..c_str..NulError$u20$as$u20$core..fmt..Debug$GT$3fmt17h18e4eb7c84a81c03E
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::io::Error as std::fmt::Debug>::fmt, attempted lookup for symbol name: _ZN58_$LT$std..io..error..Error$u20$as$u20$core..fmt..Debug$GT$3fmt17h57fbb5ea577dca77E
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <! as std::fmt::Debug>::fmt, attempted lookup for symbol name: _ZN42_$LT$$u21$$u20$as$u20$core..fmt..Debug$GT$3fmt17h7731a922cd7e8301E
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <std::num::TryFromIntError as std::fmt::Debug>::fmt, attempted lookup for symbol name: _ZN70_$LT$core..num..error..TryFromIntError$u20$as$u20$core..fmt..Debug$GT$3fmt17h699ff305d5b9c9e8E
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&usize as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRjNtB5_5Debug3fmtCsb2tXkiy4HHk_6memchr
WARN kani_compiler::codegen_cprover_gotoc::codegen::rvalue Unable to find vtable symbol for virtual function <&u64 as std::fmt::Debug>::fmt, attempted lookup for symbol name: _RNvXsV_NtCs4YygHDVoDdI_4core3fmtRyNtB5_5Debug3fmtCsb2tXkiy4HHk_6memchr
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_fence_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3305 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_fence_release` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3306 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_fence_acqrel` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3307 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_fence_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3308 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xadd_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2995 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xadd_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2991 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xadd_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2992 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xadd_release` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2993 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xadd_acqrel` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2994 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xadd_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2995 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xadd_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2991 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xadd_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2992 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xadd_release` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2993 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xadd_acqrel` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2994 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xor_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3155 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xor_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3151 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xor_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3152 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xor_release` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3153 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xor_acqrel` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3154 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2960 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2961 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2962 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2960 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2961 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2962 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2960 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2961 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_load_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2962 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2979 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2975 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2976 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_release` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2977 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_acqrel` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2978 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2979 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2975 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2976 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_release` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2977 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_acqrel` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2978 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2979 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2975 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2976 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_release` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2977 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_xchg_acqrel` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2978 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_store_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2946 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_store_release` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2947 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_store_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2948 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_store_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2946 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_store_release` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2947 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_store_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:2948 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_relaxed_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3028 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_relaxed_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3030 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_relaxed_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3032 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acquire_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3033 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acquire_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3034 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acquire_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3036 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_release_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3037 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_release_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3039 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_release_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3041 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acqrel_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3042 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acqrel_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3043 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acqrel_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3045 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_seqcst_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3046 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_seqcst_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3047 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_seqcst_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3048 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_relaxed_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3028 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_relaxed_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3030 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_relaxed_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3032 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acquire_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3033 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acquire_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3034 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acquire_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3036 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_release_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3037 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_release_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3039 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_release_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3041 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acqrel_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3042 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acqrel_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3043 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_acqrel_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3045 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_seqcst_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3046 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_seqcst_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3047 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchg_seqcst_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3048 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_relaxed_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3070 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_relaxed_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3072 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_relaxed_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3074 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_acquire_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3075 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_acquire_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3076 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_acquire_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3078 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_release_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3079 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_release_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3081 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_release_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3083 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_acqrel_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3084 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_acqrel_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3085 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_acqrel_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3087 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_seqcst_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3088 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_seqcst_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3089 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_cxchgweak_seqcst_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3090 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_or_relaxed` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3140 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_or_seqcst` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3136 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_or_acquire` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3137 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_or_release` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3138 treated as a sequential operation.
WARN kani_compiler::codegen_cprover_gotoc::codegen::intrinsic Kani does not support concurrency for now. `atomic_or_acqrel` in /Users/fzaiser/.rustup/toolchains/nightly-2022-07-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3139 treated as a sequential operation.
```

</details>

This causes several problems:
* it's very noisy: the user does not get actionable feedback from it. They can do nothing to silence the warnings
* it lowers user trust: users might think that Kani does not actually support the program or that the analysis is unsound but
* **Kani's analysis is still sound** because it only supports single-threaded execution for now

I agree that we have to be careful about this if/when we introduce multi-threading, but printing warnings all the time does not seem to be the best path forward to me.

### PR DESCRIPTION
**Pull request by celinval**
### Description of changes: 

We were emitting warnings using the `warn` macro at every occurrence of a concurrent constructs, which wasn't very user friendly. Instead, we now aggregate them and only print one warning at the end, similar to how we handle unsupported constructs.

### Resolved issues:

Resolves #1460 ??

### Related RFC:

N/A

### Call-outs:

With this PR, I propose that we close #1460 in favor of reducing the verbosity of those messages by aggregating them as we did for unsupported constructs. @fzaiser @adpaco-aws, would that be OK?

The output now looks like this for the test `kani/Intrinsics/Atomic/Stable/Store/main.rs`:

```
$ kani main.rs --only-codegen
warning: Found the following unsupported constructs:
             - caller_location (1)
         
         Verification will fail if one or more of these constructs is reachable.
         See https://model-checking.github.io/kani/rust-feature-support.html for more details.

warning: Kani does not support concurrency for now. The following constructs will be treated as sequential operations:
             - atomic_store_relaxed (1)
             - atomic_load_seqcst (1)
             - atomic_store_seqcst (1)
             - atomic_store_release (1)
             - atomic_load_acquire (1)
             - atomic_load_relaxed (1)

warning: 2 warnings emitted
```

### Testing:

* How is this change tested?

* Is this a refactor change?

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs [hunk 1]
```diff
@@ -339,6 +339,17 @@ fn print_report(ctx: &GotocCtx, tcx: TyCtxt) {
         details.";
         tcx.sess.warn(&msg);
     }
+
+    if !ctx.concurrent_constructs.is_empty() {
+        let mut msg = String::from(
+            "Kani does not support concurrency for now. The following constructs will be treated \
```
Comment (zhassan-aws) [inline kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs:345]: I know this message was there from before, but I suggest we change it to
```suggestion
            "Kani currently does not support concurrency. The following constructs will be treated \
```

File: kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs [hunk 2]
```diff
@@ -339,6 +339,17 @@ fn print_report(ctx: &GotocCtx, tcx: TyCtxt) {
...
+            as sequential operations:\n",
+        );
+        for (construct, locations) in ctx.concurrent_constructs.iter() {
+            writeln!(&mut msg, "    - {} ({})", construct, locations.len()).unwrap();
```
Comment (zhassan-aws) [inline kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs:349]: For upcoming Rust toolchain update 😊 
```suggestion
            writeln!(&mut msg, "    - {construct} ({})", locations.len()).unwrap();
```

**Review by zhassan-aws — APPROVED** [review]
Thanks! A couple of minor comments.

Also, we're currently storing the location of each occurrence, but not using it. Would it make sense to include all the locations in the warning under some flag (e.g. `--verbose`) in case the user wants to find out where they're used?

**Comment by celinval** [comment]
> Thanks! A couple of minor comments.
> 
> Also, we're currently storing the location of each occurrence, but not using it. Would it make sense to include all the locations in the warning under some flag (e.g. `--verbose`) in case the user wants to find out where they're used?

I thought about expanding the location with `--verbose`, but I was looking at the logs, they tend to just print the same std file (`atomic.rs`). We could include the name of the calling function as well.

**Comment by celinval** [comment]
Should I lower it to an info instead of warning?? @zhassan-aws

**Comment by zhassan-aws** [comment]
Are you asking because we would already emit a warning if the program had other concurrency constructs (e.g. threads)? If so, I still suggest we keep it a warning to make it a bit more obvious to the user how Kani is handling them.

**Comment by zhassan-aws** [comment]
> That said, I rather not do this as part of this change. I understand that the new format loses that information, so let me know if you think it is a blocker. I could also skip saving the location for now (and even drop the counter in the message).

No, it's fine to do this in a separate PR.

File: kani-compiler/src/codegen_cprover_gotoc/utils/utils.rs [hunk 3]
```diff
@@ -66,6 +67,20 @@ impl<'tcx> GotocCtx<'tcx> {
             _ => None,
         }
     }
+
+    /// Store an occurrence of a concurrent construct that was treated as a sequential operation.
+    ///
+    /// Kani does not currently support concurrency and the compiler assumes that when generating
+    /// code for some specialized concurrent constructs that this is the case. We store all types of
+    /// operations that had this special handling and print a warning at the end of the compilation.
+    pub fn store_concurrent_construct(&mut self, operation_name: &str, loc: Location) {
```
Comment (adpaco-aws) [inline kani-compiler/src/codegen_cprover_gotoc/utils/utils.rs:76]: As mentioned, printing the location isn't useful at the moment. A better thing to do would be storing locations from function calls up to here, then print whichever is closes to the user's code. But we don't have anything like that at the moment, right?

File: kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs [hunk 4]
```diff
@@ -339,6 +339,17 @@ fn print_report(ctx: &GotocCtx, tcx: TyCtxt) {
         details.";
         tcx.sess.warn(&msg);
     }
+
+    if !ctx.concurrent_constructs.is_empty() {
+        let mut msg = String::from(
+            "Kani currently does not support concurrency. The following constructs will be treated \
```
Comment (adpaco-aws) [inline kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs:345]: This messaging could also be improved. In particular, I think we should avoid using "Kani" in our messages, and say something like "Concurrency is not supported at the moment". But I'm afraid this will break some stuff, so let's not do it here.

**Review by adpaco-aws — APPROVED** [review]
Thanks @celinval for doing this!

I'm in favor of merging it as is, just have a couple of comments to keep in mind.

File: kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs (hunk 4 above)
Comment (tedinski) [reply kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs:345]: > I think we should avoid using "Kani" in our messages

Why is that?

**Review by tedinski — APPROVED** [review]
lgtm, though my thoughts are:

1. CBMC supports concurrency... For some of these I wonder how hard it's really be to make (at least some of) them work as intended. We could reduce the warning count to the ones we really don't handle right.
2. It actually still looks like a lot of operations. Wonder if we should bother with any further condensation (e.g. "atomic load/store" as one?) But... this isn't important. Big enough improvement for one PR.

File: kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs (hunk 4 above)
Comment (adpaco-aws) [reply kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs:345]: You're running Kani, so it's odd printing messages that mention Kani in any way when you're already in that context. If I'm not mistaken, the Rust compiler won't use its own name in messages unless it's talking about specific editions (e.g., "this construct isn't supported in Rust 2018". Otherwise, I feel like it becomes repetitive for users to see messages like "Kani does this" or "Kani does that" (there may be exceptions, of course).
