### PR TITLE
Fix `unreachable!()` override macro + new tests

### LINKED ISSUE #1362: Compilation error when using `unreachable` macro
I tried this code:

```rust
#[kani::proof]
fn main() {
    let x = 5;
    unreachable!("The value of x is {}", x);
}
```

using the following command line invocation:

```
kani test.rs
```

with Kani version: cb1a6068a15

Compilation fails with:
```
$ kani test.rs 
error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> test.rs:4:5
    |
4   |     unreachable!("The value of x is {}", x);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ argument of type `&'static str` unexpected
    |
note: function defined here
   --> /home/ubuntu/git/kani/library/kani/src/lib.rs:124:8
    |
124 | pub fn panic(message: &'static str) -> ! {
    |        ^^^^^
    = note: this error originates in the macro `unreachable` (in Nightly builds, run with -Z macro-backtrace for more info)
help: remove the extra argument
   --> |/home/ubuntu/git/kani/library/std/src/lib.rs:147:9
    |
147 |         kani::panic(unreachable!("The value of x is {}", x)));
    |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error: aborting due to previous error

For more information about this error, try `rustc --explain E0061`.
Error: "Failed to compile crate."
Error: /home/ubuntu/git/kani/target/debug/kani-compiler exited with status exit status: 1
```

### PR DESCRIPTION
**Pull request by celinval**
### Description of changes: 

My latest change to handling panic messages actually broke `unreachable` macro. The main issue was the wrong position of a parenthesis and the fact that we didn't have tests that covered that specific case of the macro.

### Resolved issues:

Fixes #1362

### Call-outs:

One thing I haven't figured out yet is how to trigger an error if the user code uses edition 2021+ and has the following construct:

```rust
let msg = "blah";
panic!(msg);
```
This is actually an error in 2021+ but accepted in previous editions. The macro override that we perform accepts that no matter the edition though.

### Testing:

* How is this change tested? New test

* Is this a refactor change? No

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: library/std/src/lib.rs [hunk 1]
```diff
@@ -143,8 +143,14 @@ macro_rules! unreachable {
     ($($msg:literal)? $(,)?) => (
         kani::panic(concat!("internal error: entered unreachable code: ", $($msg)?))
     );
+    // Needed for 2018 and older rust editions.
+    // TODO: Is it possible to trigger an error if 2021 and above?
+    ($($msg:expr)? $(,)?) => (
```
Comment (zhassan-aws) [inline library/std/src/lib.rs:148]: Can you add a comment on each rule that mentions example of an `unreachable` statement captured by this rule (it is not immediately clear to me what this new rule captures)?

Comment (celinval) [reply library/std/src/lib.rs:148]: Sure.

**Review by zhassan-aws — APPROVED** [review]
Much clear now. Thanks!
