### PR TITLE
Running `verify-std` no longer changes Cargo files

### LINKED ISSUE #3574: Unexpected behavior for verify-std when run inside library directory
This issue was pointed out by @QinyuanWu in https://github.com/model-checking/verify-rust-std/discussions/98.

When the `kani verify-std` command is run inside the `library` directory of the `verify-rust-std` repository, it causes the `Cargo.toml` and `Cargo.lock` files to change:
```bash
$ pwd
/home/ubuntu/git/verify-rust-std/library
$ kani verify-std -Zunstable-options . -Z function-contracts -Z mem-predicates --harness ptr::non_null::verify
Kani Rust Verifier 0.55.0 (standalone)
    Creating library package
      Adding `kani_verify_std` as member of workspace at `/home/zyadh/git/verify-rust-std/library`
note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
    Updating crates.io index
     Locking 8 packages to latest compatible versions
      Adding proc-macro-error v1.0.4
      Adding proc-macro-error-attr v1.0.4
      Adding proc-macro2 v1.0.87
      Adding quote v1.0.37
      Adding syn v1.0.109 (latest: v2.0.79)
      Adding syn v2.0.79
      Adding unicode-ident v1.0.13
      Adding version_check v0.9.5
   Compiling proc-macro2 v1.0.87
   Compiling version_check v0.9.5
   Compiling unicode-ident v1.0.13
   Compiling syn v1.0.109
   Compiling safety v0.1.0 (/home/zyadh/git/verify-rust-std/library/contracts/safety)
   Compiling compiler_builtins v0.1.123
   Compiling libc v0.2.158
   Compiling memchr v2.5.0
   ...
```

```
$ git diff Cargo.toml
diff --git a/library/Cargo.toml b/library/Cargo.toml
index e744cfe5e0f..b60256ed7a8 100644
--- a/library/Cargo.toml
+++ b/library/Cargo.toml
@@ -2,7 +2,7 @@
 resolver = "1"
 members = [
   "std",
-  "sysroot",
+  "sysroot", "target/kani_verify_std",
 ]
 
 exclude = [
```
In addition, unless one runs `cargo clean`, any modifications to the source code will not be taken into account for the next `kani verify-std` run (i.e., apparently the command will run on a cached version of the library).

The solution is to run Kani outside of this directory, e.g. in the root directory of `verify-rust-std`.

### PR DESCRIPTION
**Pull request by celinval**
In order to create a dummy crate we were using `cargo init` command. However, this command will interact with any existing workspace.

Instead, explicitly create a dummy `Cargo.toml` and `src/lib.rs`.

Resolves #3574

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: kani-driver/src/call_cargo.rs [hunk 1]
```diff
@@ -46,10 +46,39 @@ pub struct CargoOutputs {
 
 impl KaniSession {
     /// Create a new cargo library in the given path.
+    ///
+    /// Since we cannot create a new workspace with `cargo init --lib`, we create the dummy
+    /// crate manually. =( See <https://github.com/rust-lang/cargo/issues/8365>.
+    ///
+    /// Without setting up a new workspace, cargo init will modify the workspace where this is
```
Comment (carolynzech) [inline kani-driver/src/call_cargo.rs:53]: Could you add ~1 sentence to this command explaining how exactly it modifies the workspace (i.e., what bad modifications we're trying to prevent)?

Comment (carolynzech) [reply kani-driver/src/call_cargo.rs:53]: Alternatively, can you link to the Kani issue #3574 here as well, so that people can see the diff for themselves?

File: kani-driver/src/call_cargo.rs [hunk 2]
```diff
@@ -46,10 +46,39 @@ pub struct CargoOutputs {
...
+
+        // Create dummy crate and write dummy body
+        let lib_path = path.join("src/lib.rs");
+        fs::write(&lib_path, "pub fn dummy() {}")?;
+
+        // Create Cargo.toml
+        fs::write(
+            &toml_path,
+            r#"[package]
+name = "dummy"
```
Comment (carolynzech) [inline kani-driver/src/call_cargo.rs:72]: Can you indent this so it's in line with line 71?

**Review by carolynzech — COMMENTED** [review]
LGTM! Just a few nits.

File: kani-driver/src/call_cargo.rs (hunk 2 above)
Comment (celinval) [reply kani-driver/src/call_cargo.rs:72]: This will create a weirdly indented `Cargo.toml` though because I'm using raw string.

File: kani-driver/src/call_cargo.rs (hunk 1 above)
Comment (celinval) [reply kani-driver/src/call_cargo.rs:53]: sure

File: kani-driver/src/call_cargo.rs [hunk 3]
```diff
@@ -46,10 +46,39 @@ pub struct CargoOutputs {
 
 impl KaniSession {
     /// Create a new cargo library in the given path.
+    ///
+    /// Since we cannot create a new workspace with `cargo init --lib`, we create the dummy
+    /// crate manually. =( See <https://github.com/rust-lang/cargo/issues/8365>.
+    ///
+    /// Without setting up a new workspace, cargo init will modify the workspace where this is
+    /// running.
```
Comment (celinval) [inline kani-driver/src/call_cargo.rs:54]:
```suggestion
    /// running. See <https://github.com/model-checking/kani/issues/3574> for details.
```

**Review by carolynzech — APPROVED** [review]
