### PR TITLE
Avoid mismatch when generating structs that represent scalar data but also include ZSTs

### LINKED ISSUE #2364: Kani panics during Goto translation for code using bitvec
Kani panics during Goto translation for code using the bitvec library.

Kani versions tested:  0.24.0, 0.25.0

To reproduce, create a lib crate with the following `Cargo.toml`:
```
[package]
name = "kani-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1"
```

Add the following to `src/lib.rs`:
```
use bitvec::prelude::{BitArr, BitArray, Msb0};

type MyStruct = BitArr!(for 1, in u8, Msb0);

fn f() -> MyStruct {
    BitArray::ZERO
}

#[cfg(kani)]
mod tests {
    use super::*;

    #[kani::proof]
    fn some_property() {
        let mut val = f();
        val.set(0, true);
    }
}
```

Run kani:
```
$ RUST_BACKTRACE=full cargo kani
   Compiling kani-test v0.1.0 (/home/ec2-user/dev/kani-test)
error: internal compiler error: Kani unexpectedly panicked at panicked at 'assertion failed: `(left == right)`
                                  left: `2`,
                                 right: `1`: Error in struct_expr; mismatch in number of fields and values.
                                    StructTag("tag-_15362072497429542738")
                                    [Expr { value: IntConstant(0), typ: Unsignedbv { width: 8 }, location: None }]', cprover_bindings/src/goto_program/expr.rs:782:9.

thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`: Error in struct_expr; mismatch in number of fields and values.
	StructTag("tag-_15362072497429542738")
	[Expr { value: IntConstant(0), typ: Unsignedbv { width: 8 }, location: None }]', cprover_bindings/src/goto_program/expr.rs:782:9
stack backtrace:
   0:     0x7fe8956f732a - std::backtrace_rs::backtrace::libunwind::trace::h081f29f716721cea
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fe8956f732a - std::backtrace_rs::backtrace::trace_unsynchronized::h1c7fc4c4ccf8cfff
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe8956f732a - std::sys_common::backtrace::_print_fmt::hb7786e9419686803
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fe8956f732a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h94ad8e373d395c6e
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fe89575945e - core::fmt::write::h46ba6a9e2a6d4adf
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/core/src/fmt/mod.rs:1232:17
   5:     0x7fe8956e7a75 - std::io::Write::write_fmt::h6f4267f20ec68788
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/io/mod.rs:1682:15
   6:     0x7fe8956f70f5 - std::sys_common::backtrace::_print::hb5c67b8e69014d61
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7fe8956f70f5 - std::sys_common::backtrace::print::h2ff0f6ec8fe8dee2
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7fe8956f9ebf - std::panicking::default_hook::{{closure}}::h8f2dc7f3e286efd1
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/panicking.rs:267:22
   9:     0x7fe8956f9bfb - std::panicking::default_hook::heeca694d4cd7d11c
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/panicking.rs:286:9
  10:     0x565317770f2d - kani_compiler::session::PANIC_HOOK::{{closure}}::{{closure}}::hb14bd8923604da61
  11:     0x56531777115b - kani_compiler::session::JSON_PANIC_HOOK::{{closure}}::{{closure}}::h83fbfacccda15e89
  12:     0x5653176f09b3 - kani_compiler::codegen_cprover_gotoc::utils::debug::DEFAULT_HOOK::{{closure}}::{{closure}}::h8598e9598da8eeb7
  13:     0x7fe8956fa6fa - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h9cd7f28d670041a2
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/alloc/src/boxed.rs:2002:9
  14:     0x7fe8956fa6fa - std::panicking::rust_panic_with_hook::h892e6adff61670d4
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/panicking.rs:692:13
  15:     0x7fe8956fa479 - std::panicking::begin_panic_handler::{{closure}}::he0859e3e131b2a3c
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/panicking.rs:579:13
  16:     0x7fe8956f77dc - std::sys_common::backtrace::__rust_end_short_backtrace::he7b65f460b4dc3cf
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/sys_common/backtrace.rs:137:18
  17:     0x7fe8956fa182 - rust_begin_unwind
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/panicking.rs:575:5
  18:     0x7fe895755e03 - core::panicking::panic_fmt::h4c3a1b54039d0595
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/core/src/panicking.rs:64:14
  19:     0x7fe895756309 - core::panicking::assert_failed_inner::he0ca732d156acafe
  20:     0x56531762fa4b - core::panicking::assert_failed::h60f7762499c7d476
  21:     0x5653178a5595 - cprover_bindings::goto_program::expr::Expr::struct_expr_from_values::h5313170e7983664e
  22:     0x56531767b7f5 - kani_compiler::codegen_cprover_gotoc::codegen::operand::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_single_variant_single_field::h856a55abda3a5749
  23:     0x56531767a3bf - kani_compiler::codegen_cprover_gotoc::codegen::operand::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_scalar::hf8dcd8912855886e
  24:     0x565317678073 - kani_compiler::codegen_cprover_gotoc::codegen::operand::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_const_value::h2857335c8e791718
  25:     0x56531767756d - kani_compiler::codegen_cprover_gotoc::codegen::operand::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_operand::h2d62e643e8e5a02d
  26:     0x5653176e7244 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h21e9344438eb315c
  27:     0x565317738ebe - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h407630fd894e7718
  28:     0x56531769b1c1 - kani_compiler::codegen_cprover_gotoc::codegen::statement::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_funcall_args::hc83057b12bf746a4
  29:     0x565317697cbd - kani_compiler::codegen_cprover_gotoc::codegen::statement::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_terminator::h4d86b2ff53a9f0e9
  30:     0x56531763c1f2 - kani_compiler::codegen_cprover_gotoc::codegen::function::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_function::h4f53ea8d82ff8395
  31:     0x5653176e4480 - std::thread::local::LocalKey<T>::with::h40521ba7a02703d9
  32:     0x565317750be4 - <kani_compiler::codegen_cprover_gotoc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h8b8bdfc55be3a56f
  33:     0x7fe893623081 - <rustc_session[4c51ba081ed00764]::session::Session>::time::<alloc[6e60c50040f84f8b]::boxed::Box<dyn core[be13c3a4a0166a5d]::any::Any>, rustc_interface[5e583a021ee4110c]::passes::start_codegen::{closure#0}>
  34:     0x7fe893622ba9 - rustc_interface[5e583a021ee4110c]::passes::start_codegen
  35:     0x7fe8936206b9 - <rustc_interface[5e583a021ee4110c]::passes::QueryContext>::enter::<<rustc_interface[5e583a021ee4110c]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[be13c3a4a0166a5d]::result::Result<alloc[6e60c50040f84f8b]::boxed::Box<dyn core[be13c3a4a0166a5d]::any::Any>, rustc_errors[a3f9bdfc7e623733]::ErrorGuaranteed>>
  36:     0x7fe89361c59d - <rustc_interface[5e583a021ee4110c]::queries::Queries>::ongoing_codegen
  37:     0x7fe89361b4bf - rustc_span[90cd83e1cc6358cf]::with_source_map::<core[be13c3a4a0166a5d]::result::Result<(), rustc_errors[a3f9bdfc7e623733]::ErrorGuaranteed>, rustc_interface[5e583a021ee4110c]::interface::run_compiler<core[be13c3a4a0166a5d]::result::Result<(), rustc_errors[a3f9bdfc7e623733]::ErrorGuaranteed>, rustc_driver[d168a790576a7dcc]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  38:     0x7fe8936130f4 - <scoped_tls[51f5e5aadba18ca0]::ScopedKey<rustc_span[90cd83e1cc6358cf]::SessionGlobals>>::set::<rustc_interface[5e583a021ee4110c]::interface::run_compiler<core[be13c3a4a0166a5d]::result::Result<(), rustc_errors[a3f9bdfc7e623733]::ErrorGuaranteed>, rustc_driver[d168a790576a7dcc]::run_compiler::{closure#1}>::{closure#0}, core[be13c3a4a0166a5d]::result::Result<(), rustc_errors[a3f9bdfc7e623733]::ErrorGuaranteed>>
  39:     0x7fe8936127f2 - std[6b8bd2f9a6d311d6]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[5e583a021ee4110c]::util::run_in_thread_pool_with_globals<rustc_interface[5e583a021ee4110c]::interface::run_compiler<core[be13c3a4a0166a5d]::result::Result<(), rustc_errors[a3f9bdfc7e623733]::ErrorGuaranteed>, rustc_driver[d168a790576a7dcc]::run_compiler::{closure#1}>::{closure#0}, core[be13c3a4a0166a5d]::result::Result<(), rustc_errors[a3f9bdfc7e623733]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[be13c3a4a0166a5d]::result::Result<(), rustc_errors[a3f9bdfc7e623733]::ErrorGuaranteed>>
  40:     0x7fe893c93d8c - <<std[6b8bd2f9a6d311d6]::thread::Builder>::spawn_unchecked_<rustc_interface[5e583a021ee4110c]::util::run_in_thread_pool_with_globals<rustc_interface[5e583a021ee4110c]::interface::run_compiler<core[be13c3a4a0166a5d]::result::Result<(), rustc_errors[a3f9bdfc7e623733]::ErrorGuaranteed>, rustc_driver[d168a790576a7dcc]::run_compiler::{closure#1}>::{closure#0}, core[be13c3a4a0166a5d]::result::Result<(), rustc_errors[a3f9bdfc7e623733]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[be13c3a4a0166a5d]::result::Result<(), rustc_errors[a3f9bdfc7e623733]::ErrorGuaranteed>>::{closure#1} as core[be13c3a4a0166a5d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7fe895704793 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf05b4b3c0eebe09f
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/alloc/src/boxed.rs:1988:9
  42:     0x7fe895704793 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h42d3453ce26899c4
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/alloc/src/boxed.rs:1988:9
  43:     0x7fe895704793 - std::sys::unix::thread::Thread::new::thread_start::h53c357220671f65c
                               at /rustc/f3126500f25114ba4e0ac3e76694dd45a22de56d/library/std/src/sys/unix/thread.rs:108:17
  44:     0x7fe890ca744b - start_thread
  45:     0x7fe8906a252f - __clone
  46:                0x0 - <unknown>

Kani unexpectedly panicked during compilation.
Please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md

[Kani] current codegen item: codegen_function: bitvec::ptr::BitPtr::<bitvec::ptr::Mut, u8, bitvec::order::Msb0>::from_slice_mut
_RNvMs0_NtNtCsOWo2AhJUyI_6bitvec3ptr6singleINtB5_6BitPtrNtNtCs7wy8fYxGRNo_3wyz4comu3MuthNtNtB9_5order4Msb0E14from_slice_mutCs6bxxippQzXe_9kani_test
[Kani] current codegen location: Loc { file: "/home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-1.0.1/src/ptr/single.rs", function: None, start_line: 383, start_col: Some(5), end_line: 383, end_col: Some(51) }
error: could not compile `kani-test`
error: Failed to compile `kani-test` due to an internal compiler error.: error: internal compiler error: Kani unexpectedly panicked at panicked at 'assertion failed: `(left == right)`
                                  left: `2`,
                                 right: `1`: Error in struct_expr; mismatch in number of fields and values.
                                    StructTag("tag-_15362072497429542738")
                                    [Expr { value: IntConstant(0), typ: Unsignedbv { width: 8 }, location: None }]', cprover_bindings/src/goto_program/expr.rs:782:9.

```

### LINKED ISSUE #2680: ICE: mismatch in number of fields and values.
I tried this code: `tests/kani.rs`
```rust
#[cfg(kani)]
#[kani::proof]
fn kani() {

    let input: kani::slice::AnySlice<u8, { usize::MAX }> = kani::slice::any_slice();

    if let Ok(value) = rasn::der::decode::<rasn_pkix::Certificate>(&input) {
        assert_eq!(value, rasn::der::decode(&rasn::der::encode(&value).unwrap()).unwrap());
    }

    if let Ok(value) = rasn::uper::decode::<rasn_pkix::Certificate>(&input) {
        assert_eq!(value, rasn::uper::decode(&rasn::uper::encode(&value).unwrap()).unwrap());
    }

    if let Ok(value) = rasn::aper::decode::<rasn_pkix::Certificate>(&input) {
        assert_eq!(value, rasn::aper::decode(&rasn::aper::encode(&value).unwrap()).unwrap());
    }
}
```

using the following command line invocation:

```
cargo kani --tests
```

with Kani version:

I expected to see this happen: it works

Instead, this happened:

```
error: internal compiler error: Kani unexpectedly panicked at panicked at cprover_bindings/src/goto_program/expr.rs:804:9:
                                assertion failed: `(left == right)`
                                  left: `2`,
                                 right: `1`: Error in struct_expr; mismatch in number of fields and values.
                                    StructTag("tag-_161424092592971241517604180463813633314")
                                    [Expr { value: IntConstant(0), typ: Unsignedbv { width: 8 }, location: None, size_of_annotation: None }].

thread 'rustc' panicked at cprover_bindings/src/goto_program/expr.rs:804:9:
assertion failed: `(left == right)`
  left: `2`,
 right: `1`: Error in struct_expr; mismatch in number of fields and values.
	StructTag("tag-_161424092592971241517604180463813633314")
	[Expr { value: IntConstant(0), typ: Unsignedbv { width: 8 }, location: None, size_of_annotation: None }]
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: cprover_bindings::goto_program::expr::Expr::struct_expr_from_values
   5: kani_compiler::codegen_cprover_gotoc::codegen::operand::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_single_variant_single_field
   6: kani_compiler::codegen_cprover_gotoc::codegen::operand::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_scalar
   7: kani_compiler::codegen_cprover_gotoc::codegen::operand::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_const_value
   8: kani_compiler::codegen_cprover_gotoc::codegen::operand::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_operand
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  10: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  11: kani_compiler::codegen_cprover_gotoc::codegen::rvalue::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_rvalue
  12: kani_compiler::codegen_cprover_gotoc::codegen::statement::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_statement
  13: kani_compiler::codegen_cprover_gotoc::codegen::block::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_block
  14: kani_compiler::codegen_cprover_gotoc::utils::debug::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info
  15: kani_compiler::codegen_cprover_gotoc::compiler_interface::GotocCodegenBackend::codegen_items
  16: <kani_compiler::codegen_cprover_gotoc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  17: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
  18: rustc_interface::passes::start_codegen
  19: <rustc_middle::ty::context::GlobalCtxt>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>
  20: <rustc_interface::queries::Queries>::ongoing_codegen
  21: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Kani unexpectedly panicked during compilation.
Please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md

[Kani] current codegen item: codegen_function: bitvec::domain::Domain::<'_, wyz::comu::Mut, u8>::new
_RNvMs4_NtCs4MAoNlLLqrn_6bitvec6domainINtB5_6DomainNtNtCsfYGE6EJ4wD9_3wyz4comu3MuthE3newCscrWoMilNx7E_4rasn
[Kani] current codegen location: Loc { file: "/Users/ep/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitvec-1.0.1/src/domain.rs", function: None, start_line: 377, start_col: Some(5), end_line: 378, end_col: Some(67) }
error: could not compile `rasn` (test "kani")
error: Failed to compile `kani` due to an internal compiler error.: error: internal compiler error: Kani unexpectedly panicked at panicked at cprover_bindings/src/goto_program/expr.rs:804:9:
                                assertion failed: `(left == right)`
                                  left: `2`,
                                 right: `1`: Error in struct_expr; mismatch in number of fields and values.
                                    StructTag("tag-_161424092592971241517604180463813633314")
                                    [Expr { value: IntConstant(0), typ: Unsignedbv { width: 8 }, location: None, size_of_annotation: None }].
```

### PR DESCRIPTION
**Pull request by adpaco-aws**
### Description of changes: 

This PR considers another case for the code generation of scalar data. In particular, when the expected type is an ADT, we previously considered two cases: either there is no field or there is one. But in cases where the ADT includes a ZST, the ADT will contain multiple fields: one associated to the scalar data, and other fields associated to the ZSTs. In those cases, we ended up crashing as in #2680:

```rust
error: internal compiler error: Kani unexpectedly panicked at panicked at cprover_bindings/src/goto_program/expr.rs:804:9:
                                assertion failed: `(left == right)`
                                  left: `2`,
                                 right: `1`: Error in struct_expr; mismatch in number of fields and values.
                                    StructTag("tag-_161424092592971241517604180463813633314")
                                    [Expr { value: IntConstant(0), typ: Unsignedbv { width: 8 }, location: None, size_of_annotation: None }].

thread 'rustc' panicked at cprover_bindings/src/goto_program/expr.rs:804:9:
assertion failed: `(left == right)`
  left: `2`,
 right: `1`: Error in struct_expr; mismatch in number of fields and values.
	StructTag("tag-_161424092592971241517604180463813633314")
	[Expr { value: IntConstant(0), typ: Unsignedbv { width: 8 }, location: None, size_of_annotation: None }]
```

With the changes in this PR, that's no longer the case.

Resolves #2364 
Resolves #2680

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs [hunk 1]
```diff
@@ -304,24 +304,58 @@ impl<'tcx> GotocCtx<'tcx> {
...
                         } else {
                             unimplemented!()
                         }
                     } else {
-                        // otherwise, there is just one field, which is stored as the scalar data
-                        let field = &variant.fields[0usize.into()];
-                        let fty = field.ty(self.tcx, subst);
-
-                        let overall_t = self.codegen_ty(ty);
+                        // Otherwise, there is at least one field. Again, there are two cases.
```
Comment (celinval) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:318]: you could say that there's just one non-ZST field

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs [hunk 2]
```diff
@@ -304,24 +304,58 @@ impl<'tcx> GotocCtx<'tcx> {
...
+                                    span,
+                                    overall_type,
+                                    field_type,
+                                )
+                            } else {
+                                // There are multiple fields, but only one is related to the scalar data.
+                                // The rest of them correspond to phantom data (ZST).
+                                let field_types: Vec<Ty<'_>> =
+                                    variant.fields.iter().map(|f| f.ty(self.tcx, subst)).collect();
+                                // Check that there is a single non-phantom field
```
Comment (celinval) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:336]: This is not only phantom data related. Any ZST can trigger this issue. For example:

```rust
struct Empty {}

pub struct Foo {
    x: u8,
    _t: Empty,
}

#[kani::proof]
fn check_zst() {
    const C: Foo = Foo { x: 0, _t: Empty {} };
    assert_eq!(C.x, 0);
}
```
So please update the comments and variables to reflect that.

File: tests/cargo-kani/phantom-data/src/lib.rs [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+
+use std::marker::PhantomData;
+
+pub struct Foo<R> {
+    x: u8,
+    _t: PhantomData<R>,
+}
+
+#[kani::proof]
+fn main() {
```
Comment (celinval) [inline tests/cargo-kani/phantom-data/src/lib.rs:14]: nit: Can you please provide a more meaningful name to your check? We should stop using `main` everywhere since this is not a patter we expect others to follow.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs [hunk 4]
```diff
@@ -304,24 +304,58 @@ impl<'tcx> GotocCtx<'tcx> {
...
+                                let non_phantom_field_types: Vec<_> =
+                                    field_types.iter().filter(|t| !t.is_phantom_data()).collect();
+                                assert!(
+                                    non_phantom_field_types.len() == 1,
+                                    "error: expected exactly one field that is not phantom data"
+                                );
+                                let field_values: Vec<Expr> = field_types
+                                    .iter()
+                                    .map(|t| {
+                                        if t.is_phantom_data() {
```
Comment (celinval) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:346]: I don't think this will in fact fix the issue I just pasted above. Can you please check?

I recommend you use the following function instead:

https://github.com/model-checking/kani/blob/dba16744ee1d9299b379d9f876c28a8d07376933/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs#L456-L458

**Review by celinval — CHANGES_REQUESTED** [review]
I'm worried this fix is too specific to PhantomData. Instead, we want something that will work for any struct with multiple fields where only one is not ZST.

File: tests/cargo-kani/phantom-data/src/lib.rs (hunk 3 above)
Comment (remi-delmas-3000) [reply tests/cargo-kani/phantom-data/src/lib.rs:14]: we also need a test with ZST that are not PhantomData

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs [hunk 5]
```diff
@@ -304,24 +304,58 @@ impl<'tcx> GotocCtx<'tcx> {
...
-                        // otherwise, there is just one field, which is stored as the scalar data
-                        let field = &variant.fields[0usize.into()];
-                        let fty = field.ty(self.tcx, subst);
-
-                        let overall_t = self.codegen_ty(ty);
+                        // Otherwise, there is at least one field. Again, there are two cases.
+                        let overall_type = self.codegen_ty(ty);
                         if adt.is_struct() {
-                            self.codegen_single_variant_single_field(s, span, overall_t, fty)
+                            if variant.fields.len() == 1 {
```
Comment (remi-delmas-3000) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:321]: Can this branch and the next branch of the if-then-else be merged ? it seems like the single  non-zst field case is a special case of n-fields with a single non-zst.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs (hunk 4 above)
Comment (adpaco-aws) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs]: Thanks! You're right, other ZST would cause the compiler to crash (for example, the test you sent in the other comment).

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs (hunk 2 above)
Comment (adpaco-aws) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs]: True. I believe all comments, variables and tests have been updated, please take a look.

File: tests/cargo-kani/phantom-data/src/lib.rs (hunk 3 above)
Comment (adpaco-aws) [reply tests/cargo-kani/phantom-data/src/lib.rs]: We now have properly named tests for both ZST and `PhantomData`. It seemed a bit redundant to me since `PhantomData` is just a special case of ZST, but it doesn't hurt to keep both.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs (hunk 5 above)
Comment (adpaco-aws) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs]: Yes, it's done. I've even gone further and removed the `adt.is_struct()` condition by restricting the outer one only to structs.

**Review by celinval — APPROVED** [review]
Awesome! Thanks @adpaco-aws

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs [hunk 6]
```diff
@@ -303,38 +303,48 @@ impl<'tcx> GotocCtx<'tcx> {
...
-                if adt.is_struct() || adt.is_union() {
-                    // in this case, we must have a one variant ADT. there are two cases
-                    let variant = &adt.variants().raw[0];
-                    // if there is no field, then it's just a ZST
+                if adt.is_struct() {
+                    // In this case, we must have a one variant ADT. There are two cases.
+                    let variant = adt.non_enum_variant();
+                    let overall_type = self.codegen_ty(ty);
+                    // If there is no field, then it's just a ZST.
                     if variant.fields.is_empty() {
```
Comment (remi-delmas-3000) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:311]: is this condition really reachable considering constant evaluation returned a scalar value ?

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs [hunk 7]
```diff
@@ -303,38 +303,48 @@ impl<'tcx> GotocCtx<'tcx> {
                 }
             }
             (Scalar::Int(_), ty::Adt(adt, subst)) => {
```
Comment (remi-delmas-3000) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:305]: what about floats and other integer types of different sizes

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs [hunk 8]
```diff
@@ -303,38 +303,48 @@ impl<'tcx> GotocCtx<'tcx> {
...
+                            .collect();
+                        Expr::struct_expr_from_values(
+                            overall_type,
+                            field_values,
+                            &self.symbol_table,
+                        )
                     }
-                } else {
-                    // if it's an enum
+                } else if adt.is_enum() {
```
Comment (remi-delmas-3000) [inline kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:341]: can we have a case where all enums have zero sized fields and the scalar value returned by the constant evaluation represents the discriminant of the enum ?

File: tests/cargo-kani/codegen-scalar-with-phantom/check_phantom_data.expected [hunk 9]
```diff
@@ -0,0 +1,4 @@
+Status: SUCCESS\
+Description: "assertion failed: C.x == 0"
+
+VERIFICATION:- SUCCESSFUL
```
Comment (remi-delmas-3000) [inline tests/cargo-kani/codegen-scalar-with-phantom/check_phantom_data.expected:4]: missign newline

File: tests/cargo-kani/codegen-scalar-with-zsts/check_zst.expected [hunk 10]
```diff
@@ -0,0 +1,4 @@
+Status: SUCCESS\
+Description: "assertion failed: C.x == 0"
+
+VERIFICATION:- SUCCESSFUL
```
Comment (remi-delmas-3000) [inline tests/cargo-kani/codegen-scalar-with-zsts/check_zst.expected:4]: missing new line

File: tests/cargo-kani/codegen-scalar-with-zsts/src/lib.rs [hunk 11]
```diff
@@ -0,0 +1,17 @@
...
+
+pub struct Foo {
+    x: u8,
+    _t: Empty,
+}
+
+#[kani::proof]
+fn check_zst() {
+    const C: Foo = Foo { x: 0, _t: Empty {} };
+    assert_eq!(C.x, 0);
```
Comment (remi-delmas-3000) [inline tests/cargo-kani/codegen-scalar-with-zsts/src/lib.rs:16]: should the tests cover more cases where constants reduce to a scalar value ? floats, doubles, ints of all sizes, etc. enums with more than one variants but all have zst fields, etc ?

File: tests/cargo-kani/codegen-scalar-with-phantom/check_phantom_data.expected (hunk 9 above)
Comment (adpaco-aws) [reply tests/cargo-kani/codegen-scalar-with-phantom/check_phantom_data.expected]: Added.

File: tests/cargo-kani/codegen-scalar-with-zsts/check_zst.expected (hunk 10 above)
Comment (adpaco-aws) [reply tests/cargo-kani/codegen-scalar-with-zsts/check_zst.expected]: Added.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs (hunk 6 above)
Comment (adpaco-aws) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs]: Looks like it's not, at least according to our regression. I've removed this `if-then-else`. Thanks for pointing this out!

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs (hunk 8 above)
Comment (adpaco-aws) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:332]: Sorry, I don't understand the question.

This PR does not change how we generate code for ADTs represented with `enum`s, only ADTs which are `struct`s because that's when the crash happened. The change you highlighted comes from the branch clean-up.

File: kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs (hunk 7 above)
Comment (remi-delmas-3000) [reply kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:305]: Thanks for the precision !

**Review by remi-delmas-3000 — APPROVED** [review]
