### PR TITLE
Do not override `std` library during playback

### LINKED ISSUE #2850: Do not override `std` functions when running concrete playback
For example, when running a concrete playback to figure out why an `assert_eq!()` failed, it is super useful for the user to see the proper assertion message where the values get printed.

### PR DESCRIPTION
**Pull request by celinval**
We override a few std functions to improve verification time or verification results, however, those functions are quite helpful during concrete execution. Thus, avoid overriding functions when executing concrete playback.

Resolves #2850

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: tests/script-based-pre/playback_print/print_vars.rs [hunk 1]
```diff
@@ -0,0 +1,20 @@
+// Copyright Kani Contributors
+// SPDX-License-Identifier: Apache-2.0 OR MIT
+//
+// compile-flags: --edition 2021
+// kani-flags: playback
```
Comment (adpaco-aws) [inline tests/script-based-pre/playback_print/print_vars.rs:5]: I don't think these are being used, but if you wanted to leave them for documentation purposes we should add `-Z concrete-playback` to `kani-flags`.

File: tests/script-based-pre/playback_print/playback_print.sh [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+echo "[TEST] Generate test..."
+kani ${RS_FILE} -Z concrete-playback --concrete-playback=inplace
+
+echo "[TEST] Run test..."
+kani playback -Z concrete-playback ${RS_FILE} 2>&1 | tee output.log
+
+echo "------ Check output ----------"
+
+set -e
```
Comment (adpaco-aws) [inline tests/script-based-pre/playback_print/playback_print.sh:29]: Why not `set -e` earlier?

File: tests/script-based-pre/playback_print/playback_print.sh [hunk 3]
```diff
@@ -0,0 +1,40 @@
+#!/usr/bin/env bash
+# Copyright Kani Contributors
+# SPDX-License-Identifier: Apache-2.0 OR MIT
+# Test that concrete playback -Z concrete-playback does not override std print
+# functions
```
Comment (adpaco-aws) [inline tests/script-based-pre/playback_print/playback_print.sh:5]:
```suggestion

# Test that concrete playback does not override std print functions
```
or
```suggestion

# Test that `kani playback -Z concrete-playback` does not override std print functions
```

**Review by zhassan-aws — APPROVED** [review]
Thanks

File: tests/script-based-pre/playback_print/playback_print.sh (hunk 2 above)
Comment (celinval) [reply tests/script-based-pre/playback_print/playback_print.sh:29]: Because Kani exit status is non-zero when the verification fail.

File: tests/script-based-pre/playback_print/print_vars.rs (hunk 1 above)
Comment (celinval) [inline tests/script-based-pre/playback_print/print_vars.rs:5]:
```suggestion
// Harness used to test that playback do not override assertion and panic functions.
```
