### PR TITLE
Fix: regression test from #3888 has version control change

### LINKED ISSUE #3891: Changes from #3888 result in tests modifying files under version control
**Proposed change:** We need to fix test execution as introduced in #3888 so as not to leave behind files that are (git) version controlled.

**Motivation:** PRs like https://github.com/model-checking/kani/pull/3890 are the consequence of regression-test executing leaving behind modified files. Similarly, developers running tests locally before pushing changes will inadvertently push unrelated changes to the repository.

### PR DESCRIPTION
**Pull request by carolynzech**
Resolves #3891

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: tests/script-based-pre/playback_array/playback_array.sh [hunk 1]
```diff
@@ -0,0 +1,18 @@
+#!/usr/bin/env bash
+# Copyright Kani Contributors
+# SPDX-License-Identifier: Apache-2.0 OR MIT
+
```
Comment (tautschnig) [inline tests/script-based-pre/playback_array/playback_array.sh:4]:
```suggestion

set -e
```

File: tests/script-based-pre/playback_array/playback_array.sh [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+cp array.rs ${RS_FILE}
+
+echo "[TEST] Generate test..."
+kani ${RS_FILE} -Z concrete-playback --concrete-playback=inplace
+
+echo "[TEST] Run test..."
+kani playback -Z concrete-playback ${RS_FILE}
+
+# Cleanup
+rm ${RS_FILE}
```
Comment (tautschnig) [inline tests/script-based-pre/playback_array/playback_array.sh:18]:
```suggestion
```

File: tests/script-based-pre/playback_array/playback_array.sh [hunk 3]
```diff
@@ -0,0 +1,18 @@
+#!/usr/bin/env bash
+# Copyright Kani Contributors
+# SPDX-License-Identifier: Apache-2.0 OR MIT
+
+set -o pipefail
+set -o nounset
+
```
Comment (tautschnig) [inline tests/script-based-pre/playback_array/playback_array.sh:7]:
```suggestion

cleanup()
{
  rm ${RS_FILE}
}
trap cleanup EXIT

```

**Review by tautschnig — APPROVED** [review]

File: tests/script-based-pre/playback_array/playback_array.sh [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+{
+  rm ${RS_FILE}
+}
+trap cleanup EXIT
+
+RS_FILE="modified.rs"
+cp array.rs ${RS_FILE}
+
+echo "[TEST] Generate test..."
+kani ${RS_FILE} -Z concrete-playback --concrete-playback=inplace
```
Comment (tautschnig) [inline tests/script-based-pre/playback_array/playback_array.sh:19]:
```suggestion
kani ${RS_FILE} -Z concrete-playback --concrete-playback=inplace || true
```
as this Kani command will have a non-zero return code as it does find property violations (and the `set -e` now makes the script terminate early).

Comment (carolynzech) [reply tests/script-based-pre/playback_array/playback_array.sh:19]: Hm, I wonder if we will also need this after the `playback` command, since that fails too?

Comment (tautschnig) [reply tests/script-based-pre/playback_array/playback_array.sh:19]: I'd say for the last one it is the right overall exit code.
